;; INNER_CALIBRATION = 890
(module
  (func $main (export "main")
    (local $y i32)

    (local.set $y (i32.const 89000 (;$INNER_ITERATIONS;)))
    (loop $l
      (call $which_is_null (ref.null func) (ref.null func))
      (drop)
      (call $which_is_null (ref.func 0)    (ref.null func))
      (drop)
      (call $which_is_null (ref.null func) (ref.func 0))
      (drop)
      (call $which_is_null (ref.func 0)    (ref.func 0))
      (drop)
      (br_if 0 (local.tee $y (i32.sub (local.get $y) (i32.const 1))))
    )
  )
  (func $which_is_null (param funcref funcref) (result i32)
    (i32.const 0)
    (br_on_null 0 (local.get 0))
    (drop)
    (drop)
    (i32.const 1)
    (br_on_null 0 (local.get 1))
    (drop)
    (drop)
    (i32.const 2)
  )	
)
