;; INNER_CALIBRATION = 33500
(module
  (func $start (export "_start")
    (call $main)
  )
  (func $main (export "main")
    (local $y i32)
    (local.set $y (i32.const 3350000))
    (loop $l
      (local.tee $y (i32.sub (local.get $y) (i32.const 1)))
      (br_if $l)
    )
    (call $A (i32.const 3))
  )
  (func $A (param i32)
    (local $y i32)
    (br_if 0 (i32.eqz (local.get 0)))
    (local.set $y (i32.const 3350000))
    (loop $l
      (local.tee $y (i32.sub (local.get $y) (i32.const 1)))
      (br_if $l)
    )
    (call $A (i32.sub (local.get 0) (i32.const 1)))
  )
)
