;; INNER_CALIBRATION = 115
;; array.set: writing elements of different kinds, cycling through a 1024-element array.
(module
  (type $leaf (struct (field i32)))
  (type $i8s (array (mut i8)))
  (type $i32s (array (mut i32)))
  (type $f64s (array (mut f64)))
  (type $refs (array (mut (ref null $leaf))))
  (type $anys (array (mut anyref)))
  (func $main (export "main")
    (local $y i32)
    (local $a8 (ref $i8s))
    (local $a32 (ref $i32s))
    (local $af64 (ref $f64s))
    (local $aref (ref $refs))
    (local $aany (ref $anys))
    (local.set $a8 (array.new_default $i8s (i32.const 1024)))
    (local.set $a32 (array.new_default $i32s (i32.const 1024)))
    (local.set $af64 (array.new_default $f64s (i32.const 1024)))
    (local.set $aref (array.new_default $refs (i32.const 1024)))
    (local.set $aany (array.new_default $anys (i32.const 1024)))
    (local.set $y (i32.const 1 (;$REPEAT;)))
    (loop $l
      (call $set_i8 (local.get $a8) (i32.const 11500 (;$INNER_ITERATIONS;)))
      (call $set_i32 (local.get $a32) (i32.const 11500 (;$INNER_ITERATIONS;)))
      (call $set_f64 (local.get $af64) (i32.const 11500 (;$INNER_ITERATIONS;)))
      (call $set_ref (local.get $aref) (i32.const 11500 (;$INNER_ITERATIONS;)))
      (call $set_anyref_i31 (local.get $aany) (i32.const 11500 (;$INNER_ITERATIONS;)))
      (local.tee $y (i32.sub (local.get $y) (i32.const 1)))
      (br_if $l)
    )
  )
  (func $set_i8 (param $a (ref $i8s)) (param $n i32)
    (loop $l
      (array.set $i8s (local.get $a) (i32.and (local.get $n) (i32.const 1023)) (local.get $n))
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
  )
  (func $set_i32 (param $a (ref $i32s)) (param $n i32)
    (loop $l
      (array.set $i32s (local.get $a) (i32.and (local.get $n) (i32.const 1023)) (local.get $n))
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
  )
  (func $set_f64 (param $a (ref $f64s)) (param $n i32)
    (loop $l
      (array.set $f64s (local.get $a) (i32.and (local.get $n) (i32.const 1023)) (f64.const 1.5))
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
  )
  ;; A struct reference into a typed reference array.
  (func $set_ref (param $a (ref $refs)) (param $n i32)
    (local $leaf (ref $leaf))
    (local.set $leaf (struct.new $leaf (i32.const 1)))
    (loop $l
      (array.set $refs (local.get $a) (i32.and (local.get $n) (i32.const 1023)) (local.get $leaf))
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
  )
  ;; An i31 into an anyref array.
  (func $set_anyref_i31 (param $a (ref $anys)) (param $n i32)
    (loop $l
      (array.set $anys (local.get $a) (i32.and (local.get $n) (i32.const 1023)) (ref.i31 (local.get $n)))
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
  )
)
