;; INNER_CALIBRATION = 0.19
;; Linear search of 1024-element arrays: an i32 value, and a struct reference (by ref.eq) in an
;; anyref array, each located at the end.
(module
  (type $leaf (struct (field i32)))
  (type $i32s (array (mut i32)))
  (type $anys (array (mut anyref)))
  (func $main (export "main")
    (local $y i32)
    (local $a32 (ref $i32s))
    (local $aany (ref $anys))
    (local $target (ref $leaf))
    (local.set $a32 (array.new $i32s (i32.const 0) (i32.const 1024)))
    (array.set $i32s (local.get $a32) (i32.const 1023) (i32.const 42))
    (local.set $target (struct.new $leaf (i32.const 42)))
    (local.set $aany (array.new $anys (ref.i31 (i32.const 0)) (i32.const 1024)))
    (array.set $anys (local.get $aany) (i32.const 1023) (local.get $target))
    (local.set $y (i32.const 1 (;$REPEAT;)))
    (loop $l
      (drop (call $find_i32_n (local.get $a32) (i32.const 19 (;$INNER_ITERATIONS;))))
      (drop (call $find_ref_n (local.get $aany) (local.get $target) (i32.const 19 (;$INNER_ITERATIONS;))))
      (local.tee $y (i32.sub (local.get $y) (i32.const 1)))
      (br_if $l)
    )
  )
  (func $find_i32 (param $a (ref $i32s)) (param $v i32) (result i32)
    (local $i i32)
    (block $done
      (loop $l
        (br_if $done (i32.ge_u (local.get $i) (array.len (local.get $a))))
        (br_if $done (i32.eq (array.get $i32s (local.get $a) (local.get $i)) (local.get $v)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $l)
      )
    )
    (local.get $i)
  )
  (func $find_ref (param $a (ref $anys)) (param $v eqref) (result i32)
    (local $i i32)
    (block $done
      (loop $l
        (br_if $done (i32.ge_u (local.get $i) (array.len (local.get $a))))
        (br_if $done (ref.eq (ref.cast eqref (array.get $anys (local.get $a) (local.get $i))) (local.get $v)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $l)
      )
    )
    (local.get $i)
  )
  (func $find_i32_n (param $a (ref $i32s)) (param $n i32) (result i32)
    (local $acc i32)
    (loop $l
      (local.set $acc (i32.add (local.get $acc) (call $find_i32 (local.get $a) (i32.const 42))))
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
    (local.get $acc)
  )
  (func $find_ref_n (param $a (ref $anys)) (param $v eqref) (param $n i32) (result i32)
    (local $acc i32)
    (loop $l
      (local.set $acc (i32.add (local.get $acc) (call $find_ref (local.get $a) (local.get $v))))
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
    (local.get $acc)
  )
)
