;; INNER_CALIBRATION = 103
;; array.get: reading elements of different kinds, cycling through a 1024-element array.
(module
  (type $i8s (array (mut i8)))
  (type $i16s (array (mut i16)))
  (type $i32s (array (mut i32)))
  (type $i64s (array (mut i64)))
  (type $anys (array (mut anyref)))
  (func $main (export "main")
    (local $y i32)
    (local $a8 (ref $i8s))
    (local $a16 (ref $i16s))
    (local $a32 (ref $i32s))
    (local $a64 (ref $i64s))
    (local $aany (ref $anys))
    (local.set $a8 (array.new $i8s (i32.const 1) (i32.const 1024)))
    (local.set $a16 (array.new $i16s (i32.const -2) (i32.const 1024)))
    (local.set $a32 (array.new $i32s (i32.const 3) (i32.const 1024)))
    (local.set $a64 (array.new $i64s (i64.const 4) (i32.const 1024)))
    (local.set $aany (array.new $anys (ref.i31 (i32.const 5)) (i32.const 1024)))
    (local.set $y (i32.const 1 (;$REPEAT;)))
    (loop $l
      (drop (call $get_i8_u (local.get $a8) (i32.const 10300 (;$INNER_ITERATIONS;))))
      (drop (call $get_i16_s (local.get $a16) (i32.const 10300 (;$INNER_ITERATIONS;))))
      (drop (call $get_i32 (local.get $a32) (i32.const 10300 (;$INNER_ITERATIONS;))))
      (drop (call $get_i64 (local.get $a64) (i32.const 10300 (;$INNER_ITERATIONS;))))
      (call $get_anyref (local.get $aany) (i32.const 10300 (;$INNER_ITERATIONS;)))
      (local.tee $y (i32.sub (local.get $y) (i32.const 1)))
      (br_if $l)
    )
  )
  (func $get_i8_u (param $a (ref $i8s)) (param $n i32) (result i32)
    (local $acc i32)
    (loop $l
      (local.set $acc (i32.add (local.get $acc) (array.get_u $i8s (local.get $a) (i32.and (local.get $n) (i32.const 1023)))))
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
    (local.get $acc)
  )
  (func $get_i16_s (param $a (ref $i16s)) (param $n i32) (result i32)
    (local $acc i32)
    (loop $l
      (local.set $acc (i32.add (local.get $acc) (array.get_s $i16s (local.get $a) (i32.and (local.get $n) (i32.const 1023)))))
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
    (local.get $acc)
  )
  (func $get_i32 (param $a (ref $i32s)) (param $n i32) (result i32)
    (local $acc i32)
    (loop $l
      (local.set $acc (i32.add (local.get $acc) (array.get $i32s (local.get $a) (i32.and (local.get $n) (i32.const 1023)))))
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
    (local.get $acc)
  )
  (func $get_i64 (param $a (ref $i64s)) (param $n i32) (result i64)
    (local $acc i64)
    (loop $l
      (local.set $acc (i64.add (local.get $acc) (array.get $i64s (local.get $a) (i32.and (local.get $n) (i32.const 1023)))))
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
    (local.get $acc)
  )
  ;; anyref elements holding i31s.
  (func $get_anyref (param $a (ref $anys)) (param $n i32)
    (loop $l
      (drop (array.get $anys (local.get $a) (i32.and (local.get $n) (i32.const 1023))))
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
  )
)
