;; INNER_CALIBRATION = 100
;; An anyref array holding a mix of i31s and references to structs and other arrays: scanning
;; dispatches on the kind of each element, and writing alternates between i31s and references.
(module
  (type $leaf (struct (field $v i32)))
  (type $i32s (array (mut i32)))
  (type $anys (array (mut anyref)))
  (func $main (export "main")
    (local $y i32)
    (local $a (ref $anys))
    (local.set $a (call $init (i32.const 1024)))
    (local.set $y (i32.const 1 (;$REPEAT;)))
    (loop $l
      (drop (call $sum (local.get $a) (i32.const 10000 (;$INNER_ITERATIONS;))))
      (drop (call $count_i31 (local.get $a) (i32.const 10000 (;$INNER_ITERATIONS;))))
      (call $set_mixed (local.get $a) (i32.const 10000 (;$INNER_ITERATIONS;)))
      (local.tee $y (i32.sub (local.get $y) (i32.const 1)))
      (br_if $l)
    )
  )
  ;; Fills a new array: i31s at even indices, $leaf structs and $i32s arrays alternating at odd ones.
  (func $init (param $n i32) (result (ref $anys))
    (local $a (ref $anys))
    (local $i i32)
    (local.set $a (array.new_default $anys (local.get $n)))
    (loop $l
      (array.set $anys (local.get $a) (local.get $i) (ref.i31 (local.get $i)))
      (array.set $anys (local.get $a) (i32.add (local.get $i) (i32.const 1)) (struct.new $leaf (local.get $i)))
      (array.set $anys (local.get $a) (i32.add (local.get $i) (i32.const 2)) (ref.i31 (local.get $i)))
      (array.set $anys (local.get $a) (i32.add (local.get $i) (i32.const 3)) (array.new $i32s (local.get $i) (i32.const 1)))
      (local.set $i (i32.add (local.get $i) (i32.const 4)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n)))
    )
    (local.get $a)
  )
  ;; Sums the values of all elements, cycling through the array.
  (func $sum (param $a (ref $anys)) (param $n i32) (result i32)
    (local $acc i32)
    (loop $l
      (local.set $acc (i32.add (local.get $acc)
        (call $value (array.get $anys (local.get $a) (i32.and (local.get $n) (i32.const 1023))))))
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
    (local.get $acc)
  )
  ;; Counts the elements that are i31s, cycling through the array.
  (func $count_i31 (param $a (ref $anys)) (param $n i32) (result i32)
    (local $acc i32)
    (loop $l
      (local.set $acc (i32.add (local.get $acc)
        (ref.test (ref i31) (array.get $anys (local.get $a) (i32.and (local.get $n) (i32.const 1023))))))
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
    (local.get $acc)
  )
  ;; Overwrites elements, alternating an i31 and a reference, cycling through the array.
  (func $set_mixed (param $a (ref $anys)) (param $n i32)
    (local $leaf (ref $leaf))
    (local.set $leaf (struct.new $leaf (i32.const 7)))
    (loop $l
      (array.set $anys (local.get $a) (i32.and (local.get $n) (i32.const 1023)) (ref.i31 (local.get $n)))
      (array.set $anys (local.get $a) (i32.and (i32.add (local.get $n) (i32.const 1)) (i32.const 1023)) (local.get $leaf))
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
  )
  ;; The value of an i31, the field of a $leaf, or the first element of an $i32s.
  (func $value (param $r anyref) (result i32)
    (block $i32s (result (ref $i32s))
      (block $leaf (result (ref $leaf))
        (block $i31 (result (ref i31))
          (br_on_cast $i31 anyref (ref i31) (local.get $r))
          (br_on_cast $leaf anyref (ref $leaf))
          (br_on_cast $i32s anyref (ref $i32s))
          (drop)
          (return (i32.const 0))
        )
        (return (i31.get_s))
      )
      (return (struct.get $leaf $v))
    )
    (array.get $i32s (i32.const 0))
  )
)
