;; INNER_CALIBRATION = 143
;; array.fill: filling 256-element arrays of different element kinds.
(module
  (type $leaf (struct (field i32)))
  (type $i8s (array (mut i8)))
  (type $i32s (array (mut i32)))
  (type $refs (array (mut (ref null $leaf))))
  (type $anys (array (mut anyref)))
  (func $main (export "main")
    (local $y i32)
    (local $a8 (ref $i8s))
    (local $a32 (ref $i32s))
    (local $aref (ref $refs))
    (local $aany (ref $anys))
    (local.set $a8 (array.new_default $i8s (i32.const 256)))
    (local.set $a32 (array.new_default $i32s (i32.const 256)))
    (local.set $aref (array.new_default $refs (i32.const 256)))
    (local.set $aany (array.new_default $anys (i32.const 256)))
    (local.set $y (i32.const 1 (;$REPEAT;)))
    (loop $l
      (call $fill_i8 (local.get $a8) (i32.const 14300 (;$INNER_ITERATIONS;)))
      (call $fill_i32 (local.get $a32) (i32.const 14300 (;$INNER_ITERATIONS;)))
      (call $fill_ref (local.get $aref) (i32.const 14300 (;$INNER_ITERATIONS;)))
      (call $fill_anyref_i31 (local.get $aany) (i32.const 14300 (;$INNER_ITERATIONS;)))
      (local.tee $y (i32.sub (local.get $y) (i32.const 1)))
      (br_if $l)
    )
  )
  (func $fill_i8 (param $a (ref $i8s)) (param $n i32)
    (loop $l
      (array.fill $i8s (local.get $a) (i32.const 0) (local.get $n) (i32.const 256))
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
  )
  (func $fill_i32 (param $a (ref $i32s)) (param $n i32)
    (loop $l
      (array.fill $i32s (local.get $a) (i32.const 0) (local.get $n) (i32.const 256))
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
  )
  (func $fill_ref (param $a (ref $refs)) (param $n i32)
    (local $leaf (ref $leaf))
    (local.set $leaf (struct.new $leaf (i32.const 1)))
    (loop $l
      (array.fill $refs (local.get $a) (i32.const 0) (local.get $leaf) (i32.const 256))
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
  )
  (func $fill_anyref_i31 (param $a (ref $anys)) (param $n i32)
    (loop $l
      (array.fill $anys (local.get $a) (i32.const 0) (ref.i31 (local.get $n)) (i32.const 256))
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
  )
)
