;;! gc = true

;; array.fill on arrays of anyref (which may hold i31s or references), through a supertype,
;; and on packed and unpacked primitive arrays.
(module
  (type $leaf (struct (field i32)))
  (type $anys (array (mut anyref)))
  (type $anysup (sub (array (mut anyref))))
  (type $anysub (sub $anysup (array (mut anyref))))
  (type $i8s (array (mut i8)))
  (type $i16s (array (mut i16)))
  (type $i64s (array (mut i64)))
  (type $f32s (array (mut f32)))

  ;; Encodes an anyref as an i32: null -> -1, i31 -> its value, $leaf -> 1000 + its field.
  (func $val (param anyref) (result i32)
    (if (result i32) (ref.is_null (local.get 0))
      (then (i32.const -1))
      (else
        (if (result i32) (ref.test (ref i31) (local.get 0))
          (then (i31.get_s (ref.cast (ref i31) (local.get 0))))
          (else (i32.add (i32.const 1000) (struct.get $leaf 0 (ref.cast (ref $leaf) (local.get 0)))))))))
  (func $anys4 (param $a (ref $anys)) (result i32 i32 i32 i32)
    (call $val (array.get $anys (local.get $a) (i32.const 0)))
    (call $val (array.get $anys (local.get $a) (i32.const 1)))
    (call $val (array.get $anys (local.get $a) (i32.const 2)))
    (call $val (array.get $anys (local.get $a) (i32.const 3))))

  (func (export "fill_i31") (result i32 i32 i32 i32)
    (local $a (ref $anys))
    (local.set $a (array.new_default $anys (i32.const 4)))
    (array.fill $anys (local.get $a) (i32.const 1) (ref.i31 (i32.const 9)) (i32.const 2))
    (call $anys4 (local.get $a)))
  ;; Successive fills of i31s, references, and null over the same paired storage.
  (func (export "fill_mixed") (result i32 i32 i32 i32)
    (local $a (ref $anys))
    (local.set $a (array.new_default $anys (i32.const 4)))
    (array.fill $anys (local.get $a) (i32.const 0) (ref.i31 (i32.const 9)) (i32.const 4))
    (array.fill $anys (local.get $a) (i32.const 1) (struct.new $leaf (i32.const 4)) (i32.const 2))
    (array.fill $anys (local.get $a) (i32.const 2) (ref.null any) (i32.const 1))
    (call $anys4 (local.get $a)))
  ;; Fill a subtype array through its supertype.
  (func (export "fill_via_sup") (result i32 i32 i32)
    (local $a (ref $anysub))
    (local.set $a (array.new_default $anysub (i32.const 3)))
    (array.fill $anysup (local.get $a) (i32.const 0) (struct.new $leaf (i32.const 3)) (i32.const 3))
    (call $val (array.get $anysub (local.get $a) (i32.const 0)))
    (call $val (array.get $anysub (local.get $a) (i32.const 1)))
    (call $val (array.get $anysub (local.get $a) (i32.const 2))))
  (func (export "fill_i8") (result i32 i32 i32)
    (local $a (ref $i8s))
    (local.set $a (array.new_default $i8s (i32.const 3)))
    (array.fill $i8s (local.get $a) (i32.const 1) (i32.const 0x1ff) (i32.const 2))
    (array.get_u $i8s (local.get $a) (i32.const 0))
    (array.get_u $i8s (local.get $a) (i32.const 1))
    (array.get_s $i8s (local.get $a) (i32.const 2)))
  (func (export "fill_i16") (result i32 i32 i32)
    (local $a (ref $i16s))
    (local.set $a (array.new_default $i16s (i32.const 3)))
    (array.fill $i16s (local.get $a) (i32.const 0) (i32.const 0x18000) (i32.const 2))
    (array.get_u $i16s (local.get $a) (i32.const 0))
    (array.get_s $i16s (local.get $a) (i32.const 1))
    (array.get_u $i16s (local.get $a) (i32.const 2)))
  (func (export "fill_i64") (result i64 i64)
    (local $a (ref $i64s))
    (local.set $a (array.new_default $i64s (i32.const 2)))
    (array.fill $i64s (local.get $a) (i32.const 1) (i64.const 0x0102030405060708) (i32.const 1))
    (array.get $i64s (local.get $a) (i32.const 0))
    (array.get $i64s (local.get $a) (i32.const 1)))
  (func (export "fill_f32") (result f32 f32)
    (local $a (ref $f32s))
    (local.set $a (array.new_default $f32s (i32.const 2)))
    (array.fill $f32s (local.get $a) (i32.const 0) (f32.const 1.5) (i32.const 2))
    (array.get $f32s (local.get $a) (i32.const 0))
    (array.get $f32s (local.get $a) (i32.const 1)))
  (func (export "fill_oob")
    (array.fill $anys (array.new_default $anys (i32.const 4)) (i32.const 2) (ref.i31 (i32.const 1)) (i32.const 3)))
  (func (export "fill_i8_oob")
    (array.fill $i8s (array.new_default $i8s (i32.const 4)) (i32.const 5) (i32.const 1) (i32.const 0)))
  (func (export "fill_zero_at_end") (result i32)
    (array.fill $anys (array.new_default $anys (i32.const 4)) (i32.const 4) (ref.i31 (i32.const 1)) (i32.const 0))
    (i32.const 1))
)
(assert_return (invoke "fill_i31") (i32.const -1) (i32.const 9) (i32.const 9) (i32.const -1))
(assert_return (invoke "fill_mixed") (i32.const 9) (i32.const 1004) (i32.const -1) (i32.const 9))
(assert_return (invoke "fill_via_sup") (i32.const 1003) (i32.const 1003) (i32.const 1003))
(assert_return (invoke "fill_i8") (i32.const 0) (i32.const 255) (i32.const -1))
(assert_return (invoke "fill_i16") (i32.const 32768) (i32.const -32768) (i32.const 0))
(assert_return (invoke "fill_i64") (i64.const 0) (i64.const 0x0102030405060708))
(assert_return (invoke "fill_f32") (f32.const 1.5) (f32.const 1.5))
(assert_trap (invoke "fill_oob") "out of bounds array access")
(assert_trap (invoke "fill_i8_oob") "out of bounds array access")
(assert_return (invoke "fill_zero_at_end") (i32.const 1))
