;;! gc = true

;; array.copy between arrays whose element types are related by subtyping but which may have
;; different representations: struct references, anyref/eqref (which may hold i31s), and i31ref.
(module
  (type $leaf (struct (field i32)))
  (type $refs (array (mut (ref null $leaf))))
  (type $anys (array (mut anyref)))
  (type $eqs (array (mut eqref)))
  (type $i31s (array (mut i31ref)))
  (type $structs (array (mut structref)))
  (type $anysup (sub (array anyref)))
  (type $leafsub (sub $anysup (array (ref $leaf))))

  (func $leaf (param i32) (result (ref $leaf)) (struct.new $leaf (local.get 0)))
  ;; Encodes an anyref as an i32: null -> -1, i31 -> its value, $leaf -> 1000 + its field.
  (func $val (param anyref) (result i32)
    (if (result i32) (ref.is_null (local.get 0))
      (then (i32.const -1))
      (else
        (if (result i32) (ref.test (ref i31) (local.get 0))
          (then (i31.get_s (ref.cast (ref i31) (local.get 0))))
          (else (i32.add (i32.const 1000) (struct.get $leaf 0 (ref.cast (ref $leaf) (local.get 0)))))))))
  (func $anys4 (param $a (ref $anys)) (result i32 i32 i32 i32)
    (call $val (array.get $anys (local.get $a) (i32.const 0)))
    (call $val (array.get $anys (local.get $a) (i32.const 1)))
    (call $val (array.get $anys (local.get $a) (i32.const 2)))
    (call $val (array.get $anys (local.get $a) (i32.const 3))))
  (func $anys5 (param $a (ref $anys)) (result i32 i32 i32 i32 i32)
    (call $anys4 (local.get $a))
    (call $val (array.get $anys (local.get $a) (i32.const 4))))
  (func $structs3 (param $a (ref $structs)) (result i32 i32 i32)
    (call $val (array.get $structs (local.get $a) (i32.const 0)))
    (call $val (array.get $structs (local.get $a) (i32.const 1)))
    (call $val (array.get $structs (local.get $a) (i32.const 2))))
  (func $refs5 (param $a (ref $refs)) (result i32 i32 i32 i32 i32)
    (call $val (array.get $refs (local.get $a) (i32.const 0)))
    (call $val (array.get $refs (local.get $a) (i32.const 1)))
    (call $val (array.get $refs (local.get $a) (i32.const 2)))
    (call $val (array.get $refs (local.get $a) (i32.const 3)))
    (call $val (array.get $refs (local.get $a) (i32.const 4))))

  (func $new_refs (result (ref $refs))
    (array.new_fixed $refs 3 (call $leaf (i32.const 1)) (ref.null $leaf) (call $leaf (i32.const 3))))
  (func $new_refs5 (result (ref $refs))
    (array.new_fixed $refs 5 (call $leaf (i32.const 1)) (ref.null $leaf) (call $leaf (i32.const 3)) (ref.null $leaf) (call $leaf (i32.const 5))))
  (func $new_anys5 (result (ref $anys))
    (array.new_fixed $anys 5 (ref.i31 (i32.const 1)) (ref.i31 (i32.const 2)) (call $leaf (i32.const 3)) (ref.null any) (ref.i31 (i32.const 5))))
  (func $new_leafsub (result (ref $leafsub))
    (array.new_fixed $leafsub 2 (call $leaf (i32.const 5)) (call $leaf (i32.const 6))))

  ;; Plain references into paired anyref storage.
  (func (export "refs_to_anys") (result i32 i32 i32 i32)
    (local $dst (ref $anys))
    (local.set $dst (array.new $anys (ref.i31 (i32.const 7)) (i32.const 4)))
    (array.copy $anys $refs (local.get $dst) (i32.const 1) (call $new_refs) (i32.const 0) (i32.const 3))
    (call $anys4 (local.get $dst)))
  ;; Plain references into plain structref storage.
  (func (export "refs_to_structs") (result i32 i32 i32)
    (local $dst (ref $structs))
    (local.set $dst (array.new $structs (ref.null struct) (i32.const 3)))
    (array.copy $structs $refs (local.get $dst) (i32.const 0) (call $new_refs) (i32.const 1) (i32.const 2))
    (call $structs3 (local.get $dst)))
  ;; Paired i31ref storage into paired eqref storage.
  (func (export "i31s_to_eqs") (result i32 i32 i32 i32)
    (local $dst (ref $eqs))
    (local.set $dst (array.new $eqs (ref.null eq) (i32.const 4)))
    (array.copy $eqs $i31s (local.get $dst) (i32.const 1)
      (array.new_fixed $i31s 3 (ref.i31 (i32.const 1)) (ref.i31 (i32.const 2)) (ref.i31 (i32.const 3))) (i32.const 0) (i32.const 3))
    (call $val (array.get $eqs (local.get $dst) (i32.const 0)))
    (call $val (array.get $eqs (local.get $dst) (i32.const 1)))
    (call $val (array.get $eqs (local.get $dst) (i32.const 2)))
    (call $val (array.get $eqs (local.get $dst) (i32.const 3))))
  ;; A subtype array of struct references, which shares the representation of its anyref
  ;; supertype, into paired anyref storage.
  (func (export "leafsub_to_anys") (result i32 i32 i32 i32)
    (local $dst (ref $anys))
    (local.set $dst (array.new $anys (ref.i31 (i32.const 7)) (i32.const 4)))
    (array.copy $anys $leafsub (local.get $dst) (i32.const 1) (call $new_leafsub) (i32.const 0) (i32.const 2))
    (call $anys4 (local.get $dst)))
  ;; The same subtype array into plain structref storage.
  (func (export "leafsub_to_structs") (result i32 i32 i32)
    (local $dst (ref $structs))
    (local.set $dst (array.new $structs (ref.null struct) (i32.const 3)))
    (array.copy $structs $leafsub (local.get $dst) (i32.const 1) (call $new_leafsub) (i32.const 0) (i32.const 2))
    (call $structs3 (local.get $dst)))
  ;; Overlapping copies within one paired array, in both directions.
  (func (export "anys_overlap_up") (result i32 i32 i32 i32 i32)
    (local $a (ref $anys))
    (local.set $a (call $new_anys5))
    (array.copy $anys $anys (local.get $a) (i32.const 2) (local.get $a) (i32.const 1) (i32.const 3))
    (call $anys5 (local.get $a)))
  (func (export "anys_overlap_down") (result i32 i32 i32 i32 i32)
    (local $a (ref $anys))
    (local.set $a (call $new_anys5))
    (array.copy $anys $anys (local.get $a) (i32.const 0) (local.get $a) (i32.const 2) (i32.const 3))
    (call $anys5 (local.get $a)))
  ;; Overlapping copies within one plain array, in both directions.
  (func (export "refs_overlap_up") (result i32 i32 i32 i32 i32)
    (local $a (ref $refs))
    (local.set $a (call $new_refs5))
    (array.copy $refs $refs (local.get $a) (i32.const 2) (local.get $a) (i32.const 1) (i32.const 3))
    (call $refs5 (local.get $a)))
  (func (export "refs_overlap_down") (result i32 i32 i32 i32 i32)
    (local $a (ref $refs))
    (local.set $a (call $new_refs5))
    (array.copy $refs $refs (local.get $a) (i32.const 0) (local.get $a) (i32.const 2) (i32.const 3))
    (call $refs5 (local.get $a)))
  ;; Out-of-bounds copies trap, for both the same and different representations.
  (func (export "refs_to_anys_oob")
    (array.copy $anys $refs (array.new_default $anys (i32.const 4)) (i32.const 1) (call $new_refs) (i32.const 0) (i32.const 4)))
  (func (export "refs_to_anys_dst_oob")
    (array.copy $anys $refs (array.new_default $anys (i32.const 4)) (i32.const 2) (call $new_refs) (i32.const 0) (i32.const 3)))
  (func (export "anys_oob")
    (local $a (ref $anys))
    (local.set $a (call $new_anys5))
    (array.copy $anys $anys (local.get $a) (i32.const 3) (local.get $a) (i32.const 0) (i32.const 3)))
  ;; Zero-length copies at the end of both arrays are fine.
  (func (export "zero_at_end") (result i32)
    (array.copy $anys $refs (array.new_default $anys (i32.const 4)) (i32.const 4) (call $new_refs) (i32.const 3) (i32.const 0))
    (i32.const 1))
)
(assert_return (invoke "refs_to_anys") (i32.const 7) (i32.const 1001) (i32.const -1) (i32.const 1003))
(assert_return (invoke "refs_to_structs") (i32.const -1) (i32.const 1003) (i32.const -1))
(assert_return (invoke "i31s_to_eqs") (i32.const -1) (i32.const 1) (i32.const 2) (i32.const 3))
(assert_return (invoke "leafsub_to_anys") (i32.const 7) (i32.const 1005) (i32.const 1006) (i32.const 7))
(assert_return (invoke "leafsub_to_structs") (i32.const -1) (i32.const 1005) (i32.const 1006))
(assert_return (invoke "anys_overlap_up") (i32.const 1) (i32.const 2) (i32.const 2) (i32.const 1003) (i32.const -1))
(assert_return (invoke "anys_overlap_down") (i32.const 1003) (i32.const -1) (i32.const 5) (i32.const -1) (i32.const 5))
(assert_return (invoke "refs_overlap_up") (i32.const 1001) (i32.const -1) (i32.const -1) (i32.const 1003) (i32.const -1))
(assert_return (invoke "refs_overlap_down") (i32.const 1003) (i32.const -1) (i32.const 1005) (i32.const -1) (i32.const 1005))
(assert_trap (invoke "refs_to_anys_oob") "out of bounds array access")
(assert_trap (invoke "refs_to_anys_dst_oob") "out of bounds array access")
(assert_trap (invoke "anys_oob") "out of bounds array access")
(assert_return (invoke "zero_at_end") (i32.const 1))
