;;! gc = true

;; array.new_elem and array.init_elem from element segments whose types are subtypes of the
;; array element type, into arrays with different representations.
(module
  (type $leaf (struct (field i32)))
  (type $anys (array (mut anyref)))
  (type $structs (array (mut structref)))
  (type $anysup (sub (array anyref)))
  (type $leafsub (sub $anysup (array (ref $leaf))))
  (elem $eleaves (ref $leaf) (item (struct.new $leaf (i32.const 1))) (item (struct.new $leaf (i32.const 2))))
  (elem $eanys anyref (item (ref.i31 (i32.const 3))) (item (struct.new $leaf (i32.const 4))) (item (ref.null any)))

  ;; Encodes an anyref as an i32: null -> -1, i31 -> its value, $leaf -> 1000 + its field.
  (func $val (param anyref) (result i32)
    (if (result i32) (ref.is_null (local.get 0))
      (then (i32.const -1))
      (else
        (if (result i32) (ref.test (ref i31) (local.get 0))
          (then (i31.get_s (ref.cast (ref i31) (local.get 0))))
          (else (i32.add (i32.const 1000) (struct.get $leaf 0 (ref.cast (ref $leaf) (local.get 0)))))))))
  (func $anys4 (param $a (ref $anys)) (result i32 i32 i32 i32)
    (call $val (array.get $anys (local.get $a) (i32.const 0)))
    (call $val (array.get $anys (local.get $a) (i32.const 1)))
    (call $val (array.get $anys (local.get $a) (i32.const 2)))
    (call $val (array.get $anys (local.get $a) (i32.const 3))))

  ;; Struct references from a segment into paired anyref storage.
  (func (export "new_elem_leaves_to_anys") (result i32 i32)
    (local $a (ref $anys))
    (local.set $a (array.new_elem $anys $eleaves (i32.const 0) (i32.const 2)))
    (call $val (array.get $anys (local.get $a) (i32.const 0)))
    (call $val (array.get $anys (local.get $a) (i32.const 1))))
  ;; Struct references from a segment into plain structref storage.
  (func (export "new_elem_leaves_to_structs") (result i32 i32)
    (local $a (ref $structs))
    (local.set $a (array.new_elem $structs $eleaves (i32.const 0) (i32.const 2)))
    (call $val (array.get $structs (local.get $a) (i32.const 0)))
    (call $val (array.get $structs (local.get $a) (i32.const 1))))
  ;; Struct references from a segment into a subtype array that shares its anyref supertype's
  ;; representation, read back through the supertype.
  (func (export "new_elem_leaves_to_leafsub") (result i32 i32)
    (local $a (ref $anysup))
    (local.set $a (array.new_elem $leafsub $eleaves (i32.const 0) (i32.const 2)))
    (call $val (array.get $anysup (local.get $a) (i32.const 0)))
    (call $val (array.get $anysup (local.get $a) (i32.const 1))))
  ;; A mix of i31s, references, and null from a segment.
  (func (export "new_elem_anys") (result i32 i32 i32)
    (local $a (ref $anys))
    (local.set $a (array.new_elem $anys $eanys (i32.const 0) (i32.const 3)))
    (call $val (array.get $anys (local.get $a) (i32.const 0)))
    (call $val (array.get $anys (local.get $a) (i32.const 1)))
    (call $val (array.get $anys (local.get $a) (i32.const 2))))
  (func (export "init_elem_leaves_to_anys") (result i32 i32 i32 i32)
    (local $a (ref $anys))
    (local.set $a (array.new $anys (ref.i31 (i32.const 9)) (i32.const 4)))
    (array.init_elem $anys $eleaves (local.get $a) (i32.const 1) (i32.const 0) (i32.const 2))
    (call $anys4 (local.get $a)))
  (func (export "init_elem_anys_to_anys") (result i32 i32 i32 i32)
    (local $a (ref $anys))
    (local.set $a (array.new $anys (ref.i31 (i32.const 9)) (i32.const 4)))
    (array.init_elem $anys $eanys (local.get $a) (i32.const 1) (i32.const 1) (i32.const 2))
    (call $anys4 (local.get $a)))
  (func (export "new_elem_oob")
    (drop (array.new_elem $anys $eanys (i32.const 2) (i32.const 2))))
  (func (export "init_elem_dst_oob")
    (array.init_elem $anys $eleaves (array.new_default $anys (i32.const 4)) (i32.const 3) (i32.const 0) (i32.const 2)))
  (func (export "init_elem_src_oob")
    (array.init_elem $anys $eleaves (array.new_default $anys (i32.const 4)) (i32.const 0) (i32.const 1) (i32.const 2)))
)
(assert_return (invoke "new_elem_leaves_to_anys") (i32.const 1001) (i32.const 1002))
(assert_return (invoke "new_elem_leaves_to_structs") (i32.const 1001) (i32.const 1002))
(assert_return (invoke "new_elem_leaves_to_leafsub") (i32.const 1001) (i32.const 1002))
(assert_return (invoke "new_elem_anys") (i32.const 3) (i32.const 1004) (i32.const -1))
(assert_return (invoke "init_elem_leaves_to_anys") (i32.const 9) (i32.const 1001) (i32.const 1002) (i32.const 9))
(assert_return (invoke "init_elem_anys_to_anys") (i32.const 9) (i32.const 1004) (i32.const -1) (i32.const 9))
(assert_trap (invoke "new_elem_oob") "out of bounds table access")
(assert_trap (invoke "init_elem_dst_oob") "out of bounds array access")
(assert_trap (invoke "init_elem_src_oob") "out of bounds table access")
