;; Struct layout: subtypes add fields of different kinds to their supertypes' layouts.
(module
  (type $A (sub (struct
    (field $x (mut i32))
    (field $r (mut (ref null $A))))))
  (type $B (sub $A (struct
    (field $x (mut i32))
    (field $r (mut (ref null $A)))
    (field $y (mut i8))
    (field $q (mut anyref)))))
  (type $C (sub final $B (struct
    (field $x (mut i32))
    (field $r (mut (ref null $A)))
    (field $y (mut i8))
    (field $q (mut anyref))
    (field $z (mut i64))
    (field $s (mut (ref null $C)))
    (field $w (mut i16)))))

  (global $a (mut (ref null $A)) (ref.null $A))
  (global $b (mut (ref null $B)) (ref.null $B))
  (global $c (mut (ref null $C)) (ref.null $C))

  (func (export "init")
    (global.set $c (struct.new $C
      (i32.const 3) (ref.null $A) (i32.const 0xc3) (ref.i31 (i32.const 33))
      (i64.const 0x3333333333333333) (ref.null $C) (i32.const 0x3c3c)))
    (global.set $b (struct.new $B (i32.const 2) (global.get $c) (i32.const 0xb2) (ref.i31 (i32.const 22))))
    (global.set $a (struct.new $A (i32.const 1) (global.get $b)))
    (struct.set $C $r (global.get $c) (global.get $a))
    (struct.set $C $s (global.get $c) (global.get $c)))

  ;; Read the fields of $c through each type.
  (func (export "c_x_as_A") (result i32) (struct.get $A $x (global.get $c)))
  (func (export "c_x_as_B") (result i32) (struct.get $B $x (global.get $c)))
  (func (export "c_x_as_C") (result i32) (struct.get $C $x (global.get $c)))
  (func (export "c_r_is_a") (result i32) (ref.eq (struct.get $A $r (global.get $c)) (global.get $a)))
  (func (export "c_y_as_B") (result i32) (struct.get_u $B $y (global.get $c)))
  (func (export "c_y_as_C") (result i32) (struct.get_s $C $y (global.get $c)))
  (func (export "c_q_as_B") (result i32) (i31.get_u (ref.cast (ref i31) (struct.get $B $q (global.get $c)))))
  (func (export "c_q_as_C") (result i32) (i31.get_u (ref.cast (ref i31) (struct.get $C $q (global.get $c)))))
  (func (export "c_z") (result i64) (struct.get $C $z (global.get $c)))
  (func (export "c_s_is_c") (result i32) (ref.eq (struct.get $C $s (global.get $c)) (global.get $c)))
  (func (export "c_w") (result i32) (struct.get_u $C $w (global.get $c)))

  ;; The other instances.
  (func (export "a_x") (result i32) (struct.get $A $x (global.get $a)))
  (func (export "a_r_is_b") (result i32) (ref.eq (struct.get $A $r (global.get $a)) (global.get $b)))
  (func (export "b_x") (result i32) (struct.get $B $x (global.get $b)))
  (func (export "b_r_is_c") (result i32) (ref.eq (struct.get $A $r (global.get $b)) (global.get $c)))
  (func (export "b_y") (result i32) (struct.get_s $B $y (global.get $b)))
  (func (export "b_q") (result i32) (i31.get_u (ref.cast (ref i31) (struct.get $B $q (global.get $b)))))
  (func (export "walk3_is_a") (result i32)
    (ref.eq (struct.get $A $r (struct.get $A $r (struct.get $A $r (global.get $a)))) (global.get $a)))
  (func (export "walk_sum") (result i32)
    (i32.add (struct.get $A $x (global.get $a))
      (i32.add (struct.get $A $x (struct.get $A $r (global.get $a)))
        (struct.get $A $x (struct.get $A $r (struct.get $A $r (global.get $a)))))))

  ;; Write through a supertype's view, read through the subtype's view.
  (func (export "set_c_x_as_A") (param i32) (struct.set $A $x (global.get $c) (local.get 0)))
  (func (export "set_c_y_as_B") (param i32) (struct.set $B $y (global.get $c) (local.get 0)))
  (func (export "set_c_q_as_B") (struct.set $B $q (global.get $c) (global.get $b)))
  (func (export "c_q_is_b") (result i32) (ref.eq (ref.cast (ref null eq) (struct.get $C $q (global.get $c))) (global.get $b)))

  (func (export "a_is_B") (result i32) (ref.test (ref $B) (global.get $a)))
  (func (export "b_is_B") (result i32) (ref.test (ref $B) (global.get $b)))
  (func (export "b_is_C") (result i32) (ref.test (ref $C) (global.get $b)))
  (func (export "c_is_A") (result i32) (ref.test (ref $A) (global.get $c)))
  (func (export "c_is_C") (result i32) (ref.test (ref $C) (global.get $c)))
)

(invoke "init")
(assert_return (invoke "c_x_as_A") (i32.const 3))
(assert_return (invoke "c_x_as_B") (i32.const 3))
(assert_return (invoke "c_x_as_C") (i32.const 3))
(assert_return (invoke "c_r_is_a") (i32.const 1))
(assert_return (invoke "c_y_as_B") (i32.const 0xc3))
(assert_return (invoke "c_y_as_C") (i32.const -61))
(assert_return (invoke "c_q_as_B") (i32.const 33))
(assert_return (invoke "c_q_as_C") (i32.const 33))
(assert_return (invoke "c_z") (i64.const 0x3333333333333333))
(assert_return (invoke "c_s_is_c") (i32.const 1))
(assert_return (invoke "c_w") (i32.const 0x3c3c))

(assert_return (invoke "a_x") (i32.const 1))
(assert_return (invoke "a_r_is_b") (i32.const 1))
(assert_return (invoke "b_x") (i32.const 2))
(assert_return (invoke "b_r_is_c") (i32.const 1))
(assert_return (invoke "b_y") (i32.const -78))
(assert_return (invoke "b_q") (i32.const 22))
(assert_return (invoke "walk3_is_a") (i32.const 1))
(assert_return (invoke "walk_sum") (i32.const 6))

(invoke "set_c_x_as_A" (i32.const 0x77777777))
(assert_return (invoke "c_x_as_C") (i32.const 0x77777777))
(assert_return (invoke "c_y_as_B") (i32.const 0xc3))
(assert_return (invoke "c_w") (i32.const 0x3c3c))
(assert_return (invoke "walk_sum") (i32.const 0x7777777a))
(invoke "set_c_y_as_B" (i32.const 0x1ff))
(assert_return (invoke "c_y_as_C") (i32.const -1))
(assert_return (invoke "c_x_as_A") (i32.const 0x77777777))
(assert_return (invoke "c_w") (i32.const 0x3c3c))
(assert_return (invoke "c_z") (i64.const 0x3333333333333333))
(invoke "set_c_q_as_B")
(assert_return (invoke "c_q_is_b") (i32.const 1))
(assert_return (invoke "c_s_is_c") (i32.const 1))
(assert_return (invoke "c_r_is_a") (i32.const 1))

(assert_return (invoke "a_is_B") (i32.const 0))
(assert_return (invoke "b_is_B") (i32.const 1))
(assert_return (invoke "b_is_C") (i32.const 0))
(assert_return (invoke "c_is_A") (i32.const 1))
(assert_return (invoke "c_is_C") (i32.const 1))
