;; Struct layout: primitive fields of all sizes in mixed declaration order.
(module
  (type $s (struct
    (field $a (mut i8))
    (field $b (mut i64))
    (field $c (mut i16))
    (field $d (mut f32))
    (field $e (mut i32))
    (field $f (mut f64))
    (field $g (mut i8))
    (field $h (mut i16))))

  (global $g (ref $s) (struct.new $s
    (i32.const 0x81) (i64.const 0x1122334455667788) (i32.const 0x8001) (f32.const 1.5)
    (i32.const 0xdeadbeef) (f64.const 2.25) (i32.const 0x7f) (i32.const 0x7fff)))

  (func (export "get_a_s") (result i32) (struct.get_s $s $a (global.get $g)))
  (func (export "get_a_u") (result i32) (struct.get_u $s $a (global.get $g)))
  (func (export "get_b") (result i64) (struct.get $s $b (global.get $g)))
  (func (export "get_c_s") (result i32) (struct.get_s $s $c (global.get $g)))
  (func (export "get_c_u") (result i32) (struct.get_u $s $c (global.get $g)))
  (func (export "get_d") (result f32) (struct.get $s $d (global.get $g)))
  (func (export "get_e") (result i32) (struct.get $s $e (global.get $g)))
  (func (export "get_f") (result f64) (struct.get $s $f (global.get $g)))
  (func (export "get_g_s") (result i32) (struct.get_s $s $g (global.get $g)))
  (func (export "get_h_u") (result i32) (struct.get_u $s $h (global.get $g)))

  (func (export "set_a") (param i32) (struct.set $s $a (global.get $g) (local.get 0)))
  (func (export "set_b") (param i64) (struct.set $s $b (global.get $g) (local.get 0)))
  (func (export "set_c") (param i32) (struct.set $s $c (global.get $g) (local.get 0)))
  (func (export "set_d") (param f32) (struct.set $s $d (global.get $g) (local.get 0)))
  (func (export "set_e") (param i32) (struct.set $s $e (global.get $g) (local.get 0)))
  (func (export "set_f") (param f64) (struct.set $s $f (global.get $g) (local.get 0)))
  (func (export "set_g") (param i32) (struct.set $s $g (global.get $g) (local.get 0)))
  (func (export "set_h") (param i32) (struct.set $s $h (global.get $g) (local.get 0)))
)

(assert_return (invoke "get_a_s") (i32.const -127))
(assert_return (invoke "get_a_u") (i32.const 129))
(assert_return (invoke "get_b") (i64.const 0x1122334455667788))
(assert_return (invoke "get_c_s") (i32.const -32767))
(assert_return (invoke "get_c_u") (i32.const 32769))
(assert_return (invoke "get_d") (f32.const 1.5))
(assert_return (invoke "get_e") (i32.const 0xdeadbeef))
(assert_return (invoke "get_f") (f64.const 2.25))
(assert_return (invoke "get_g_s") (i32.const 127))
(assert_return (invoke "get_h_u") (i32.const 32767))

;; Overwrite each field and check that its neighbors are unaffected.
(invoke "set_a" (i32.const -1))
(assert_return (invoke "get_a_u") (i32.const 255))
(assert_return (invoke "get_c_u") (i32.const 32769))
(assert_return (invoke "get_g_s") (i32.const 127))
(assert_return (invoke "get_h_u") (i32.const 32767))
(assert_return (invoke "get_e") (i32.const 0xdeadbeef))

(invoke "set_c" (i32.const -1))
(assert_return (invoke "get_c_s") (i32.const -1))
(assert_return (invoke "get_a_u") (i32.const 255))
(assert_return (invoke "get_h_u") (i32.const 32767))
(assert_return (invoke "get_g_s") (i32.const 127))

(invoke "set_g" (i32.const 0x80))
(assert_return (invoke "get_g_s") (i32.const -128))
(assert_return (invoke "get_a_u") (i32.const 255))
(assert_return (invoke "get_c_u") (i32.const 65535))
(assert_return (invoke "get_h_u") (i32.const 32767))

(invoke "set_h" (i32.const 0x12345))
(assert_return (invoke "get_h_u") (i32.const 0x2345))
(assert_return (invoke "get_c_u") (i32.const 65535))
(assert_return (invoke "get_g_s") (i32.const -128))
(assert_return (invoke "get_a_u") (i32.const 255))

(invoke "set_e" (i32.const 0))
(assert_return (invoke "get_e") (i32.const 0))
(assert_return (invoke "get_d") (f32.const 1.5))
(assert_return (invoke "get_b") (i64.const 0x1122334455667788))
(assert_return (invoke "get_f") (f64.const 2.25))

(invoke "set_d" (f32.const -0x1p-149))
(assert_return (invoke "get_d") (f32.const -0x1p-149))
(assert_return (invoke "get_e") (i32.const 0))

(invoke "set_b" (i64.const -1))
(invoke "set_f" (f64.const -0x1.fffffffffffffp+1023))
(assert_return (invoke "get_b") (i64.const -1))
(assert_return (invoke "get_f") (f64.const -0x1.fffffffffffffp+1023))
(assert_return (invoke "get_d") (f32.const -0x1p-149))
(assert_return (invoke "get_e") (i32.const 0))
(assert_return (invoke "get_a_u") (i32.const 255))
(assert_return (invoke "get_c_u") (i32.const 65535))
(assert_return (invoke "get_g_s") (i32.const -128))
(assert_return (invoke "get_h_u") (i32.const 0x2345))
