;; Struct layout: references interleaved with primitives, including anyref/eqref fields that hold i31s.
(module
  (type $s (struct
    (field (mut i8))
    (field (mut (ref null $s)))
    (field (mut i32))
    (field (mut anyref))
    (field (mut i64))
    (field (mut (ref null $s)))
    (field (mut eqref))
    (field (mut i16))))

  (global $a (ref $s) (struct.new_default $s))
  (global $b (ref $s) (struct.new_default $s))

  (func (export "init")
    (struct.set $s 0 (global.get $a) (i32.const 0x55))
    (struct.set $s 1 (global.get $a) (global.get $b))
    (struct.set $s 2 (global.get $a) (i32.const 0x12345678))
    (struct.set $s 3 (global.get $a) (ref.i31 (i32.const 77)))
    (struct.set $s 4 (global.get $a) (i64.const 0x0102030405060708))
    (struct.set $s 5 (global.get $a) (global.get $a))
    (struct.set $s 6 (global.get $a) (global.get $b))
    (struct.set $s 7 (global.get $a) (i32.const 0x3333)))

  (func (export "get0") (result i32) (struct.get_u $s 0 (global.get $a)))
  (func (export "get1_is_null") (result i32) (ref.is_null (struct.get $s 1 (global.get $a))))
  (func (export "get1_is_b") (result i32) (ref.eq (struct.get $s 1 (global.get $a)) (global.get $b)))
  (func (export "get2") (result i32) (struct.get $s 2 (global.get $a)))
  (func (export "get3_is_null") (result i32) (ref.is_null (struct.get $s 3 (global.get $a))))
  (func (export "get3_is_i31") (result i32) (ref.test (ref i31) (struct.get $s 3 (global.get $a))))
  (func (export "get3_i31") (result i32) (i31.get_s (ref.cast (ref i31) (struct.get $s 3 (global.get $a)))))
  (func (export "get3_is_b") (result i32) (ref.eq (ref.cast (ref null eq) (struct.get $s 3 (global.get $a))) (global.get $b)))
  (func (export "get4") (result i64) (struct.get $s 4 (global.get $a)))
  (func (export "get5_is_null") (result i32) (ref.is_null (struct.get $s 5 (global.get $a))))
  (func (export "get5_is_a") (result i32) (ref.eq (struct.get $s 5 (global.get $a)) (global.get $a)))
  (func (export "get6_is_null") (result i32) (ref.is_null (struct.get $s 6 (global.get $a))))
  (func (export "get6_is_b") (result i32) (ref.eq (struct.get $s 6 (global.get $a)) (global.get $b)))
  (func (export "get6_i31") (result i32) (i31.get_u (ref.cast (ref i31) (struct.get $s 6 (global.get $a)))))
  (func (export "get7") (result i32) (struct.get_u $s 7 (global.get $a)))

  (func (export "set3_b") (struct.set $s 3 (global.get $a) (global.get $b)))
  (func (export "set3_i31") (param i32) (struct.set $s 3 (global.get $a) (ref.i31 (local.get 0))))
  (func (export "set3_null") (struct.set $s 3 (global.get $a) (ref.null any)))
  (func (export "set6_i31") (param i32) (struct.set $s 6 (global.get $a) (ref.i31 (local.get 0))))
  (func (export "set6_null") (struct.set $s 6 (global.get $a) (ref.null eq)))
)

;; Default values.
(assert_return (invoke "get0") (i32.const 0))
(assert_return (invoke "get1_is_null") (i32.const 1))
(assert_return (invoke "get2") (i32.const 0))
(assert_return (invoke "get3_is_null") (i32.const 1))
(assert_return (invoke "get3_is_i31") (i32.const 0))
(assert_return (invoke "get4") (i64.const 0))
(assert_return (invoke "get5_is_null") (i32.const 1))
(assert_return (invoke "get6_is_null") (i32.const 1))
(assert_return (invoke "get7") (i32.const 0))

(invoke "init")
(assert_return (invoke "get0") (i32.const 0x55))
(assert_return (invoke "get1_is_b") (i32.const 1))
(assert_return (invoke "get2") (i32.const 0x12345678))
(assert_return (invoke "get3_is_null") (i32.const 0))
(assert_return (invoke "get3_is_i31") (i32.const 1))
(assert_return (invoke "get3_i31") (i32.const 77))
(assert_return (invoke "get4") (i64.const 0x0102030405060708))
(assert_return (invoke "get5_is_a") (i32.const 1))
(assert_return (invoke "get6_is_b") (i32.const 1))
(assert_return (invoke "get7") (i32.const 0x3333))

;; Transitions between i31, reference, and null in the same field.
(invoke "set3_b")
(assert_return (invoke "get3_is_i31") (i32.const 0))
(assert_return (invoke "get3_is_b") (i32.const 1))
(invoke "set3_i31" (i32.const -1))
(assert_return (invoke "get3_is_b") (i32.const 0))
(assert_return (invoke "get3_is_i31") (i32.const 1))
(assert_return (invoke "get3_i31") (i32.const -1))
(invoke "set3_i31" (i32.const 0))
(assert_return (invoke "get3_is_i31") (i32.const 1))
(assert_return (invoke "get3_is_null") (i32.const 0))
(assert_return (invoke "get3_i31") (i32.const 0))
(invoke "set3_null")
(assert_return (invoke "get3_is_null") (i32.const 1))
(assert_return (invoke "get3_is_i31") (i32.const 0))
(assert_return (invoke "get3_is_b") (i32.const 0))
(invoke "set3_b")
(assert_return (invoke "get3_is_b") (i32.const 1))

(invoke "set6_i31" (i32.const 0x7fffffff))
(assert_return (invoke "get6_is_b") (i32.const 0))
(assert_return (invoke "get6_i31") (i32.const 0x7fffffff))
(invoke "set6_null")
(assert_return (invoke "get6_is_null") (i32.const 1))
(invoke "set6_i31" (i32.const 1))
(assert_return (invoke "get6_is_null") (i32.const 0))
(assert_return (invoke "get6_i31") (i32.const 1))

;; Neighbors unaffected.
(assert_return (invoke "get0") (i32.const 0x55))
(assert_return (invoke "get1_is_b") (i32.const 1))
(assert_return (invoke "get2") (i32.const 0x12345678))
(assert_return (invoke "get4") (i64.const 0x0102030405060708))
(assert_return (invoke "get5_is_a") (i32.const 1))
(assert_return (invoke "get7") (i32.const 0x3333))
