;; Struct layout: many adjacent packed fields, written and read independently.

(module
  (type $s (struct
    (field (mut i8))
    (field (mut i8))
    (field (mut i8))
    (field (mut i8))
    (field (mut i8))
    (field (mut i8))
    (field (mut i8))
    (field (mut i8))
    (field (mut i16))
    (field (mut i16))
    (field (mut i16))
    (field (mut i16))
    (field (mut (ref null $s)))
    (field (mut i8))
    (field (mut i8))
    (field (mut i8))
    (field (mut i32))
  ))

  (global $g (ref $s) (struct.new_default $s))

  (func (export "get0") (result i32) (struct.get_u $s 0 (global.get $g)))
  (func (export "gets0") (result i32) (struct.get_s $s 0 (global.get $g)))
  (func (export "set0") (param i32) (struct.set $s 0 (global.get $g) (local.get 0)))
  (func (export "get1") (result i32) (struct.get_u $s 1 (global.get $g)))
  (func (export "gets1") (result i32) (struct.get_s $s 1 (global.get $g)))
  (func (export "set1") (param i32) (struct.set $s 1 (global.get $g) (local.get 0)))
  (func (export "get2") (result i32) (struct.get_u $s 2 (global.get $g)))
  (func (export "gets2") (result i32) (struct.get_s $s 2 (global.get $g)))
  (func (export "set2") (param i32) (struct.set $s 2 (global.get $g) (local.get 0)))
  (func (export "get3") (result i32) (struct.get_u $s 3 (global.get $g)))
  (func (export "gets3") (result i32) (struct.get_s $s 3 (global.get $g)))
  (func (export "set3") (param i32) (struct.set $s 3 (global.get $g) (local.get 0)))
  (func (export "get4") (result i32) (struct.get_u $s 4 (global.get $g)))
  (func (export "gets4") (result i32) (struct.get_s $s 4 (global.get $g)))
  (func (export "set4") (param i32) (struct.set $s 4 (global.get $g) (local.get 0)))
  (func (export "get5") (result i32) (struct.get_u $s 5 (global.get $g)))
  (func (export "gets5") (result i32) (struct.get_s $s 5 (global.get $g)))
  (func (export "set5") (param i32) (struct.set $s 5 (global.get $g) (local.get 0)))
  (func (export "get6") (result i32) (struct.get_u $s 6 (global.get $g)))
  (func (export "gets6") (result i32) (struct.get_s $s 6 (global.get $g)))
  (func (export "set6") (param i32) (struct.set $s 6 (global.get $g) (local.get 0)))
  (func (export "get7") (result i32) (struct.get_u $s 7 (global.get $g)))
  (func (export "gets7") (result i32) (struct.get_s $s 7 (global.get $g)))
  (func (export "set7") (param i32) (struct.set $s 7 (global.get $g) (local.get 0)))
  (func (export "get8") (result i32) (struct.get_u $s 8 (global.get $g)))
  (func (export "gets8") (result i32) (struct.get_s $s 8 (global.get $g)))
  (func (export "set8") (param i32) (struct.set $s 8 (global.get $g) (local.get 0)))
  (func (export "get9") (result i32) (struct.get_u $s 9 (global.get $g)))
  (func (export "gets9") (result i32) (struct.get_s $s 9 (global.get $g)))
  (func (export "set9") (param i32) (struct.set $s 9 (global.get $g) (local.get 0)))
  (func (export "get10") (result i32) (struct.get_u $s 10 (global.get $g)))
  (func (export "gets10") (result i32) (struct.get_s $s 10 (global.get $g)))
  (func (export "set10") (param i32) (struct.set $s 10 (global.get $g) (local.get 0)))
  (func (export "get11") (result i32) (struct.get_u $s 11 (global.get $g)))
  (func (export "gets11") (result i32) (struct.get_s $s 11 (global.get $g)))
  (func (export "set11") (param i32) (struct.set $s 11 (global.get $g) (local.get 0)))
  (func (export "get13") (result i32) (struct.get_u $s 13 (global.get $g)))
  (func (export "gets13") (result i32) (struct.get_s $s 13 (global.get $g)))
  (func (export "set13") (param i32) (struct.set $s 13 (global.get $g) (local.get 0)))
  (func (export "get14") (result i32) (struct.get_u $s 14 (global.get $g)))
  (func (export "gets14") (result i32) (struct.get_s $s 14 (global.get $g)))
  (func (export "set14") (param i32) (struct.set $s 14 (global.get $g) (local.get 0)))
  (func (export "get15") (result i32) (struct.get_u $s 15 (global.get $g)))
  (func (export "gets15") (result i32) (struct.get_s $s 15 (global.get $g)))
  (func (export "set15") (param i32) (struct.set $s 15 (global.get $g) (local.get 0)))
  (func (export "get16") (result i32) (struct.get $s 16 (global.get $g)))
  (func (export "set16") (param i32) (struct.set $s 16 (global.get $g) (local.get 0)))
  (func (export "get12_is_g") (result i32) (ref.eq (struct.get $s 12 (global.get $g)) (global.get $g)))
  (func (export "set12") (struct.set $s 12 (global.get $g) (global.get $g)))
)

(invoke "set0" (i32.const 128))
(invoke "set1" (i32.const 145))
(invoke "set2" (i32.const 162))
(invoke "set3" (i32.const 179))
(invoke "set4" (i32.const 196))
(invoke "set5" (i32.const 213))
(invoke "set6" (i32.const 230))
(invoke "set7" (i32.const 247))
(invoke "set8" (i32.const 67720))
(invoke "set9" (i32.const 72089))
(invoke "set10" (i32.const 76458))
(invoke "set11" (i32.const 80827))
(invoke "set13" (i32.const 195))
(invoke "set14" (i32.const 210))
(invoke "set15" (i32.const 225))
(invoke "set16" (i32.const 3405691582))
(invoke "set12")
(assert_return (invoke "get0") (i32.const 128))
(assert_return (invoke "gets0") (i32.const -128))
(assert_return (invoke "get1") (i32.const 145))
(assert_return (invoke "gets1") (i32.const -111))
(assert_return (invoke "get2") (i32.const 162))
(assert_return (invoke "gets2") (i32.const -94))
(assert_return (invoke "get3") (i32.const 179))
(assert_return (invoke "gets3") (i32.const -77))
(assert_return (invoke "get4") (i32.const 196))
(assert_return (invoke "gets4") (i32.const -60))
(assert_return (invoke "get5") (i32.const 213))
(assert_return (invoke "gets5") (i32.const -43))
(assert_return (invoke "get6") (i32.const 230))
(assert_return (invoke "gets6") (i32.const -26))
(assert_return (invoke "get7") (i32.const 247))
(assert_return (invoke "gets7") (i32.const -9))
(assert_return (invoke "get8") (i32.const 2184))
(assert_return (invoke "gets8") (i32.const 2184))
(assert_return (invoke "get9") (i32.const 6553))
(assert_return (invoke "gets9") (i32.const 6553))
(assert_return (invoke "get10") (i32.const 10922))
(assert_return (invoke "gets10") (i32.const 10922))
(assert_return (invoke "get11") (i32.const 15291))
(assert_return (invoke "gets11") (i32.const 15291))
(assert_return (invoke "get13") (i32.const 195))
(assert_return (invoke "gets13") (i32.const -61))
(assert_return (invoke "get14") (i32.const 210))
(assert_return (invoke "gets14") (i32.const -46))
(assert_return (invoke "get15") (i32.const 225))
(assert_return (invoke "gets15") (i32.const -31))
(assert_return (invoke "get16") (i32.const -889275714))
(assert_return (invoke "get12_is_g") (i32.const 1))
(invoke "set0" (i32.const 0))
(invoke "set2" (i32.const 0))
(invoke "set4" (i32.const 0))
(invoke "set6" (i32.const 0))
(assert_return (invoke "get0") (i32.const 0))
(assert_return (invoke "get1") (i32.const 145))
(assert_return (invoke "get2") (i32.const 0))
(assert_return (invoke "get3") (i32.const 179))
(assert_return (invoke "get4") (i32.const 0))
(assert_return (invoke "get5") (i32.const 213))
(assert_return (invoke "get6") (i32.const 0))
(assert_return (invoke "get7") (i32.const 247))
(assert_return (invoke "get8") (i32.const 2184))
(assert_return (invoke "get9") (i32.const 6553))
(assert_return (invoke "get10") (i32.const 10922))
(assert_return (invoke "get11") (i32.const 15291))
(assert_return (invoke "get13") (i32.const 195))
(assert_return (invoke "get14") (i32.const 210))
(assert_return (invoke "get15") (i32.const 225))
(assert_return (invoke "get16") (i32.const -889275714))
(assert_return (invoke "get12_is_g") (i32.const 1))
