;; Struct layout: struct.new_default initializes every kind of field, then fields are set one at a time.
(module
  (type $s (struct
    (field (mut i64))
    (field (mut anyref))
    (field (mut i8))
    (field (mut (ref null func)))
    (field (mut f64))
    (field (mut eqref))
    (field (mut i16))
    (field (mut (ref null struct)))
    (field (mut f32))
    (field (mut externref))
    (field (mut i32))
    (field (mut (ref null $s)))))

  (global $g (mut (ref null $s)) (ref.null $s))
  (func $f (export "f"))

  (func (export "new") (global.set $g (struct.new_default $s)))
  (func (export "get0") (result i64) (struct.get $s 0 (global.get $g)))
  (func (export "get1_is_null") (result i32) (ref.is_null (struct.get $s 1 (global.get $g))))
  (func (export "get2") (result i32) (struct.get_s $s 2 (global.get $g)))
  (func (export "get3_is_null") (result i32) (ref.is_null (struct.get $s 3 (global.get $g))))
  (func (export "get4") (result f64) (struct.get $s 4 (global.get $g)))
  (func (export "get5_is_null") (result i32) (ref.is_null (struct.get $s 5 (global.get $g))))
  (func (export "get6") (result i32) (struct.get_u $s 6 (global.get $g)))
  (func (export "get7_is_null") (result i32) (ref.is_null (struct.get $s 7 (global.get $g))))
  (func (export "get8") (result f32) (struct.get $s 8 (global.get $g)))
  (func (export "get9_is_null") (result i32) (ref.is_null (struct.get $s 9 (global.get $g))))
  (func (export "get10") (result i32) (struct.get $s 10 (global.get $g)))
  (func (export "get11_is_null") (result i32) (ref.is_null (struct.get $s 11 (global.get $g))))

  (func (export "set_all")
    (struct.set $s 0 (global.get $g) (i64.const -2))
    (struct.set $s 1 (global.get $g) (ref.i31 (i32.const 5)))
    (struct.set $s 2 (global.get $g) (i32.const 0xf0))
    (struct.set $s 3 (global.get $g) (ref.func $f))
    (struct.set $s 4 (global.get $g) (f64.const 1e300))
    (struct.set $s 5 (global.get $g) (global.get $g))
    (struct.set $s 6 (global.get $g) (i32.const 0xf00f))
    (struct.set $s 7 (global.get $g) (global.get $g))
    (struct.set $s 8 (global.get $g) (f32.const -0.0))
    (struct.set $s 10 (global.get $g) (i32.const 0x80000000))
    (struct.set $s 11 (global.get $g) (global.get $g)))
  (func (export "set9") (param externref) (struct.set $s 9 (global.get $g) (local.get 0)))

  (func (export "get1_i31") (result i32) (i31.get_u (ref.cast (ref i31) (struct.get $s 1 (global.get $g)))))
  (func (export "get3_call") (result i32)
    (call_ref $void (ref.cast (ref $void) (struct.get $s 3 (global.get $g))))
    (i32.const 42))
  (type $void (func))
  (func (export "get5_is_g") (result i32) (ref.eq (struct.get $s 5 (global.get $g)) (global.get $g)))
  (func (export "get7_is_g") (result i32) (ref.eq (struct.get $s 7 (global.get $g)) (global.get $g)))
  (func (export "get9") (result externref) (struct.get $s 9 (global.get $g)))
  (func (export "get11_is_g") (result i32) (ref.eq (struct.get $s 11 (global.get $g)) (global.get $g)))
)

(invoke "new")
(assert_return (invoke "get0") (i64.const 0))
(assert_return (invoke "get1_is_null") (i32.const 1))
(assert_return (invoke "get2") (i32.const 0))
(assert_return (invoke "get3_is_null") (i32.const 1))
(assert_return (invoke "get4") (f64.const 0))
(assert_return (invoke "get5_is_null") (i32.const 1))
(assert_return (invoke "get6") (i32.const 0))
(assert_return (invoke "get7_is_null") (i32.const 1))
(assert_return (invoke "get8") (f32.const 0))
(assert_return (invoke "get9_is_null") (i32.const 1))
(assert_return (invoke "get10") (i32.const 0))
(assert_return (invoke "get11_is_null") (i32.const 1))

(invoke "set_all")
(invoke "set9" (ref.extern 7))
(assert_return (invoke "get0") (i64.const -2))
(assert_return (invoke "get1_is_null") (i32.const 0))
(assert_return (invoke "get1_i31") (i32.const 5))
(assert_return (invoke "get2") (i32.const -16))
(assert_return (invoke "get3_is_null") (i32.const 0))
(assert_return (invoke "get3_call") (i32.const 42))
(assert_return (invoke "get4") (f64.const 1e300))
(assert_return (invoke "get5_is_g") (i32.const 1))
(assert_return (invoke "get6") (i32.const 0xf00f))
(assert_return (invoke "get7_is_g") (i32.const 1))
(assert_return (invoke "get8") (f32.const -0.0))
(assert_return (invoke "get9_is_null") (i32.const 0))
(assert_return (invoke "get9") (ref.extern 7))
(assert_return (invoke "get10") (i32.const 0x80000000))
(assert_return (invoke "get11_is_g") (i32.const 1))

;; A fresh instance has defaults again.
(invoke "new")
(assert_return (invoke "get0") (i64.const 0))
(assert_return (invoke "get1_is_null") (i32.const 1))
(assert_return (invoke "get2") (i32.const 0))
(assert_return (invoke "get3_is_null") (i32.const 1))
(assert_return (invoke "get6") (i32.const 0))
(assert_return (invoke "get9_is_null") (i32.const 1))
(assert_return (invoke "get10") (i32.const 0))
(assert_return (invoke "get11_is_null") (i32.const 1))
