(module $M
  (type $s (struct))
  (type $t (struct (field i32)))
  (type $a (array i32))
  (func (export "f") (result i32)
    (local (ref $a))
    (local (ref $a))
    (local (ref $a))
    (local (ref $a))
    (local (ref $s))
    (local (ref $s))
    (local (ref $s))
    (local (ref eq))
    (local (ref eq))
    (local (ref eq))
    (local (ref eq))
    (local (ref eq))
    (local (ref eq))
    (local (ref $s))
    (local (ref $s))
    (local (ref $s))
    (local (ref $s))
    (local (ref $s))
    (local (ref $s))
    (local (ref i31))
    (local (ref $t))
    (local (ref $t))
    (local (ref $t))
    (local (ref $t))
    (local (ref $t))

    (i32.const 11)
  )
)

(assert_return (invoke "f") (i32.const 11))
