(module
  (type $0 (struct))
  (type $1 (func (param (ref eq) (ref eq))))
  (type $2 (func))
  (export "_start" (func 0))
  (elem $0 declare func 1)
  (func $0
    (type 2)
    (local (ref eq) (ref eq) (ref eq))
    (struct.new_default 0)
    (local.set 0)
    (struct.new_default 0)
    (local.set 1)
    (struct.new_default 0)
    (local.set 2)
    (local.get 0)
    (local.get 1)
    (ref.func 1)
    (call_ref 1)
  )
  (func $1 (type 1) (unreachable))
)

(assert_trap (invoke "_start") "unreachable")
