(module
  (type $S (struct))
  (type $1 (func (param i32)))
  (global $0 (ref $S) (struct.new_default $S))
  (global $1 (ref $S) (struct.new_default $S))
  (global $g (mut i32) (i32.const 7))

  (func $set (param i32) (global.set $g (local.get 0)))

  (func (export "main")
    (global.get $1)
    (global.get $0)
    (i32.const 1)
    (select (result (ref $S)))
    (global.get $0)
    (ref.eq)
    (call $set)
  )
  (func (export "get") (result i32) (global.get $g))
)
(assert_return (invoke "main"))
(assert_return (invoke "get") (i32.const 0))
