(module
  (func $nop)
  ;; every activation is interpreted until its loop is OSR-compiled, so each compiles $f again
  (func $f (param $n i32) (local $i i32)
    (if (local.get $n) (then (call $f (i32.sub (local.get $n) (i32.const 1)))))
    (loop $l
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (call $nop)
      (br_if $l (i32.lt_u (local.tee $i (i32.add (local.get $i) (i32.const 1))) (i32.const 20)))))
  (func (export "main") (call $f (i32.const 8))))
