(module
  (type $0 (func))
  (type $1 (struct (field i32) (field (ref null eq))))
  (type $2 (struct (field (ref null eq)) (field (ref null 2))))
  (type $3 (array (mut i8)))
  (type $4 (struct (field i64)))
  (type $5 (struct (field f64)))
  (type $6 (func (param (ref null 3) i32 i32)))
  (type $7 (func (param i32)))
  (type $8 (func (param (ref null struct)) (result (ref null none))))
  (type $9 (struct (field (ref 8)) (field (ref null struct))))
  (type $10 (func (param (ref 9) (ref null struct)) (result (ref 9))))
  (type $11 (struct (field (ref 10)) (field (ref null struct))))
  (type $12 (func (param (ref null struct)) (result (ref null eq))))
  (type $13 (struct (field (ref 12)) (field (ref null struct))))
  (type $14 (func (param (ref 13) (ref null struct)) (result (ref 13))))
  (type $15 (struct (field (ref 14)) (field (ref null struct))))
  (type $16 (func (param i64 (ref null struct)) (result (ref null none))))
  (type $17 (func (param i64 (ref null struct)) (result (ref null eq))))
  (type $18 (struct (field (ref 17)) (field (ref null struct))))
  (type $19 (func (param i64 (ref null struct)) (result (ref 18))))
  (type $20 (struct (field (ref 19)) (field (ref null struct))))
  (type $21 (struct (field (ref 20))))
  (type $22 (func (param (ref null none) (ref null struct)) (result (ref 18))))
  (type $23 (struct (field (ref 22)) (field (ref null struct))))
  (type $24 (struct (field i64) (field (ref 23))))
  (type $25 (struct (field (ref null eq))))
  (type $26 (struct (field i64) (field (ref 13))))
  (type $27 (struct (field (ref 13))))
  (type $28 (func (param (ref null eq)) (result (ref null eq))))
  (type $29 (cont 28))
  (type $30
    (func (param (ref 29) (ref null eq) (ref null struct)) (result (ref 18)))
  )
  (type $31 (struct (field (ref 29)) (field (ref null struct))))
  (type $32 (func (param (ref null eq) (ref 29)) (result (ref null eq) (ref 29))))
  (type $33 (func (param (ref null eq) (ref 29)) (result (ref 18))))
  (type $34 (func (param i64 (ref null struct)) (result (ref 15))))
  (type $35 (func (param i64) (result (ref 15))))
  (type $36 (func (result (ref null none))))
  (type $37 (func (param i64) (result (ref null none))))
  (import "wizeng" "puta" (func $0 (type 6)))
  (import "wizeng" "putc" (func $1 (type 7)))
  (global (export "_init_result") (mut (ref null none)) (ref.null none))
  (global (ref 8) (ref.func 3))
  (global (ref 17) (ref.func 4))
  (global (ref 17) (ref.func 5))
  (global (ref 17) (ref.func 6))
  (global (ref 12) (ref.func 7))
  (global (ref 28) (ref.func 8))
  (global (ref 19) (ref.func 10))
  (global (ref 22) (ref.func 11))
  (global (ref 14) (ref.func 12))
  (global (ref 10) (ref.func 15))
  (global (ref 12) (ref.func 16))
  (global (ref 8) (ref.func 17))
  (func $2 (type 16) (local i64 i64)
    (local.get 0)
    (local.set 2)
    (ref.null none)
    (suspend 0)
    (ref.cast (ref 4))
    (struct.get 4 0)
    (local.set 3)
    (local.get 2)
    (local.get 3)
    (i64.add)
    (struct.new 4)
    (suspend 1)
    (drop)
    (ref.null none)
  )
  (func $3 (type 8) (local i64 (ref null none))
    (loop (result (ref null none))
      (ref.null none)
      (suspend 0)
      (ref.cast (ref 4))
      (struct.get 4 0)
      (local.set 1)
      (local.get 1)
      (i64.const 0)
      (i64.eq)
      (if (result (ref null none))
        (then (ref.null none))
        (else
          (i64.const 0)
          (i64.const 1)
          (i64.sub)
          (ref.null none)
          (call 2)
          (local.set 2)
          (ref.null none)
          (local.set 0)
          (br 1)
        )
      )
    )
  )
  (func $4 (type 17) (local i64 (ref 18) (ref 21))
    (local.get 1)
    (ref.cast (ref 21))
    (local.set 4)
    (local.get 0)
    (local.set 2)
    (local.get 2)
    (local.get 4)
    (struct.get 21 0)
    (struct.get 20 1)
    (local.get 4)
    (struct.get 21 0)
    (struct.get 20 0)
    (call_ref 19)
    (local.set 3)
    (local.get 2)
    (local.get 3)
    (struct.get 18 1)
    (local.get 3)
    (struct.get 18 0)
    (return_call_ref 17)
  )
  (func $5 (type 17) (local (ref 18) (ref 24))
    (local.get 1)
    (ref.cast (ref 24))
    (local.set 3)
    (ref.null none)
    (local.get 3)
    (struct.get 24 1)
    (struct.get 23 1)
    (local.get 3)
    (struct.get 24 1)
    (struct.get 23 0)
    (call_ref 22)
    (local.set 2)
    (local.get 3)
    (struct.get 24 0)
    (local.get 2)
    (struct.get 18 1)
    (local.get 2)
    (struct.get 18 0)
    (return_call_ref 17)
  )
  (func $6 (type 17) (local (ref 25))
    (local.get 1)
    (ref.cast (ref 25))
    (local.set 2)
    (local.get 2)
    (struct.get 25 0)
  )
  (func $7 (type 12) (local (ref 18) (ref 26))
    (local.get 0)
    (ref.cast (ref 26))
    (local.set 2)
    (ref.func 8)
    (cont.new 29)
    (local.get 2)
    (struct.get 26 1)
    (struct.new 27)
    (ref.null none)
    (call 9)
    (local.set 1)
    (local.get 2)
    (struct.get 26 0)
    (local.get 1)
    (struct.get 18 1)
    (local.get 1)
    (struct.get 18 0)
    (return_call_ref 17)
  )
  (func $8 (type 28) (local (ref 27))
    (local.get 0)
    (ref.cast (ref 27))
    (local.set 1)
    (local.get 1)
    (struct.get 27 0)
    (struct.get 13 1)
    (local.get 1)
    (struct.get 27 0)
    (struct.get 13 0)
    (return_call_ref 12)
  )
  (func $9 (type 30) (local (ref null eq) (ref null eq) i64 i64)
    (local.get 1)
    (local.get 0)
    (loop (type 33)
      (block (type 32)
        (block (type 32)
          (resume 29 (on 0 1) (on 1 0))
          (local.set 3)
          (local.get 3)
          (local.set 4)
          (ref.func 6)
          (local.get 4)
          (struct.new 25)
          (struct.new 18)
          (return)
        )
        (local.set 0)
        (ref.cast (ref 4))
        (struct.get 4 0)
        (local.set 5)
        (local.get 5)
        (local.set 6)
        (ref.func 5)
        (local.get 6)
        (ref.func 11)
        (local.get 0)
        (local.get 2)
        (struct.new 31)
        (struct.new 23)
        (struct.new 24)
        (struct.new 18)
        (return)
      )
      (local.set 0)
      (drop)
      (ref.func 4)
      (ref.func 10)
      (local.get 0)
      (local.get 2)
      (struct.new 31)
      (struct.new 20)
      (struct.new 21)
      (struct.new 18)
      (return)
    )
  )
  (func $10 (type 19) (local (ref 31))
    (local.get 1)
    (ref.cast (ref 31))
    (local.set 2)
    (local.get 2)
    (struct.get 31 0)
    (local.get 0)
    (struct.new 4)
    (local.get 2)
    (struct.get 31 1)
    (return_call 9)
  )
  (func $11 (type 22) (local (ref 31))
    (local.get 1)
    (ref.cast (ref 31))
    (local.set 2)
    (local.get 2)
    (struct.get 31 0)
    (local.get 0)
    (local.get 2)
    (struct.get 31 1)
    (return_call 9)
  )
  (func $12 (type 14) (local (ref 13) (ref 4))
    (local.get 1)
    (ref.cast (ref 4))
    (local.set 3)
    (local.get 0)
    (local.set 2)
    (ref.func 7)
    (local.get 3)
    (struct.get 4 0)
    (local.get 2)
    (struct.new 26)
    (struct.new 13)
  )
  (func $13 (type 34) (local i64)
    (local.get 0)
    (local.set 2)
    (ref.func 12)
    (local.get 2)
    (struct.new 4)
    (struct.new 15)
  )
  (func $14 (export "main") (type 0) (local (ref 11) (ref 9))
    (ref.func 15)
    (i64.const 196_864)
    (ref.null none)
    (call 13)
    (struct.new 11)
    (local.set 0)
    (ref.func 3)
    (ref.null none)
    (struct.new 9)
    (local.get 0)
    (struct.get 11 1)
    (local.get 0)
    (struct.get 11 0)
    (call_ref 10)
    (local.set 1)
    (local.get 1)
    (struct.get 9 1)
    (local.get 1)
    (struct.get 9 0)
    (call_ref 8)
    (global.set 0)
    (global.get 0)
    (drop)
    (i32.const 40)
    (call 1)
    (i32.const 41)
    (call 1)
    (i32.const 32)
    (call 1)
    (i32.const 58)
    (call 1)
    (i32.const 32)
    (call 1)
    (i32.const 40)
    (call 1)
    (i32.const 41)
    (call 1)
    (i32.const 10)
    (call 1)
  )
  (func $15 (type 10) (local (ref 15))
    (ref.func 17)
    (local.get 1)
    (ref.cast (ref 15))
    (local.set 2)
    (ref.func 16)
    (local.get 0)
    (struct.new 13)
    (local.get 2)
    (struct.get 15 1)
    (local.get 2)
    (struct.get 15 0)
    (call_ref 14)
    (struct.new 9)
  )
  (func $16 (type 12) (local (ref 9))
    (local.get 0)
    (ref.cast (ref 9))
    (local.set 1)
    (local.get 1)
    (struct.get 9 1)
    (local.get 1)
    (struct.get 9 0)
    (call_ref 8)
  )
  (func $17 (type 8) (local (ref 13))
    (local.get 0)
    (ref.cast (ref 13))
    (local.set 1)
    (local.get 1)
    (struct.get 13 1)
    (local.get 1)
    (struct.get 13 0)
    (call_ref 12)
    (drop)
    (ref.null none)
  )
  (func $18 (export "evalState") (type 35)
    (local.get 0)
    (ref.null none)
    (return_call 13)
  )
  (func $19 (export "loop") (type 36) (ref.null none) (return_call 3))
  (func $20 (export "incr") (type 37)
    (local.get 0)
    (ref.null none)
    (return_call 2)
  )
  (tag (type 28))
  (tag (type 28))
)
