(module
  (type $0 (func))
  (type $1 (struct (field i32) (field (ref null eq))))
  (type $2 (struct (field (ref null eq)) (field (ref null 2))))
  (type $3 (array (mut i8)))
  (type $4 (struct (field i64)))
  (type $5 (struct (field f64)))
  (type $6 (struct (field i32) (field (mut (ref null eq)))))
  (type $7 (func (result (ref null eq))))
  (type $8 (cont 7))
  (type $9 (func (param (ref null eq)) (result (ref null eq))))
  (type $10 (cont 9))
  (rec
    (type $11
      (struct
        (field (mut i8))
        (field (mut (ref null 2)))
        (field (mut (ref null 2)))
        (field (mut (ref null 12)))
      )
    )
    (type $12
      (struct
        (field (mut (ref 6)))
        (field (mut (ref 10)))
        (field (mut (ref null 12)))
      )
    )
  )
  (type $13
    (struct (field (ref 6)) (field (mut (ref null 8))) (field (mut (ref null 13))))
  )
  (type $14 (struct (field (ref 6)) (field (ref null 14))))
  (type $15 (func (param (ref null 3) i32 i32)))
  (type $16 (func (param i32)))
  (type $17 (func (param i64)))
  (type $18 (func (param (ref null struct)) (result i64)))
  (type $19 (struct (field (ref 18)) (field (ref null struct))))
  (type $20 (func (param (ref null struct)) (result (ref null eq))))
  (type $21 (struct (field (ref 20)) (field (ref null struct))))
  (type $22 (func (param (ref 6)) (result (ref null eq))))
  (type $23 (cont 22))
  (type $24 (cont 20))
  (type $25 (func (result (ref 21) (ref 23))))
  (type $26 (func (result (ref 11) (ref 10))))
  (type $27 (func (param (ref 23)) (result (ref null eq))))
  (type $28 (func (param i64 (ref null 2) (ref null struct)) (result i64)))
  (type $29
    (func (param i64 (ref null 2) (ref null struct)) (result (ref null none)))
  )
  (type $30 (struct (field (ref 28)) (field (ref null struct))))
  (type $31 (struct (field (ref 30))))
  (type $32
    (func
      (param (ref null 6) (ref null eq) (ref null struct))
      (result (ref null none))
    )
  )
  (type $33 (func (param (ref null struct)) (result (ref null none))))
  (type $34 (func (param i64 (ref null struct)) (result (ref null none))))
  (type $35 (struct (field (ref null 6))))
  (type $36 (struct (field (ref 34)) (field (ref null struct))))
  (type $37 (struct (field (ref null 6)) (field i64) (field (ref 36))))
  (type $38 (func (param (ref null struct)) (result (ref null 6))))
  (type $39
    (func (param i64 (ref null 6) (ref null struct)) (result (ref null none)))
  )
  (type $40 (struct (field (ref 33)) (field (ref null struct))))
  (type $41
    (func (param (ref null none) (ref 21) (ref null struct)) (result (ref null 6)))
  )
  (type $42 (func (param (ref null 6) (ref null struct)) (result (ref null eq))))
  (type $43 (func (param (ref 11)) (result (ref null eq))))
  (type $44 (func (result (ref 6))))
  (type $45 (func (param (ref 21)) (result (ref 6))))
  (import "wizeng" "puta" (func $0 (type 15)))
  (import "wizeng" "putc" (func $1 (type 16)))
  (global (export "_init_result") (mut i64) (i64.const 0))
  (global (mut i64) (i64.const 0))
  (global (mut (ref null 14)) (ref.null 14))
  (global (ref 28) (ref.func 2))
  (global (ref 33) (ref.func 6))
  (global (ref 34) (ref.func 7))
  (global (ref 18) (ref.func 11))
  (global (ref 20) (ref.func 18))
  (global (ref 7) (ref.func 20))
  (global (ref 20) (ref.func 22))
  (func $2 (type 28) (local (ref null 2) i64 (ref null 2) i64 (ref null 2) (ref null 2) i64 i64)
    (loop (result i64)
      (local.get 1)
      (local.set 3)
      (local.get 0)
      (local.set 4)
      (local.get 3)
      (local.set 5)
      (local.get 5)
      (ref.is_null)
      (if (result i64)
        (then (local.get 4))
        (else
          (local.get 5)
          (struct.get 2 0)
          (ref.cast (ref 4))
          (struct.get 4 0)
          (local.set 6)
          (local.get 5)
          (struct.get 2 1)
          (local.set 7)
          (local.get 7)
          (local.set 8)
          (local.get 6)
          (local.set 9)
          (local.get 9)
          (i64.const 503)
          (local.get 4)
          (i64.mul)
          (i64.sub)
          (i64.const 37)
          (i64.add)
          (i64.const 1_009)
          (i64.rem_s)
          (local.set 10)
          (local.get 10)
          (local.get 8)
          (ref.null none)
          (local.set 2)
          (local.set 1)
          (local.set 0)
          (call 19)
          (br 1)
        )
      )
    )
  )
  (func $3 (type 29) (local (ref null 2) i64 (ref 1) (ref 1) (ref null none) i64 i64 i64 (ref null 6) (ref null 6) (ref 31))
    (loop (result (ref null none))
      (local.get 2)
      (ref.cast (ref 31))
      (local.set 13)
      (local.get 1)
      (local.set 3)
      (local.get 0)
      (local.set 4)
      (ref.null none)
      (call 19)
      (call 4)
      (ref.cast (ref 1))
      (local.set 5)
      (local.get 5)
      (local.set 6)
      (block (result (ref null none))
        (block
          (block
            (block
              (block (local.get 6) (struct.get 1 0) (br_table 2 1 0 3))
              (local.get 6)
              (struct.get 1 1)
              (ref.cast (ref 6))
              (local.set 11)
              (local.get 11)
              (local.set 12)
              (local.get 12)
              (i32.const 3)
              (local.get 4)
              (struct.new 4)
              (struct.new 1)
              (ref.null none)
              (call 19)
              (return_call 5)
              (br 3)
            )
            (local.get 6)
            (struct.get 1 1)
            (ref.cast (ref 4))
            (struct.get 4 0)
            (local.set 9)
            (local.get 9)
            (local.set 10)
            (local.get 4)
            (local.get 10)
            (struct.new 4)
            (local.get 3)
            (struct.new 2)
            (local.get 2)
            (local.set 2)
            (local.set 1)
            (local.set 0)
            (call 19)
            (br 3)
            (br 2)
          )
          (local.get 6)
          (struct.get 1 1)
          (drop)
          (ref.null none)
          (local.set 7)
          (local.get 4)
          (local.get 3)
          (local.get 13)
          (struct.get 31 0)
          (struct.get 30 1)
          (local.get 13)
          (struct.get 31 0)
          (struct.get 30 0)
          (call 19)
          (call_ref 28)
          (local.set 8)
          (local.get 8)
          (ref.null 2)
          (local.get 2)
          (local.set 2)
          (local.set 1)
          (local.set 0)
          (call 19)
          (br 2)
          (br 1)
        )
        (unreachable)
      )
    )
  )
  (func $4 (type 20) (local (ref 11) (ref 2))
    (suspend 1)
    (struct.get 6 1)
    (ref.cast (ref 11))
    (local.tee 1)
    (block (result (ref 2))
      (local.get 1)
      (struct.get 11 2)
      (br_on_non_null 0)
      (loop (result (ref 2))
        (block (result (ref 11))
          (loop (result (ref 11))
            (local.get 1)
            (local.get 1)
            (struct.get 11 1)
            (br_on_null 1)
            (local.tee 2)
            (struct.get 2 1)
            (struct.set 11 1)
            (local.get 1)
            (local.get 2)
            (struct.get 2 0)
            (local.get 1)
            (struct.get 11 2)
            (struct.new 2)
            (struct.set 11 2)
            (br 0)
          )
        )
        (struct.get 11 2)
        (br_on_non_null 1)
        (local.get 1)
        (i32.const 1)
        (struct.set 11 0)
        (suspend 2)
        (br 0)
      )
    )
    (local.tee 2)
    (struct.get 2 1)
    (struct.set 11 2)
    (local.get 2)
    (struct.get 2 0)
  )
  (func $5 (type 32) (local (ref 11))
    (block (result (ref 11))
      (local.get 0)
      (struct.get 6 1)
      (br_on_cast 0 (ref null eq) (ref 11))
      (drop)
      (ref.null none)
      (return)
    )
    (local.tee 3)
    (i32.const 0)
    (struct.set 11 0)
    (local.get 3)
    (local.get 1)
    (local.get 3)
    (struct.get 11 1)
    (struct.new 2)
    (struct.set 11 1)
    (ref.null none)
  )
  (func $6 (type 33)
    (i64.const 0)
    (ref.null 2)
    (ref.func 2)
    (ref.null none)
    (struct.new 30)
    (struct.new 31)
    (call 19)
    (return_call 3)
  )
  (func $7 (type 34) (local i64 (ref null none) (ref 35))
    (loop (result (ref null none))
      (local.get 1)
      (ref.cast (ref 35))
      (local.set 4)
      (local.get 0)
      (local.set 2)
      (local.get 2)
      (i64.const 0)
      (i64.eq)
      (if (result (ref null none))
        (then
          (local.get 4)
          (struct.get 35 0)
          (i32.const 0)
          (ref.null none)
          (struct.new 1)
          (ref.null none)
          (call 19)
          (return_call 5)
        )
        (else
          (local.get 4)
          (struct.get 35 0)
          (i32.const 1)
          (local.get 2)
          (struct.new 4)
          (struct.new 1)
          (ref.null none)
          (call 19)
          (call 5)
          (local.set 3)
          (local.get 2)
          (i64.const 1)
          (i64.sub)
          (local.get 1)
          (local.set 1)
          (local.set 0)
          (call 19)
          (br 1)
        )
      )
    )
  )
  (func $8 (type 34) (local i64 (ref null 6) (ref null none) (ref 37))
    (loop (result (ref null none))
      (local.get 1)
      (ref.cast (ref 37))
      (local.set 5)
      (local.get 0)
      (local.set 2)
      (local.get 2)
      (i64.const 0)
      (i64.eq)
      (if (result (ref null none))
        (then
          (ref.null none)
          (call 19)
          (call 9)
          (local.set 3)
          (local.get 5)
          (struct.get 37 0)
          (i32.const 2)
          (local.get 3)
          (struct.new 1)
          (ref.null none)
          (call 19)
          (return_call 5)
        )
        (else
          (local.get 5)
          (struct.get 37 1)
          (local.get 5)
          (struct.get 37 2)
          (struct.get 36 1)
          (local.get 5)
          (struct.get 37 2)
          (struct.get 36 0)
          (call 19)
          (call_ref 34)
          (local.set 4)
          (local.get 2)
          (i64.const 1)
          (i64.sub)
          (local.get 1)
          (local.set 1)
          (local.set 0)
          (call 19)
          (br 1)
        )
      )
    )
  )
  (func $9 (type 38) (suspend 1))
  (func $10 (type 39) (local (ref null 6) i64)
    (local.get 1)
    (local.set 3)
    (local.get 0)
    (local.set 4)
    (i64.const 1_000)
    (local.get 3)
    (local.get 4)
    (ref.func 7)
    (local.get 3)
    (struct.new 35)
    (struct.new 36)
    (struct.new 37)
    (call 19)
    (return_call 8)
  )
  (func $11 (type 18) (local (ref null none) (ref null 6) (ref null none) (ref 1) (ref 1) i64 i64)
    (ref.null none)
    (call 19)
    (call 12)
    (local.set 1)
    (local.get 1)
    (ref.func 22)
    (ref.func 6)
    (ref.null none)
    (struct.new 40)
    (struct.new 21)
    (ref.null none)
    (call 19)
    (call 13)
    (local.set 2)
    (i64.const 1_000)
    (local.get 2)
    (ref.null none)
    (call 19)
    (call 10)
    (local.set 3)
    (ref.null none)
    (call 19)
    (call 4)
    (ref.cast (ref 1))
    (local.set 4)
    (local.get 4)
    (local.set 5)
    (local.get 5)
    (struct.get 1 1)
    (ref.cast (ref 4))
    (struct.get 4 0)
    (local.set 6)
    (local.get 6)
    (local.set 7)
    (local.get 7)
  )
  (func $12 (type 33) (ref.null none))
  (func $13 (type 41) (local.get 1) (suspend 0))
  (func $14 (type 42)
    (local.get 0)
    (struct.get 6 1)
    (br_on_cast_fail 0 (ref null eq) (ref 11))
    (suspend 3)
  )
  (func $15 (type 0)
    (ref.null none)
    (call 19)
    (call 12)
    (ref.func 18)
    (ref.func 11)
    (ref.null none)
    (struct.new 19)
    (struct.new 21)
    (ref.null none)
    (call 19)
    (call 13)
    (ref.null none)
    (call 19)
    (call 14)
    (ref.cast (ref 4))
    (struct.get 4 0)
    (global.set 0)
    (global.get 0)
    (call 17)
    (i32.const 32)
    (call 1)
    (i32.const 58)
    (call 1)
    (i32.const 32)
    (call 1)
    (i32.const 73)
    (call 1)
    (i32.const 110)
    (call 1)
    (i32.const 116)
    (call 1)
    (i32.const 10)
    (call 1)
  )
  (func $16 (type 17)
    (local.get 0)
    (i64.eqz)
    (br_if 0)
    (local.get 0)
    (i64.const 10)
    (i64.lt_u)
    (if (result i64)
      (then (local.get 0))
      (else
        (local.get 0)
        (i64.const 10)
        (i64.div_u)
        (call 16)
        (local.get 0)
        (i64.const 10)
        (i64.rem_u)
      )
    )
    (i32.wrap_i64)
    (i32.const 48)
    (i32.add)
    (call 1)
  )
  (func $17 (type 17)
    (local.get 0)
    (i64.const 0)
    (i64.ge_s)
    (if (result i64)
      (then
        (local.get 0)
        (i64.eqz)
        (if (then (i32.const 48) (return_call 1)))
        (local.get 0)
      )
      (else (i32.const 45) (call 1) (i64.const 0) (local.get 0) (i64.sub))
    )
    (call 16)
  )
  (func $18 (type 20) (local (ref 19))
    (local.get 0)
    (ref.cast (ref 19))
    (local.set 1)
    (local.get 1)
    (struct.get 19 1)
    (local.get 1)
    (struct.get 19 0)
    (call_ref 18)
    (struct.new 4)
  )
  (func $19 (type 0)
    (global.get 1)
    (i64.eqz)
    (if
      (then (suspend 2))
      (else (global.get 1) (i64.const 1) (i64.sub) (global.set 1))
    )
  )
  (func $20 (type 7)
    (call 15)
    (block
      (loop
        (block (result (ref null eq))
          (global.get 2)
          (br_on_null 2)
          (struct.get 14 0)
          (global.get 2)
          (struct.get 14 1)
          (global.set 2)
          (struct.get 6 1)
          (br_on_cast_fail 0 (ref null eq) (ref 11))
          (suspend 3)
        )
        (drop)
        (br 0)
      )
    )
    (ref.null none)
  )
  (func $21 (export "main") (type 0) (local i32 (ref 13) (ref 13) (ref null eq) (ref 23) (ref 21) (ref 8) (ref 10) (ref 11))
    (i32.const 1)
    (local.set 0)
    (i32.const 0)
    (i32.const 0)
    (ref.null 2)
    (ref.null 2)
    (ref.null 12)
    (struct.new 11)
    (struct.new 6)
    (ref.func 20)
    (cont.new 8)
    (ref.null 13)
    (struct.new 13)
    (local.tee 1)
    (local.set 2)
    (block
      (loop
        (block
          (block (type 26)
            (block (result (ref 8))
              (block (type 25)
                (block (result (ref null eq))
                  (block (result (ref 23))
                    (local.get 2)
                    (struct.get 13 0)
                    (struct.get 6 1)
                    (ref.cast (ref 11))
                    (struct.get_u 11 0)
                    (br_if 5)
                    (i64.const 99)
                    (global.set 1)
                    (local.get 2)
                    (struct.get 13 1)
                    (resume 8 (on 1 0) (on 0 2) (on 2 3) (on 3 4))
                    (br 1)
                  )
                  (loop (type 27)
                    (local.set 4)
                    (local.get 2)
                    (struct.get 13 0)
                    (local.get 4)
                    (resume 23 (on 1 0) (on 0 2) (on 2 3) (on 3 4))
                    (br 1)
                  )
                )
                (local.set 3)
                (local.get 2)
                (struct.get 13 0)
                (struct.get 6 1)
                (ref.cast (ref 11))
                (local.set 8)
                (block (result (ref 13))
                  (loop (result (ref 13))
                    (local.get 2)
                    (local.get 8)
                    (struct.get 11 3)
                    (br_on_null 1)
                    (struct.get 12 0)
                    (local.get 3)
                    (local.get 8)
                    (struct.get 11 3)
                    (ref.as_non_null)
                    (struct.get 12 1)
                    (cont.bind 10 8)
                    (local.get 2)
                    (struct.get 13 2)
                    (struct.new 13)
                    (struct.set 13 2)
                    (local.get 8)
                    (local.get 8)
                    (struct.get 11 3)
                    (ref.as_non_null)
                    (struct.get 12 2)
                    (struct.set 11 3)
                    (br 0)
                  )
                )
                (struct.get 13 0)
                (local.get 3)
                (struct.set 6 1)
                (local.get 2)
                (ref.null 8)
                (struct.set 13 1)
                (br 3)
              )
              (local.set 4)
              (local.set 5)
              (local.get 2)
              (local.get 0)
              (local.get 0)
              (i32.const 1)
              (i32.add)
              (local.set 0)
              (i32.const 0)
              (ref.null 2)
              (ref.null 2)
              (ref.null 12)
              (struct.new 11)
              (local.tee 8)
              (struct.new 6)
              (local.get 5)
              (struct.get 21 1)
              (local.get 5)
              (struct.get 21 0)
              (cont.new 24)
              (cont.bind 24 8)
              (local.get 2)
              (struct.get 13 2)
              (struct.new 13)
              (struct.set 13 2)
              (local.get 2)
              (local.get 2)
              (struct.get 13 2)
              (struct.get 13 0)
              (local.get 4)
              (cont.bind 23 8)
              (struct.set 13 1)
              (br 3)
            )
            (local.set 6)
            (local.get 2)
            (local.get 6)
            (struct.set 13 1)
            (br 1)
          )
          (local.set 7)
          (local.set 8)
          (local.get 2)
          (ref.null 8)
          (struct.set 13 1)
          (local.get 8)
          (local.get 2)
          (struct.get 13 0)
          (local.get 7)
          (local.get 8)
          (struct.get 11 3)
          (struct.new 12)
          (struct.set 11 3)
          (br 0)
        )
        (loop
          (block
            (loop
              (block
                (local.get 2)
                (struct.get 13 2)
                (br_on_null 2)
                (struct.get 13 1)
                (br_on_null 0)
                (local.get 2)
                (struct.get 13 2)
                (ref.as_non_null)
                (local.set 2)
                (br 4)
              )
              (local.get 2)
              (local.get 2)
              (struct.get 13 2)
              (struct.get 13 2)
              (struct.set 13 2)
              (br 0)
            )
          )
          (local.get 1)
          (local.tee 2)
          (struct.get 13 1)
          (ref.is_null)
          (i32.eqz)
          (br_if 1)
          (local.get 1)
          (struct.get 13 0)
          (struct.get 6 1)
          (ref.test (ref 11))
          (i32.eqz)
          (br_if 2)
          (local.get 1)
          (struct.get 13 2)
          (ref.is_null)
          (i32.eqz)
          (br_if 0)
          (loop (br 0))
        )
      )
    )
  )
  (func $22 (type 20) (local (ref 40))
    (local.get 0)
    (ref.cast (ref 40))
    (local.set 1)
    (local.get 1)
    (struct.get 40 1)
    (local.get 1)
    (struct.get 40 0)
    (call_ref 33)
  )
  (tag (type 45))
  (tag (type 44))
  (tag (type 0))
  (tag (type 43))
)
