(module
  (type $0 (func))
  (type $1 (struct (field i32) (field (ref null eq))))
  (type $2 (struct (field (ref null eq)) (field (ref null 2))))
  (type $3 (array (mut i8)))
  (type $4 (struct (field i64)))
  (type $5 (struct (field f64)))
  (type $6 (struct (field i32) (field (mut (ref null eq)))))
  (type $7 (func (result (ref null eq))))
  (type $8 (cont 7))
  (type $9 (func (param (ref null eq)) (result (ref null eq))))
  (type $10 (cont 9))
  (rec
    (type $11
      (struct
        (field (mut i8))
        (field (mut (ref null 2)))
        (field (mut (ref null 2)))
        (field (mut (ref null 12)))
      )
    )
    (type $12
      (struct
        (field (mut (ref 6)))
        (field (mut (ref 10)))
        (field (mut (ref null 12)))
      )
    )
  )
  (type $13
    (struct (field (ref 6)) (field (mut (ref null 8))) (field (mut (ref null 13))))
  )
  (type $14 (struct (field (ref 6)) (field (ref null 14))))
  (type $15 (func (param (ref null 3) i32 i32)))
  (type $16 (func (param i32)))
  (type $17 (func (param i64)))
  (type $18 (func (param (ref null struct)) (result (ref null eq))))
  (type $19 (struct (field (ref 18)) (field (ref null struct))))
  (type $20 (func (param (ref 6)) (result (ref null eq))))
  (type $21 (cont 20))
  (type $22 (cont 18))
  (type $23 (func (result (ref 19) (ref 21))))
  (type $24 (func (result (ref 11) (ref 10))))
  (type $25 (func (param (ref 21)) (result (ref null eq))))
  (type $26 (func (param (ref null struct)) (result (ref null none))))
  (type $27 (func (param i64 (ref null struct)) (result (ref null eq))))
  (type $28
    (func
      (param (ref null 6) (ref null eq) (ref null struct))
      (result (ref null none))
    )
  )
  (type $29
    (func (param (ref null none) (ref 19) (ref null struct)) (result (ref null 6)))
  )
  (type $30 (func (param i64 (ref null struct)) (result (ref null none))))
  (type $31 (func (param (ref null struct)) (result i64)))
  (type $32 (func (param (ref null struct)) (result (ref null 6))))
  (type $33 (struct (field (ref 26)) (field (ref null struct))))
  (type $34 (func (param (ref 33) (ref null struct)) (result i64)))
  (type $35 (struct (field (ref 31)) (field (ref null struct))))
  (type $36 (func (param (ref null 6) (ref null struct)) (result (ref null eq))))
  (type $37 (func (param i64 i64 (ref null struct)) (result (ref 1))))
  (type $38 (struct (field (ref null eq)) (field (ref null eq))))
  (type $39 (func (param (ref 1) (ref null struct)) (result (ref null none))))
  (type $40 (struct (field (ref 1))))
  (type $41 (func (param i64 (ref null struct)) (result i64)))
  (type $42 (func (param i64) (result i64)))
  (type $43 (func (param (ref 1)) (result (ref null none))))
  (type $44 (func (param i64 i64) (result (ref 1))))
  (type $45 (func (param (ref 33)) (result i64)))
  (type $46 (func (param i64) (result (ref null none))))
  (type $47 (func (param (ref 11)) (result (ref null eq))))
  (type $48 (func (result (ref 6))))
  (type $49 (func (param (ref 19)) (result (ref 6))))
  (import "wizeng" "puta" (func $0 (type 15)))
  (import "wizeng" "putc" (func $1 (type 16)))
  (global (export "p") (mut (ref null 6)) (struct.new_default 6))
  (global (export "_init_result") (mut i64) (i64.const 0))
  (global (mut i64) (i64.const 0))
  (global (mut (ref null 14)) (ref.null 14))
  (global (ref 18) (ref.func $6))
  (global (ref 31) (ref.func $9))
  (global (ref 26) (ref.func $15))
  (global (ref 18) (ref.func $20))
  (global (ref 7) (ref.func $22))
  (global (ref 18) (ref.func $24))
  (func $2 (type 26) (ref.null none))
  (func $3 (type 27) (local i64 (ref 1) (ref 1) (ref null 6) (ref null 6) (ref null none) i64 i64)
    (loop (result (ref null eq))
      (local.get 0)
      (local.set 2)
      (ref.null none)
      (call $21)
      (call $4)
      (ref.cast (ref 1))
      (local.set 3)
      (local.get 3)
      (local.set 4)
      (block (result (ref null eq))
        (block
          (block
            (block (local.get 4) (struct.get 1 0) (br_table 1 2 0 2))
            (local.get 4)
            (struct.get 1 1)
            (ref.cast (ref 4))
            (struct.get 4 0)
            (local.set 8)
            (local.get 8)
            (local.set 9)
            (local.get 2)
            (local.get 9)
            (i64.add)
            (ref.null none)
            (local.set 1)
            (local.set 0)
            (call $21)
            (br 3)
            (br 2)
          )
          (local.get 4)
          (struct.get 1 1)
          (ref.cast (ref 6))
          (local.set 5)
          (local.get 5)
          (local.set 6)
          (local.get 6)
          (i32.const 1)
          (local.get 2)
          (struct.new 4)
          (struct.new 1)
          (ref.null none)
          (call $21)
          (call $5)
          (local.set 7)
          (local.get 2)
          (ref.null none)
          (local.set 1)
          (local.set 0)
          (call $21)
          (br 2)
          (br 1)
        )
        (unreachable)
      )
    )
  )
  (func $4 (type 18) (local (ref 11) (ref 2))
    (suspend 1)
    (struct.get 6 1)
    (ref.cast (ref 11))
    (local.tee 1)
    (block (result (ref 2))
      (local.get 1)
      (struct.get 11 2)
      (br_on_non_null 0)
      (loop (result (ref 2))
        (block (result (ref 11))
          (loop (result (ref 11))
            (local.get 1)
            (local.get 1)
            (struct.get 11 1)
            (br_on_null 1)
            (local.tee 2)
            (struct.get 2 1)
            (struct.set 11 1)
            (local.get 1)
            (local.get 2)
            (struct.get 2 0)
            (local.get 1)
            (struct.get 11 2)
            (struct.new 2)
            (struct.set 11 2)
            (br 0)
          )
        )
        (struct.get 11 2)
        (br_on_non_null 1)
        (local.get 1)
        (i32.const 1)
        (struct.set 11 0)
        (suspend 2)
        (br 0)
      )
    )
    (local.tee 2)
    (struct.get 2 1)
    (struct.set 11 2)
    (local.get 2)
    (struct.get 2 0)
  )
  (func $5 (type 28) (local (ref 11))
    (block (result (ref 11))
      (local.get 0)
      (struct.get 6 1)
      (br_on_cast 0 (ref null eq) (ref 11))
      (drop)
      (ref.null none)
      (return)
    )
    (local.tee 3)
    (i32.const 0)
    (struct.set 11 0)
    (local.get 3)
    (local.get 1)
    (local.get 3)
    (struct.get 11 1)
    (struct.new 2)
    (struct.set 11 1)
    (ref.null none)
  )
  (func $6 (type 18) (i64.const 0) (ref.null none) (call $21) (return_call 3))
  (func $7 (type 29) (local.get 1) (suspend 0))
  (func $8 (type 30) (local i64)
    (local.get 0)
    (local.set 2)
    (global.get 0)
    (i32.const 2)
    (local.get 2)
    (struct.new 4)
    (struct.new 1)
    (ref.null none)
    (call $21)
    (return_call 5)
  )
  (func $9 (type 31) (local (ref null 6) (ref null none) (ref 1) (ref 1) i64 i64)
    (ref.null none)
    (call $21)
    (call $10)
    (local.set 1)
    (global.get 0)
    (i32.const 0)
    (local.get 1)
    (struct.new 1)
    (ref.null none)
    (call $21)
    (call $5)
    (local.set 2)
    (ref.null none)
    (call $21)
    (call $4)
    (ref.cast (ref 1))
    (local.set 3)
    (local.get 3)
    (local.set 4)
    (local.get 4)
    (struct.get 1 1)
    (ref.cast (ref 4))
    (struct.get 4 0)
    (local.set 5)
    (local.get 5)
    (local.set 6)
    (local.get 6)
  )
  (func $10 (type 32) (suspend 1))
  (func $11 (type 34) (local (ref 33) (ref null none))
    (local.get 0)
    (local.set 2)
    (local.get 2)
    (struct.get 33 1)
    (local.get 2)
    (struct.get 33 0)
    (call $21)
    (call_ref 26)
    (local.set 3)
    (ref.null none)
    (call $21)
    (call $2)
    (ref.func $24)
    (ref.func $9)
    (ref.null none)
    (struct.new 35)
    (struct.new 19)
    (ref.null none)
    (call $21)
    (call $7)
    (ref.null none)
    (call $21)
    (call $12)
    (ref.cast (ref 4))
    (struct.get 4 0)
  )
  (func $12 (type 36)
    (local.get 0)
    (struct.get 6 1)
    (br_on_cast_fail 0 (ref null eq) (ref 11))
    (suspend 3)
  )
  (func $13 (type 37) (local i64 i64 (ref 1))
    (local.get 1)
    (local.set 3)
    (local.get 0)
    (local.set 4)
    (local.get 4)
    (i64.const 0)
    (i64.eq)
    (if (result (ref 1))
      (then (i32.const 3) (local.get 3) (struct.new 4) (struct.new 1))
      (else
        (local.get 4)
        (i64.const 1)
        (i64.sub)
        (local.get 3)
        (i64.const 1)
        (i64.add)
        (ref.null none)
        (call $21)
        (call $13)
        (local.set 5)
        (i32.const 4)
        (local.get 5)
        (local.get 5)
        (struct.new 38)
        (struct.new 1)
      )
    )
  )
  (func $14 (type 39) (local (ref 1) (ref 1) i64 i64 (ref 38) (ref 1) (ref 1) (ref 1) (ref 1) (ref null none))
    (loop (result (ref null none))
      (local.get 0)
      (local.set 2)
      (local.get 2)
      (local.set 3)
      (block (result (ref null none))
        (block
          (block
            (block (local.get 3) (struct.get 1 0) (br_table 2 2 2 1 0 2))
            (local.get 3)
            (struct.get 1 1)
            (ref.cast (ref 38))
            (local.set 6)
            (local.get 6)
            (struct.get 38 0)
            (ref.cast (ref 1))
            (local.set 7)
            (local.get 6)
            (struct.get 38 1)
            (ref.cast (ref 1))
            (local.set 8)
            (local.get 8)
            (local.set 9)
            (local.get 7)
            (local.set 10)
            (local.get 10)
            (ref.null none)
            (call $21)
            (call $14)
            (local.set 11)
            (local.get 9)
            (ref.null none)
            (local.set 1)
            (local.set 0)
            (call $21)
            (br 3)
            (br 2)
          )
          (local.get 3)
          (struct.get 1 1)
          (ref.cast (ref 4))
          (struct.get 4 0)
          (local.set 4)
          (local.get 4)
          (local.set 5)
          (local.get 5)
          (ref.null none)
          (call $21)
          (return_call 8)
          (br 1)
        )
        (unreachable)
      )
    )
  )
  (func $15 (type 26) (local (ref 40))
    (local.get 0)
    (ref.cast (ref 40))
    (local.set 1)
    (local.get 1)
    (struct.get 40 0)
    (ref.null none)
    (call $21)
    (return_call 14)
  )
  (func $16 (type 41) (local i64 (ref 1))
    (local.get 0)
    (local.set 2)
    (local.get 2)
    (i64.const 0)
    (ref.null none)
    (call $21)
    (call $13)
    (local.set 3)
    (ref.func $15)
    (local.get 3)
    (struct.new 40)
    (struct.new 33)
    (ref.null none)
    (call $21)
    (return_call 11)
  )
  (func $17 (type 0) (local (ref null none))
    (ref.null none)
    (call $21)
    (call $2)
    (local.set 0)
    (local.get 0)
    (ref.func $20)
    (ref.func $6)
    (ref.null none)
    (struct.new 19)
    (struct.new 19)
    (ref.null none)
    (call $21)
    (call $7)
    (global.set 0)
    (i64.const 20)
    (ref.null none)
    (call $21)
    (call $16)
    (global.set 1)
  )
  (func $20 (type 18) (local (ref 19))
    (local.get 0)
    (ref.cast (ref 19))
    (local.set 1)
    (local.get 1)
    (struct.get 19 1)
    (local.get 1)
    (struct.get 19 0)
    (call_ref 18)
  )
  (func $21 (type 0)
    (global.get 2)
    (i64.eqz)
    (if
      (then (suspend 2))
      (else (global.get 2) (i64.const 1) (i64.sub) (global.set 2))
    )
  )
  (func $22 (type 7)
    (call $17)
    (block
      (loop
        (block (result (ref null eq))
          (global.get 3)
          (br_on_null 2)
          (struct.get 14 0)
          (global.get 3)
          (struct.get 14 1)
          (global.set 3)
          (struct.get 6 1)
          (br_on_cast_fail 0 (ref null eq) (ref 11))
          (suspend 3)
        )
        (drop)
        (br 0)
      )
    )
    (ref.null none)
  )
  (func $23 (export "main") (type 0) (local i32 (ref 13) (ref 13) (ref null eq) (ref 21) (ref 19) (ref 8) (ref 10) (ref 11))
    (i32.const 1)
    (local.set 0)
    (i32.const 0)
    (i32.const 0)
    (ref.null 2)
    (ref.null 2)
    (ref.null 12)
    (struct.new 11)
    (struct.new 6)
    (ref.func $22)
    (cont.new 8)
    (ref.null 13)
    (struct.new 13)
    (local.tee 1)
    (local.set 2)
    (block
      (loop
        (block
          (block (type 24)
            (block (result (ref 8))
              (block (type 23)
                (block (result (ref null eq))
                  (block (result (ref 21))
                    (local.get 2)
                    (struct.get 13 0)
                    (struct.get 6 1)
                    (ref.cast (ref 11))
                    (struct.get_u 11 0)
                    (br_if 5)
                    (i64.const 99)
                    (global.set 2)
                    (local.get 2)
                    (struct.get 13 1)
                    (resume 8 (on 1 0) (on 0 2) (on 2 3) (on 3 4))
                    (br 1)
                  )
                  (loop (type 25)
                    (local.set 4)
                    (local.get 2)
                    (struct.get 13 0)
                    (local.get 4)
                    (resume 21 (on 1 0) (on 0 2) (on 2 3) (on 3 4))
                    (br 1)
                  )
                )
                (local.set 3)
                (local.get 2)
                (struct.get 13 0)
                (struct.get 6 1)
                (ref.cast (ref 11))
                (local.set 8)
                (block (result (ref 13))
                  (loop (result (ref 13))
                    (local.get 2)
                    (local.get 8)
                    (struct.get 11 3)
                    (br_on_null 1)
                    (struct.get 12 0)
                    (local.get 3)
                    (local.get 8)
                    (struct.get 11 3)
                    (ref.as_non_null)
                    (struct.get 12 1)
                    (cont.bind 10 8)
                    (local.get 2)
                    (struct.get 13 2)
                    (struct.new 13)
                    (struct.set 13 2)
                    (local.get 8)
                    (local.get 8)
                    (struct.get 11 3)
                    (ref.as_non_null)
                    (struct.get 12 2)
                    (struct.set 11 3)
                    (br 0)
                  )
                )
                (struct.get 13 0)
                (local.get 3)
                (struct.set 6 1)
                (local.get 2)
                (ref.null 8)
                (struct.set 13 1)
                (br 3)
              )
              (local.set 4)
              (local.set 5)
              (local.get 2)
              (local.get 0)
              (local.get 0)
              (i32.const 1)
              (i32.add)
              (local.set 0)
              (i32.const 0)
              (ref.null 2)
              (ref.null 2)
              (ref.null 12)
              (struct.new 11)
              (local.tee 8)
              (struct.new 6)
              (local.get 5)
              (struct.get 19 1)
              (local.get 5)
              (struct.get 19 0)
              (cont.new 22)
              (cont.bind 22 8)
              (local.get 2)
              (struct.get 13 2)
              (struct.new 13)
              (struct.set 13 2)
              (local.get 2)
              (local.get 2)
              (struct.get 13 2)
              (struct.get 13 0)
              (local.get 4)
              (cont.bind 21 8)
              (struct.set 13 1)
              (br 3)
            )
            (local.set 6)
            (local.get 2)
            (local.get 6)
            (struct.set 13 1)
            (br 1)
          )
          (local.set 7)
          (local.set 8)
          (local.get 2)
          (ref.null 8)
          (struct.set 13 1)
          (local.get 8)
          (local.get 2)
          (struct.get 13 0)
          (local.get 7)
          (local.get 8)
          (struct.get 11 3)
          (struct.new 12)
          (struct.set 11 3)
          (br 0)
        )
        (loop
          (block
            (loop
              (block
                (local.get 2)
                (struct.get 13 2)
                (br_on_null 2)
                (struct.get 13 1)
                (br_on_null 0)
                (local.get 2)
                (struct.get 13 2)
                (ref.as_non_null)
                (local.set 2)
                (br 4)
              )
              (local.get 2)
              (local.get 2)
              (struct.get 13 2)
              (struct.get 13 2)
              (struct.set 13 2)
              (br 0)
            )
          )
          (local.get 1)
          (local.tee 2)
          (struct.get 13 1)
          (ref.is_null)
          (i32.eqz)
          (br_if 1)
          (local.get 1)
          (struct.get 13 0)
          (struct.get 6 1)
          (ref.test (ref 11))
          (i32.eqz)
          (br_if 2)
          (local.get 1)
          (struct.get 13 2)
          (ref.is_null)
          (i32.eqz)
          (br_if 0)
          (loop (br 0))
        )
      )
    )
  )
  (func $24 (type 18) (local (ref 35))
    (local.get 0)
    (ref.cast (ref 35))
    (local.set 1)
    (local.get 1)
    (struct.get 35 1)
    (local.get 1)
    (struct.get 35 0)
    (call_ref 31)
    (struct.new 4)
  )
  (func $25 (export "main'") (type 42)
    (local.get 0)
    (ref.null none)
    (return_call 16)
  )
  (func $26 (export "walk_tree") (type 43)
    (local.get 0)
    (ref.null none)
    (return_call 14)
  )
  (func $27 (export "build_tree") (type 44)
    (local.get 0)
    (local.get 1)
    (ref.null none)
    (return_call 13)
  )
  (func $28 (export "run") (type 45)
    (local.get 0)
    (ref.null none)
    (return_call 11)
  )
  (func $29 (export "yield") (type 46)
    (local.get 0)
    (ref.null none)
    (return_call 8)
  )
  (tag (type 49))
  (tag (type 48))
  (tag (type 0))
  (tag (type 47))
)
