;; Collections land at arbitrary points of the inline suspend sequence.
(module
  (type $f (func (result i32)))
  (type $c (cont $f))
  (type $fs (func (param i32) (result i32)))
  (type $cs (cont $fs))
  (type $s (struct (field i32)))
  (type $arr (array (mut i32)))
  (tag $t (param i32 (ref null $s)) (result i32))
  (global $seed (mut i32) (i32.const 12345))

  (func $rand (result i32)
    (global.set $seed (i32.xor (global.get $seed) (i32.shl (global.get $seed) (i32.const 13))))
    (global.set $seed (i32.xor (global.get $seed) (i32.shr_u (global.get $seed) (i32.const 17))))
    (global.set $seed (i32.xor (global.get $seed) (i32.shl (global.get $seed) (i32.const 5))))
    (global.get $seed)
  )
  (func $gen (param $n i32) (result i32)
    (local $acc i32)
    (loop $l
      (local.set $acc (i32.add (local.get $acc) (suspend $t (local.get $n) (struct.new $s (local.get $n)))))
      (local.set $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l (local.get $n))
    )
    (local.get $acc)
  )
  (elem declare func $gen)

  (func (export "main") (param $n i32) (result i32)
    (local $k (ref null $cs))
    (local $st (ref null $s))
    (local $i i32)
    (local $sum i32)
    (local $reply i32)
    (local.set $k (cont.new $cs (ref.func $gen)))
    (local.set $reply (local.get $n))
    (loop $l
      (block $h (result i32 (ref null $s) (ref null $cs))
        (return (i32.add (local.get $sum) (resume $cs (on $t $h) (local.get $reply) (local.get $k))))
      )
      (local.set $k)
      (local.set $st)
      (local.set $i)
      (drop (array.new_default $arr (i32.and (call $rand) (i32.const 255))))
      (local.set $sum (i32.add (local.get $sum) (struct.get $s 0 (local.get $st))))
      (local.set $reply (i32.const 1))
      (br $l)
    )
    (unreachable)
  )
)

(assert_return (invoke "main" (i32.const 25000000)) (i32.const 2512010336))
