(module
  (func $putc (import "wizeng" "putc") (param i32))
  (func $puti (import "wizeng" "puti") (param i32))
  
  (func (export "wasm:block:start(fid,pc)") (param i32 i32)
    (call $putc (i32.const 115))
    (call $puti (local.get 0))
    (call $putc (i32.const 43))
    (call $puti (local.get 1))
    (call $putc (i32.const 32))
  )
  (func (export "wasm:block:end(fid,pc,instr_count)") (param i32 i32 i32)
    (call $putc (i32.const 101))
    (call $puti (local.get 0))
    (call $putc (i32.const 43))
    (call $puti (local.get 1))
    (call $putc (i32.const 44))
    (call $puti (local.get 2))
    (call $putc (i32.const 10))
  )
)
