(module
  (func (export "main")
	(call $countdown1 (i32.const 5))
	(call $countdown2 (i32.const 7))
  )
  (func $countdown1 (param i32)
    (if (local.get 0)
      (then (call $countdown1 (i32.sub (local.get 0) (i32.const 1)))))
  )
  (func $countdown2 (param i32)
    (if (local.get 0)
      (then (call $countdown2 (i32.sub (local.get 0) (i32.const 1)))))
  )
)
