(module
  (global $a i32 (i32.const 0))
  (global $b (mut i64) (i64.const 1))
  (func $start (export "_start")
    (call $main)
  )
  (func $main (export "main")
    (local $y i32)
    (local.set $y (i32.const 10))
    (loop $l
      (call $foo)
      (call $bar)
      (call $foo)
      (call $baz)
      (call $foo)
      (call $foo)
      (call $foo)
      (call $bar)
      (call $bar)
      (call $foo)
      (local.tee $y (i32.sub (local.get $y) (i32.const 1)))
      (br_if $l)
    )
  )
  (func $foo
	(drop (global.get $a))
  )
  (func $bar
    (call $baz)
  )
  (func $baz
	(global.set $b (i64.const 123))
  )
)
