;; Test: suspended frames hold locals and operands of many value kinds, null and
;; non-null, which must survive compression and decompression.
(module
  (type $box (struct (field i32)))
  (type $arr (array i32))
  (type $fv (func))
  (type $cv (cont $fv))
  (type $fi (func (param i32)))
  (type $ci (cont $fi))

  (tag $yield)
  (tag $exn (param i32))
  (table $t 0 (ref null $cv))

  (func $id (param i32) (result i32) (local.get 0))
  (elem declare func $id $worker)

  ;; Holds many kinds of values across a suspension, then checks them all.
  (func $worker (param $x i32)
    (local $i31 i31ref) (local $any anyref) (local $eq eqref) (local $s (ref null $box))
    (local $a (ref null $arr)) (local $f funcref) (local $nf nullfuncref) (local $ext externref)
    (local $k (ref null $cv)) (local $nk nullcontref) (local $kr contref) (local $exn exnref)
    (local $nexn nullexnref) (local $none nullref) (local $l i64) (local $d f64) (local $v v128)
    (local.set $i31 (ref.i31 (local.get $x)))
    (local.set $any (struct.new $box (local.get $x)))
    (local.set $eq (ref.i31 (i32.add (local.get $x) (i32.const 1))))
    (local.set $s (struct.new $box (i32.add (local.get $x) (i32.const 2))))
    (local.set $a (array.new $arr (local.get $x) (i32.const 3)))
    (local.set $f (ref.func $id))
    (local.set $k (cont.new $cv (ref.func $worker_done)))
    (block $h (result i32 exnref)
      (try_table (catch_ref $exn $h) (throw $exn (local.get $x)))
      (unreachable))
    (local.set $exn)
    (drop)
    (local.set $l (i64.const -5))
    (local.set $d (f64.const 2.5))
    (local.set $v (i32x4.splat (local.get $x)))
    ;; Operands of several kinds are also live on the operand stack across the suspension.
    (ref.null func) (ref.null extern) (ref.i31 (i32.const 7)) (local.get $k)
    (suspend $yield)
    ;; Check operands.
    (if (ref.is_null) (then (unreachable)))
    (if (i32.ne (i31.get_u (ref.cast (ref i31))) (i32.const 7)) (then (unreachable)))
    (if (i32.eqz (ref.is_null)) (then (unreachable)))
    (if (i32.eqz (ref.is_null)) (then (unreachable)))
    ;; Check locals.
    (if (i32.ne (i31.get_u (ref.as_non_null (local.get $i31))) (local.get $x)) (then (unreachable)))
    (if (i32.ne (struct.get $box 0 (ref.cast (ref $box) (local.get $any))) (local.get $x)) (then (unreachable)))
    (if (i32.ne (i31.get_u (ref.cast (ref i31) (local.get $eq))) (i32.add (local.get $x) (i32.const 1))) (then (unreachable)))
    (if (i32.ne (struct.get $box 0 (local.get $s)) (i32.add (local.get $x) (i32.const 2))) (then (unreachable)))
    (if (i32.ne (array.get $arr (local.get $a) (i32.const 2)) (local.get $x)) (then (unreachable)))
    (if (i32.ne (call_ref $fi_i (local.get $x) (ref.cast (ref $fi_i) (local.get $f))) (local.get $x)) (then (unreachable)))
    (if (i32.eqz (ref.is_null (local.get $nf))) (then (unreachable)))
    (if (i32.eqz (ref.is_null (local.get $ext))) (then (unreachable)))
    (if (i32.eqz (ref.is_null (local.get $nk))) (then (unreachable)))
    (if (i32.eqz (ref.is_null (local.get $kr))) (then (unreachable)))
    (if (i32.eqz (ref.is_null (local.get $nexn))) (then (unreachable)))
    (if (i32.eqz (ref.is_null (local.get $none))) (then (unreachable)))
    (if (ref.is_null (local.get $exn)) (then (unreachable)))
    (if (i64.ne (local.get $l) (i64.const -5)) (then (unreachable)))
    (if (f64.ne (local.get $d) (f64.const 2.5)) (then (unreachable)))
    (if (i32.ne (i32x4.extract_lane 3 (local.get $v)) (local.get $x)) (then (unreachable)))
    ;; The held continuation still works.
    (resume $cv (local.get $k))
    (block $c (result i32)
      (try_table (catch $exn $c) (throw_ref (local.get $exn)))
      (unreachable))
    (if (i32.ne (local.get $x)) (then (unreachable)))
  )
  (type $fi_i (func (param i32) (result i32)))
  (func $worker_done)
  (elem declare func $worker_done)

  (func (export "main") (param $n i32) (result i32)
    (local $i i32) (local $k (ref null $cv))
    (drop (table.grow $t (ref.null $cv) (local.get $n)))
    (loop $create
      (block $h (result (ref $cv))
        (resume $ci (on $yield $h) (local.get $i) (cont.new $ci (ref.func $worker)))
        (unreachable)
      )
      (local.set $k)
      (table.set $t (local.get $i) (local.get $k))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $create (i32.lt_u (local.get $i) (local.get $n)))
    )
    (loop $finish
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (resume $cv (table.get $t (local.get $i)))
      (br_if $finish (local.get $i))
    )
    (local.get $n)
  )
)

(assert_return (invoke "main" (i32.const 1)) (i32.const 1))
(assert_return (invoke "main" (i32.const 1000)) (i32.const 1000))
