;; INNER_CALIBRATION = 185
(module
  (func $start (export "_start")
    (call $main)
  )
  (func $main (export "main")
    (local $y i32)
    (local $z i32)
    (local.set $y (i32.const __INNER_ITERATIONS__))
    (local.set $z (i32.const 10))
    (loop $l
      (call $rec1 (local.get $z))
      (local.tee $y (i32.sub (local.get $y) (i32.const 1)))
      (br_if $l)
    )
  )
  (func $rec1 (param i32)
    (br_if 0 (i32.le_s (local.get 0) (i32.const 0)))
    (call $rec2 (i32.sub (local.get 0) (i32.const 1)))
    (call $rec3 (i32.sub (local.get 0) (i32.const 2)))
  )
  (func $rec2 (param i32)
    (call $rec1 (local.get 0))
  )
  (func $rec3 (param i32)
    (call $rec1 (local.get 0))
  )
)
