;; INNER_CALIBRATION = 450
(module
 (func $main (export "main")
    (local $x i32)
    (local $y i32)

    (local.set $y (i32.const 1 (;$INNER_ITERATIONS;)))
    (loop $l
      (local.set $y (i32.sub (local.get $y) (i32.const 1)))
      (br_if $l (i32.eq (local.get $y) (i32.const 3)))
      (br_if $l (i32.eq (local.get $y) (i32.const 5)))
      (br_if $l (i32.eq (local.get $y) (i32.const 7)))
      (br_if $l (i32.eq (local.get $y) (i32.const 9)))
      (br_if $l (i32.eq (local.get $y) (i32.const 11)))
      (br_if $l (i32.eq (local.get $y) (i32.const 13)))
      (br_if $l (i32.eq (local.get $y) (i32.const 17)))
      (br_if $l (i32.eq (local.get $y) (i32.const 19)))
      (br_if $l (i32.eq (local.get $y) (i32.const 23)))
      (br_if $l (i32.eq (local.get $y) (i32.const 29)))
      (br_if $l (i32.eq (local.get $y) (i32.const 31)))
      (br_if $l (i32.eq (local.get $y) (i32.const 37)))
      (br_if $l (i32.eq (local.get $y) (i32.const 41)))
      (br_if $l (i32.eq (local.get $y) (i32.const 43)))
      (br_if $l (i32.eq (local.get $y) (i32.const 47)))
      (br_if $l (i32.eq (local.get $y) (i32.const 53)))
      (br_if $l (local.get $y))
    )
 )
 (export "_start" (func $main))
)
