;; INNER_CALIBRATION = 7000
(module
  (func $start (export "_start")
    (call $main)
  )
  (func $main (export "main")
    (local $y i32)
    (local.set $y (i32.const 1 (;$INNER_ITERATIONS;)))
    (loop $l
      (i32.const 42)
      (call $foo (i32.const 41))
      (call $foo (i32.const 31))
      (call $foo (i32.const 21))
      (call $foo (i32.const 11))
      (call $foo (i32.const -11))
      (call $foo (i32.const -12))
      (call $foo (i32.const -13))
      (call $foo (i32.const -14))
      (call $foo (i32.const -15))
      (call $foo (i32.const -16))
      drop
      (local.tee $y (i32.sub (local.get $y) (i32.const 1)))
      (br_if $l)
    )
  )
  (func $foo (param i32 i32) (result i32)
    (if (result i32) (i32.le_s (local.get 0) (local.get 1))
      (then (i32.const 11))
      (else (i32.const 22)))
  )
)
