(module
  (func $start (export "_start")
    (call $main)
  )
  (func $main (export "main")
    (local $y i32)
    (local $z1 i32)
    (local $z2 i32)
    (local $z3 i32)
    (local $z4 i32)
    (local $z5 i32)
    (local $z6 i32)
    (local $z7 i32)
    (local $z8 i32)
    (local $z9 i32)
    (local $zA i32)
    (local.set $y (i32.const 10000000))
    (loop $l
      (call $foo)
      (call $foo)
      (call $foo)
      (call $foo)
      (call $foo)
      (call $foo)
      (call $foo)
      (call $foo)
      (call $foo)
      (call $foo)
      (local.tee $y (i32.sub (local.get $y) (i32.const 1)))
      (br_if $l)
    )
  )
  (func $foo
  )
)
