(module
  (func $start (export "_start")
    (call $main)
  )
  (func $main (export "main")
    (local $y i32)
    (local.set $y (i32.const 10000000))
    (loop $l
      (call $foo)
      (call $foo)
      (call $foo)
      (call $foo)
      (call $foo)
      (call $foo)
      (call $foo)
      (call $foo)
      (call $foo)
      (call $foo)
      (local.tee $y (i32.sub (local.get $y) (i32.const 1)))
      (br_if $l)
    )
  )
  (func $foo
  )
)
