;; INNER_CALIBRATION = 173
;; br_on_cast and br_on_cast_fail: a taken cast branch, a not-taken fail branch, and a
;; three-way dispatch cascade that succeeds on the last case.
(module
  (type $x (struct (field i32)))
  (type $y (struct (field i64)))
  (type $z (struct (field f64)))
  (func $main (export "main")
    (local $y i32)
    (local $ox (ref $x))
    (local $oz (ref $z))
    (local.set $ox (struct.new $x (i32.const 1)))
    (local.set $oz (struct.new $z (f64.const 3.0)))
    (local.set $y (i32.const 1 (;$REPEAT;)))
    (loop $l
      (call $cast_taken (local.get $ox) (i32.const 1 (;$INNER_ITERATIONS;)))
      (call $cast_fail_not_taken (local.get $ox) (i32.const 1 (;$INNER_ITERATIONS;)))
      (call $dispatch3 (local.get $oz) (i32.const 1 (;$INNER_ITERATIONS;)))
      (local.tee $y (i32.sub (local.get $y) (i32.const 1)))
      (br_if $l)
    )
  )
  ;; br_on_cast that branches, since the value is an $x.
  (func $cast_taken (param $v anyref) (param $n i32)
    (loop $l
      (block $no
        (block $yes (result (ref $x))
          (br_on_cast $yes anyref (ref $x) (local.get $v))
          (drop)
          (br $no)
        )
        (drop)
      )
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
  )
  ;; br_on_cast_fail that does not branch, since the value is an $x.
  (func $cast_fail_not_taken (param $v anyref) (param $n i32)
    (loop $l
      (block $no (result anyref)
        (br_on_cast_fail $no anyref (ref $x) (local.get $v))
      )
      (drop)
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
  )
  ;; A cascade of three casts to unrelated types, of which the last succeeds.
  (func $dispatch3 (param $v anyref) (param $n i32)
    (loop $l
      (block $done
        (block $isz (result (ref $z))
          (block $isy (result (ref $y))
            (block $isx (result (ref $x))
              (br_on_cast $isx anyref (ref $x) (local.get $v))
              (br_on_cast $isy anyref (ref $y))
              (br_on_cast $isz anyref (ref $z))
              (drop)
              (br $done)
            )
            (drop)
            (br $done)
          )
          (drop)
          (br $done)
        )
        (drop)
      )
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
  )
)
