;; INNER_CALIBRATION = 157
;; call_ref and return_call_ref: calls through a typed function reference held in a local,
;; loaded from a struct field (like a vtable), and a tail call through a reference.
(module
  (type $ft (func (param i32) (result i32)))
  (type $obj (struct (field (ref $ft))))
  (global $g (ref $ft) (ref.func $inc))
  (func $inc (type $ft) (i32.add (local.get 0) (i32.const 1)))
  (func $main (export "main")
    (local $y i32)
    (local.set $y (i32.const 1 (;$REPEAT;)))
    (loop $l
      (drop (call $via_local (ref.func $inc) (i32.const 1 (;$INNER_ITERATIONS;))))
      (drop (call $via_field (struct.new $obj (ref.func $inc)) (i32.const 1 (;$INNER_ITERATIONS;))))
      (drop (call $via_tail (i32.const 1 (;$INNER_ITERATIONS;))))
      (local.tee $y (i32.sub (local.get $y) (i32.const 1)))
      (br_if $l)
    )
  )
  (func $via_local (param $f (ref $ft)) (param $n i32) (result i32)
    (local $acc i32)
    (loop $l
      (local.set $acc (call_ref $ft (local.get $acc) (local.get $f)))
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
    (local.get $acc)
  )
  (func $via_field (param $o (ref $obj)) (param $n i32) (result i32)
    (local $acc i32)
    (loop $l
      (local.set $acc (call_ref $ft (local.get $acc) (struct.get $obj 0 (local.get $o))))
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
    (local.get $acc)
  )
  (func $tail (param i32) (result i32)
    (return_call_ref $ft (local.get 0) (global.get $g))
  )
  (func $via_tail (param $n i32) (result i32)
    (local $acc i32)
    (loop $l
      (local.set $acc (call $tail (local.get $acc)))
      (local.tee $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l)
    )
    (local.get $acc)
  )
)
