(module
  (type (func)) (type (func)) (type (func)) (type (func))
  (type (func)) (type (func)) (type (func)) (type (func))
  (type (func)) (type (func)) (type (func)) (type (func))
  (type (func)) (type (func)) (type (func)) (type (func))
  (type (func)) (type (func)) (type (func)) (type (func))
  (type (func)) (type (func)) (type (func)) (type (func))
  (type (func)) (type (func)) (type (func)) (type (func))
  (type (func)) (type (func)) (type (func)) (type (func))
  (type (func)) (type (func)) (type (func)) (type (func))
  (type (func)) (type (func)) (type (func)) (type (func))
  (type (func)) (type (func)) (type (func)) (type (func))
  (type (func)) (type (func)) (type (func)) (type (func))
  (type (func)) (type (func)) (type (func)) (type (func))
  (type (func)) (type (func)) (type (func)) (type (func))
  (type (func)) (type (func)) (type (func)) (type (func))
  (type (func)) (type (func)) (type (func)) (type (func))
  (type (func))
  (type $res (func (result i32 i32)))
  (func (export "main")
     (block (type $res)
        (return))
     (drop)
     (drop)
  )
)
(assert_return (invoke "main"))
