(module
  (type $0 (func (result i32)))
  (memory $0 3 3)
  (func $0
    (type 0)
    (local i32 i32 i32 i32 i32 i32 i32 i32)
    (i32.const 65_536)
    (i32.eqz)
    (if (then (unreachable)) (else))
    (i32.const 0)
    (i32.load offset=65_540)
    (local.set 7)
    (i32.const 0)
    (local.set 0)
    (loop
      (local.get 0)
      (local.get 7)
      (i32.lt_s)
      (if
        (then
          (i32.const 65_536)
          (local.get 0)
          (i32.const 4)
          (i32.mul)
          (i32.const 8)
          (i32.add)
          (i32.add)
          (i32.load)
          (local.set 3)
          (i32.const 65_536)
          (i32.eqz)
          (if (then (unreachable)) (else))
          (i32.const 0)
          (i32.load offset=65_540)
          (local.set 6)
          (i32.const 0)
          (local.set 1)
          (block
            (loop
              (local.get 1)
              (local.get 6)
              (i32.lt_s)
              (if
                (then
                  (i32.const 65_536)
                  (local.get 1)
                  (i32.const 4)
                  (i32.mul)
                  (i32.const 8)
                  (i32.add)
                  (i32.add)
                  (i32.load)
                  (local.tee 2)
                  (i32.eqz)
                  (if
                    (then)
                    (else
                      (local.get 2)
                      (i32.const -1)
                      (i32.eq)
                      (if
                        (then
                          (i32.const 0)
                          (local.get 3)
                          (i32.sub)
                          (local.set 5)
                        )
                        (else
                          (local.get 3)
                          (local.get 2)
                          (i32.div_s)
                          (local.set 5)
                          (br 0)
                        )
                      )
                      (local.get 5)
                      (i32.const 8)
                      (i32.shr_u)
                      (i32.eqz)
                      (i32.const 1)
                      (i32.xor)
                      (if (then (unreachable)) (else))
                      (local.get 5)
                      (i32.const 255)
                      (i32.and)
                      (local.tee 4)
                      (local.get 3)
                      (i32.const 8)
                      (i32.shr_u)
                      (i32.eqz)
                      (i32.const 1)
                      (i32.xor)
                      (if (then (unreachable)) (else))
                      (local.get 3)
                      (i32.const 255)
                      (i32.and)
                      (local.get 2)
                      (i32.const 8)
                      (i32.shr_u)
                      (i32.eqz)
                      (i32.const 1)
                      (i32.xor)
                      (if (then (unreachable)) (else))
                      (local.get 2)
                      (i32.const 255)
                      (i32.and)
                      (i32.div_u)
                      (i32.const 255)
                      (i32.and)
                      (i32.eq)
                      (if
                        (then
                          (local.get 3)
                          (i32.const 8)
                          (i32.shr_u)
                          (i32.eqz)
                          (i32.const 1)
                          (i32.xor)
                          (if (then (unreachable)) (else))
                          (local.get 4)
                          (local.get 3)
                          (i32.const 255)
                          (i32.and)
                          (local.get 2)
                          (i32.const 8)
                          (i32.shr_u)
                          (i32.eqz)
                          (i32.const 1)
                          (i32.xor)
                          (if (then (unreachable)) (else))
                          (local.get 2)
                          (i32.const 255)
                          (i32.and)
                          (i32.div_u)
                          (i32.const 255)
                          (i32.and)
                          (i32.eq)
                          (br_if 1)
                          (local.get 3)
                          (i32.const 8)
                          (i32.shl)
                          (local.get 2)
                          (i32.or)
                          (return)
                        )
                        (else
                          (local.get 3)
                          (i32.const 8)
                          (i32.shl)
                          (local.get 2)
                          (i32.or)
                          (return)
                        )
                      )
                    )
                  )
                  (local.get 1)
                  (i32.const 1)
                  (i32.add)
                  (local.set 1)
                  (br 1)
                )
                (else (br 2))
              )
            )
          )
          (local.get 0)
          (i32.const 1)
          (i32.add)
          (local.set 0)
          (br 1)
        )
        (else (i32.const 1_000_000) (return))
      )
    )
    (unreachable)
  )
  (export "main" (func 0))
  (export "memory" (memory 0))
  (data $0
    (i32.const 65_536)
    "\11\00\00\00\0f\00\00\00\00\00\00\00\01\00\00\00"
    "\02\00\00\00\03\00\00\00\04\00\00\00\0b\00\00\00"
    "\11\00\00\00\37\00\00\00\39\00\00\00\65\00\00\00"
    "\bf\00\00\00\c9\00\00\00\fd\00\00\00\fe\00\00\00"
    "\ff\00\00\00"
  )
)
(assert_return (invoke "main") (i32.const 1_000_000))
