(module
  (table funcref (elem $main))
  (type $v_i (func (result i32)))
  (func $main (export "main") (param i32) (result i32)
    (call_indirect (type $v_i) (local.get 0))
  )
)
(assert_trap (invoke "main" (i32.const 0)) "")
(assert_trap (invoke "main" (i32.const 1)) "")
(assert_trap (invoke "main" (i32.const 2)) "")
(assert_trap (invoke "main" (i32.const 4)) "")
(assert_trap (invoke "main" (i32.const 5)) "")
(assert_trap (invoke "main" (i32.const 6)) "")
(assert_trap (invoke "main" (i32.const -1)) "")
