(module
  (func (export "main") (param i32) (result i32)
    (local.get 0)
    (local.get 0)
    (i32.const 1)
    (select)
  )
)
(assert_return (invoke "main" (i32.const 9)) (i32.const 9))
(assert_return (invoke "main" (i32.const 777)) (i32.const 777))
