(module
  (func (export "main")
    (call $demo (i32.const 0))
    (call $demo (i32.const 1))
    (call $demo (i32.const 2))
    (call $demo (i32.const 3))
    (call $demo (i32.const 4))
    (drop (call $diamond (i32.const 0)))
    (drop (call $diamond (i32.const 1)))
    (drop (call $double_diamond (i32.const 0) (i32.const 0)))
    (drop (call $double_diamond (i32.const 0) (i32.const 1)))
    (drop (call $double_diamond (i32.const 1) (i32.const 0)))
    (drop (call $double_diamond (i32.const 1) (i32.const 1)))
    (drop (call $nested_if (i32.const 0) (i32.const 0)))
    (drop (call $nested_if (i32.const 0) (i32.const 1)))
    (drop (call $nested_if (i32.const 1) (i32.const 0)))
    (drop (call $nested_if (i32.const 1) (i32.const 1)))
    (drop (call $triple_diamond (i32.const 0) (i32.const 0) (i32.const 0)))
    (drop (call $triple_diamond (i32.const 0) (i32.const 0) (i32.const 1)))
    (drop (call $triple_diamond (i32.const 0) (i32.const 1) (i32.const 0)))
    (drop (call $triple_diamond (i32.const 0) (i32.const 1) (i32.const 1)))
    (drop (call $triple_diamond (i32.const 1) (i32.const 0) (i32.const 0)))
    (drop (call $triple_diamond (i32.const 1) (i32.const 0) (i32.const 1)))
    (drop (call $triple_diamond (i32.const 1) (i32.const 1) (i32.const 0)))
    (drop (call $triple_diamond (i32.const 1) (i32.const 1) (i32.const 1)))
    (call $wide_switch (i32.const 0))
    (call $wide_switch (i32.const 1))
    (call $wide_switch (i32.const 2))
    (call $wide_switch (i32.const 3))
    (call $wide_switch (i32.const 4))
    (call $wide_switch (i32.const 5))
    (call $wide_switch (i32.const 6))
    (call $wide_switch (i32.const 7))
    (drop (call $loop_sum (i32.const 5)))
    (drop (call $loop_with_if (i32.const 6)))
    (drop (call $unconditional_br (i32.const 0)))
    (drop (call $unconditional_br (i32.const 1)))
    (drop (call $br_merge (i32.const 0)))
    (drop (call $br_merge (i32.const 1)))
    (drop (call $br_merge (i32.const 1)))
  )
  (func $demo (export "demo") (param $x i32)
    (block $L3
      (block $L2
        (block $L1
          (block $L0
            (br_table $L0 $L1 $L2 $L3 (local.get $x))
          )
          (return)
        )
        (return)
      )
      (return)
    )
    (return)
  )
  (func $diamond (export "diamond") (param $x i32) (result i32)
    (if (result i32) (local.get $x)
      (then (i32.const 1))
      (else (i32.const 2))
    )
  )
  (func $double_diamond (export "double_diamond") (param $x i32) (param $y i32) (result i32)
    (local $r i32)
    (if (local.get $x)
      (then (local.set $r (i32.const 1)))
      (else (local.set $r (i32.const 2)))
    )
    (if (result i32) (local.get $y)
      (then (i32.add (local.get $r) (i32.const 10)))
      (else (i32.add (local.get $r) (i32.const 20)))
    )
  )
  ;; nested if: a branch nested entirely inside the "then" arm of an outer branch.
  ;; 3 distinct paths: x=0 (else) -> 1 path; x=1,y=0 -> 1 path; x=1,y=1 -> 1 path.
  (func $nested_if (export "nested_if") (param $x i32) (param $y i32) (result i32)
    (if (result i32) (local.get $x)
      (then
        (if (result i32) (local.get $y)
          (then (i32.const 1))
          (else (i32.const 2))
        )
      )
      (else (i32.const 3))
    )
  )
  ;; three sequential ifs sharing one running value: 2^3 = 8 distinct paths.
  (func $triple_diamond (export "triple_diamond") (param $x i32) (param $y i32) (param $z i32) (result i32)
    (local $r i32)
    (if (local.get $x)
      (then (local.set $r (i32.const 1)))
      (else (local.set $r (i32.const 2)))
    )
    (if (local.get $y)
      (then (local.set $r (i32.add (local.get $r) (i32.const 10))))
      (else (local.set $r (i32.add (local.get $r) (i32.const 20))))
    )
    (if (result i32) (local.get $z)
      (then (i32.add (local.get $r) (i32.const 100)))
      (else (i32.add (local.get $r) (i32.const 200)))
    )
  )
  ;; br_table with 6 labels (5 indexed + 1 default): indices 0-4 map 1:1, index >= 5 collapses
  ;; onto the default (L5). Exercises a wider dispatch chain than $demo's 4-label table.
  (func $wide_switch (export "wide_switch") (param $x i32)
    (block $L5
      (block $L4
        (block $L3
          (block $L2
            (block $L1
              (block $L0
                (br_table $L0 $L1 $L2 $L3 $L4 $L5 (local.get $x))
              )
              (return)
            )
            (return)
          )
          (return)
        )
        (return)
      )
      (return)
    )
    (return)
  )
  ;; simple counting loop (has a backedge) - path numbering must detect this and skip
  ;; instrumentation entirely rather than crash or produce bogus counts.
  (func $loop_sum (export "loop_sum") (param $n i32) (result i32)
    (local $i i32) (local $acc i32)
    (local.set $i (i32.const 0))
    (block $exit
      (loop $top
        (br_if $exit (i32.ge_s (local.get $i) (local.get $n)))
        (local.set $acc (i32.add (local.get $acc) (local.get $i)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $top)
      )
    )
    (local.get $acc)
  )
  ;; loop containing a nested if (still has a backedge despite the extra branching) - checks
  ;; that backedge detection isn't fooled by nested acyclic control flow inside a cyclic one.
  (func $loop_with_if (export "loop_with_if") (param $n i32) (result i32)
    (local $i i32)
    (local.set $i (i32.const 0))
    (block $exit
      (loop $top
        (br_if $exit (i32.ge_s (local.get $i) (local.get $n)))
        (if (i32.rem_s (local.get $i) (i32.const 2))
          (then (local.set $i (i32.add (local.get $i) (i32.const 2))))
          (else (local.set $i (i32.add (local.get $i) (i32.const 1))))
        )
        (br $top)
      )
    )
    (local.get $i)
  )
  ;; unconditional br skipping over dead code: no runtime decision at all, so this should be
  ;; a single-path function (no chord/tree edge needs a probe, same as $main).
  (func $unconditional_br (export "unconditional_br") (param $x i32) (result i32)
    (local $r i32)
    (local.set $r (i32.const 1))
    (block $skip
      (br $skip)
      (local.set $r (i32.const 999))
    )
    (local.get $r)
  )
  ;; unconditional br used as an early exit from a single-armed if, merging with the
  ;; fallthrough path at $done - 2 distinct paths (x=1 via br, x=0 via fallthrough).
  (func $br_merge (export "br_merge") (param $x i32) (result i32)
    (local $r i32)
    (block $done
      (if (local.get $x)
        (then
          (local.set $r (i32.const 1))
          (br $done)
        )
      )
      (local.set $r (i32.const 2))
    )
    (local.get $r)
  )
)
