;; `return` on several paths, and an if/else where only one arm returns.
(module
  (func $f (export "f") (param $a i32) (param $b i32) (result i32)
    (if (local.get $a) (then (return (i32.const 1))))
    (if (local.get $b) (then (return (i32.const 2))))
    (i32.const 3))
  (func $g (export "g") (param $x i32) (result i32)
    (if (local.get $x)
      (then (return (i32.const 7)))
      (else (nop)))
    (i32.const 8))
  (func (export "main")
    (drop (call $f (i32.const 1) (i32.const 0)))
    (drop (call $f (i32.const 0) (i32.const 1)))
    (drop (call $f (i32.const 0) (i32.const 1)))
    (drop (call $f (i32.const 0) (i32.const 0)))
    (drop (call $f (i32.const 0) (i32.const 0)))
    (drop (call $f (i32.const 0) (i32.const 0)))
    (drop (call $g (i32.const 1)))
    (drop (call $g (i32.const 0)))
    (drop (call $g (i32.const 0))))
)
