;; Exact path counts: each of 32 paths runs a different number of times, from 1 to 32.
(module
  (func $f (export "f") (param $x i32) (result i32) (local $r i32)
    (if (i32.and (local.get $x) (i32.const 1))
      (then (local.set $r (i32.add (local.get $r) (i32.const 1))))
      (else (local.set $r (local.get $r))))
    (if (i32.and (local.get $x) (i32.const 2))
      (then (local.set $r (i32.add (local.get $r) (i32.const 2))))
      (else (local.set $r (local.get $r))))
    (if (i32.and (local.get $x) (i32.const 4))
      (then (local.set $r (i32.add (local.get $r) (i32.const 4))))
      (else (local.set $r (local.get $r))))
    (if (i32.and (local.get $x) (i32.const 8))
      (then (local.set $r (i32.add (local.get $r) (i32.const 8))))
      (else (local.set $r (local.get $r))))
    (if (i32.and (local.get $x) (i32.const 16))
      (then (local.set $r (i32.add (local.get $r) (i32.const 16))))
      (else (local.set $r (local.get $r))))
    (local.get $r))
  (func (export "main") (result i32) (local $x i32) (local $j i32) (local $acc i32)
    (block $ox (loop $lx
      (br_if $ox (i32.ge_s (local.get $x) (i32.const 32)))
      (local.set $j (i32.const 0))
      (block $oj (loop $lj
        (br_if $oj (i32.gt_s (local.get $j) (local.get $x)))
        (local.set $acc (i32.add (local.get $acc) (call $f (local.get $x))))
        (local.set $j (i32.add (local.get $j) (i32.const 1)))
        (br $lj)))
      (local.set $x (i32.add (local.get $x) (i32.const 1)))
      (br $lx)))
    (local.get $acc)))
