;; Exact path counts in one function mixing a br_table, branches to outer labels and a `return`.
(module
  (func $g (export "g") (param $x i32) (result i32) (local $r i32)
    (block $out
      (block $d
        (block $c2
          (block $c1
            (block $c0
              (br_table $c0 $c1 $c2 $d (local.get $x)))
            (local.set $r (i32.const 10))
            (br $out))                        ;; br to outer label, depth 3
          (local.set $r (i32.const 20))
          (return (i32.const 21)))            ;; mid-body return
        (local.set $r (i32.const 30))
        (br $out))                            ;; br to outer label, depth 1
      (local.set $r (i32.const 40)))          ;; default arm falls through
    (local.get $r))
  (func (export "main")
    (drop (call $g (i32.const 0)))
    (drop (call $g (i32.const 0)))
    (drop (call $g (i32.const 0)))
    (drop (call $g (i32.const 0)))
    (drop (call $g (i32.const 0)))
    (drop (call $g (i32.const 0)))
    (drop (call $g (i32.const 0)))
    (drop (call $g (i32.const 0)))
    (drop (call $g (i32.const 0)))
    (drop (call $g (i32.const 0)))
    (drop (call $g (i32.const 0)))
    (drop (call $g (i32.const 0)))
    (drop (call $g (i32.const 0)))
    (drop (call $g (i32.const 0)))
    (drop (call $g (i32.const 0)))
    (drop (call $g (i32.const 0)))
    (drop (call $g (i32.const 0)))
    (drop (call $g (i32.const 1)))
    (drop (call $g (i32.const 1)))
    (drop (call $g (i32.const 1)))
    (drop (call $g (i32.const 1)))
    (drop (call $g (i32.const 1)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 2)))
    (drop (call $g (i32.const 3)))
    (drop (call $g (i32.const 3)))
    (drop (call $g (i32.const 77)))
    (drop (call $g (i32.const 77)))
    (drop (call $g (i32.const 77)))
    (drop (call $g (i32.const 77)))
    (drop (call $g (i32.const 77)))
    (drop (call $g (i32.const 77)))
    (drop (call $g (i32.const 77)))
    (drop (call $g (i32.const 77)))
    (drop (call $g (i32.const 77)))
    (drop (call $g (i32.const 255)))
    (drop (call $g (i32.const 255)))
    (drop (call $g (i32.const 255)))
    (drop (call $g (i32.const 255)))
  ))
