;; Dead code after an unconditional `br`, a body that only traps, and an else arm that traps.
(module
  (func $after_br (export "after_br") (result i32)
    (local $r i32)
    (block $b
      (local.set $r (i32.const 1))
      (br $b)
      (local.set $r (i32.const 999))
    )
    (local.get $r))
  (func $trap_body (export "trap_body") (result i32)
    (unreachable))
  (func $trap_tail (export "trap_tail") (param $x i32) (result i32)
    (if (local.get $x)
      (then (nop))
      (else (unreachable)))
    (i32.const 4))
  (func (export "main")
    (drop (call $after_br))
    (drop (call $after_br))
    (drop (call $after_br))
    (drop (call $trap_tail (i32.const 1)))
    (drop (call $trap_tail (i32.const 1))))
)
