(module
  (func $diamond (export "diamond") (param $x i32) (result i32)
    (if (result i32) (local.get $x)
      (then (i32.const 1))
      (else (i32.const 2))
    )
  )
  (func (export "main")
    (drop (call $diamond (i32.const 0)))
    (drop (call $diamond (i32.const 1))))
)
