;; `select`, which is not a branch and so stays one path, and a br_if on a call's result.
(module
  (func $pick (export "pick") (param $c i32) (param $a i32) (param $b i32) (result i32)
    (select (local.get $a) (local.get $b) (local.get $c)))
  (func $isodd (export "isodd") (param $n i32) (result i32)
    (i32.and (local.get $n) (i32.const 1)))
  (func $brif_call (export "brif_call") (param $n i32) (result i32)
    (local $r i32)
    (block $done
      (br_if $done (call $isodd (local.get $n)))
      (local.set $r (i32.const 5))
    )
    (local.get $r))
  (func (export "main")
    (drop (call $pick (i32.const 0) (i32.const 1) (i32.const 2)))
    (drop (call $pick (i32.const 1) (i32.const 1) (i32.const 2)))
    (drop (call $pick (i32.const 0) (i32.const 3) (i32.const 4)))
    (drop (call $pick (i32.const 1) (i32.const 3) (i32.const 4)))
    (drop (call $brif_call (i32.const 1)))
    (drop (call $brif_call (i32.const 3)))
    (drop (call $brif_call (i32.const 2)))
    (drop (call $brif_call (i32.const 4)))
    (drop (call $brif_call (i32.const 6))))
)
