(module
  (type $s (struct (field i32)))
  (type $f (func (result i32)))
  (type $c (cont $f))
  (type $g (func (param i32) (result i32)))
  (type $cg (cont $g))
  (tag $u)
  (tag $t (param i32 (ref null $s) (ref null $c) f64) (result i32))

  (func $forty_two (result i32) (i32.const 42))
  (func $leaf (result i32)
    (i32.add (i32.const 1000)
      (suspend $t (i32.const 7) (struct.new $s (i32.const 5)) (cont.new $c (ref.func $forty_two)) (f64.const 2.5)))
  )
  (func $mid2 (result i32)
    (block $h (result (ref null $c))
      (return (i32.add (i32.const 100) (resume $c (on $u $h) (cont.new $c (ref.func $leaf)))))
    )
    (drop)
    (i32.const -1)
  )
  (func $mid1 (result i32)
    (i32.add (i32.const 10) (resume $c (cont.new $c (ref.func $mid2))))
  )
  (elem declare func $forty_two $leaf $mid2 $mid1)

  (func (export "main") (result i32)
    (local $k (ref null $cg))
    (local $fresh (ref null $c))
    (local $st (ref null $s))
    (local $d f64)
    (local $i i32)
    (block $h (result i32 (ref null $s) (ref null $c) f64 (ref null $cg))
      (return (resume $c (on $t $h) (cont.new $c (ref.func $mid1))))
    )
    (local.set $k)
    (local.set $d)
    (local.set $fresh)
    (local.set $st)
    (local.set $i)
    ;; 7 + 42 + 5 + 2 = 56; leaf 1056, mid2 1156, mid1 1166
    (local.get $i)
    (resume $c (local.get $fresh))
    (i32.add)
    (struct.get $s 0 (local.get $st))
    (i32.add)
    (i32.trunc_f64_s (local.get $d))
    (i32.add)
    (local.get $k)
    (resume $cg)
  )
)

(assert_return (invoke "main") (i32.const 1166))
(assert_return (invoke "main") (i32.const 1166))
