(module
  (type $f1 (func (result i32)))
  (type $c1 (cont $f1))
  (type $f2 (func (param (ref null $c1)) (result i32)))
  (type $c2 (cont $f2))
  (tag $sw (result i32))

  (func $c (param $k (ref null $c1)) (result i32) (i32.const 5))
  (func $b_used (result i32)
    (local $x (ref null $c2))
    (local.set $x (cont.new $c2 (ref.func $c)))
    (drop (cont.bind $c2 $c2 (local.get $x)))
    (switch $c2 $sw (local.get $x))
    (i32.const 99)
  )
  (func $b_ok (result i32)
    (switch $c2 $sw (cont.new $c2 (ref.func $c)))
    (i32.const 99)
  )
  (elem declare func $c $b_used $b_ok)

  (func (export "used") (result i32)
    (resume $c1 (on $sw switch) (cont.new $c1 (ref.func $b_used)))
  )
  (func (export "ok") (result i32)
    (resume $c1 (on $sw switch) (cont.new $c1 (ref.func $b_ok)))
  )
)

(assert_return (invoke "ok") (i32.const 5))
(assert_trap (invoke "used") "continuation already consumed")
(assert_return (invoke "ok") (i32.const 5))
