(module
  (type $f1 (func (result i32)))
  (type $c1 (cont $f1))
  (type $f2 (func (param (ref null $c1)) (result i32)))
  (type $c2 (cont $f2))
  (type $fs (func (param i32) (result i32)))
  (type $cs (cont $fs))
  (tag $sw (result i32))
  (tag $t (param i32) (result i32))

  (func $c_suspends (param $k (ref null $c1)) (result i32)
    (i32.add (i32.const 200) (suspend $t (i32.const 3)))
  )
  (func $c_returns (param $k (ref null $c1)) (result i32)
    (i32.const 77)
  )
  (func $b_to_suspender (result i32)
    (switch $c2 $sw (cont.new $c2 (ref.func $c_suspends)))
    (i32.const 99)
  )
  (func $b_to_returner (result i32)
    (switch $c2 $sw (cont.new $c2 (ref.func $c_returns)))
    (i32.const 99)
  )
  (elem declare func $c_suspends $c_returns $b_to_suspender $b_to_returner)

  (func (export "suspend_after_switch") (result i32)
    (local $k (ref null $cs))
    (block $h (result i32 (ref null $cs))
      (return (resume $c1 (on $sw switch) (on $t $h) (cont.new $c1 (ref.func $b_to_suspender))))
    )
    (local.set $k)
    (i32.const 1)
    (i32.add)
    (local.get $k)
    (resume $cs)
  )
  (func (export "return_after_switch") (result i32)
    (block $h (result i32 (ref null $cs))
      (return (resume $c1 (on $sw switch) (on $t $h) (cont.new $c1 (ref.func $b_to_returner))))
    )
    (drop)
    (drop)
    (i32.const -1)
  )
)

(assert_return (invoke "suspend_after_switch") (i32.const 204))
(assert_return (invoke "return_after_switch") (i32.const 77))
(assert_return (invoke "suspend_after_switch") (i32.const 204))
(assert_return (invoke "return_after_switch") (i32.const 77))
