(module
  (type $f (func (result i32)))
  (type $c (cont $f))
  (type $fs (func (param i32) (result i32)))
  (type $cs (cont $fs))
  (type $s (struct (field i32)))
  (tag $t (param i32 f64 (ref null $s)) (result i32))

  (func $child (result i32)
    (i32.add (i32.const 10) (suspend $t (i32.const 1) (f64.const 1.5) (struct.new $s (i32.const 3))))
  )
  (elem declare func $child)

  (func $run1 (result i32)
    (local $k (ref null $cs))
    (local $st (ref null $s))
    (local $d f64)
    (local $i i32)
    (local $n i32)
    (block $h (result i32 f64 (ref null $s) (ref null $cs))
      (return (resume $c (on $t $h) (cont.new $c (ref.func $child))))
    )
    (local.set $k)
    (local.set $st)
    (local.set $d)
    (local.set $i)
    (local.set $n (i32.const 4))
    (loop $l
      (local.set $i (i32.add (local.get $i) (struct.get $s 0 (local.get $st))))
      (local.set $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l (local.get $n))
    )
    ;; 1 + 4 * 3 + 1 = 14; child returns 24
    (resume $cs (i32.add (local.get $i) (i32.trunc_f64_s (local.get $d))) (local.get $k))
  )
  (func $run2 (result i32)
    (local $k (ref null $cs))
    (local $st (ref null $s))
    (local $d f64)
    (local $i i32)
    (local $n i32)
    (block $h (result i32 f64 (ref null $s) (ref null $cs))
      (return (resume $c (on $t $h) (cont.new $c (ref.func $child))))
    )
    (local.set $k)
    (local.set $st)
    (local.set $d)
    (local.set $i)
    (local.set $n (i32.const 4))
    (loop $l
      (local.set $i (i32.add (local.get $i) (struct.get $s 0 (local.get $st))))
      (local.set $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l (local.get $n))
    )
    (resume $cs (i32.add (local.get $i) (i32.trunc_f64_s (local.get $d))) (local.get $k))
  )
  (func (export "main") (result i32) (call $run1))
  (func (export "main2") (result i32) (call $run2))
)

(assert_return (invoke "main") (i32.const 24))
(assert_return (invoke "main") (i32.const 24))
(assert_return (invoke "main") (i32.const 24))
(assert_return (invoke "main") (i32.const 24))
(assert_return (invoke "main") (i32.const 24))
(assert_return (invoke "main") (i32.const 24))
(assert_return (invoke "main") (i32.const 24))
(assert_return (invoke "main") (i32.const 24))
(assert_return (invoke "main") (i32.const 24))
(assert_return (invoke "main") (i32.const 24))
(assert_return (invoke "main") (i32.const 24))
(assert_return (invoke "main") (i32.const 24))
;; compiled suspender, interpreted resumer
(assert_return (invoke "main2") (i32.const 24))
(assert_return (invoke "main2") (i32.const 24))
(assert_return (invoke "main2") (i32.const 24))
