;; Resumes left through exceptions and traps must leave the parent stack clean for later resumes.
(module
  (type $f (func (result i32)))
  (type $c (cont $f))
  (type $fs (func (param i32) (result i32)))
  (type $cs (cont $fs))
  (tag $ex (param i32))
  (tag $t (param i32) (result i32))

  (func $thrower (result i32) (throw $ex (i32.const 3)))
  (func $suspender (result i32) (i32.add (i32.const 40) (suspend $t (i32.const 4))))
  (func $trapper (result i32) (unreachable))
  ;; catches an exception thrown into the child it resumes
  (func $catching_middle (result i32)
    (block $caught (result i32)
      (try_table (result i32) (catch $ex $caught)
        (resume $c (cont.new $c (ref.func $suspender)))
      )
      (return)
    )
    (i32.add (i32.const 2000))
  )
  (elem declare func $thrower $suspender $trapper $catching_middle)

  ;; shared resume site with a handler for $t
  (func $run (param $child (ref $f)) (result i32)
    (local $k (ref null $cs))
    (block $h (result i32 (ref null $cs))
      (return (resume $c (on $t $h) (cont.new $c (local.get $child))))
    )
    (local.set $k)
    (i32.const 2)
    (i32.add)
    (local.get $k)
    (resume $cs)
  )

  ;; the child throws and the parent catches at its resume, then resumes a suspender elsewhere
  (func $resume_catching (param $child (ref $f)) (result i32)
    (block $caught (result i32)
      (try_table (result i32) (catch $ex $caught)
        (resume $c (cont.new $c (local.get $child)))
      )
      (return)
    )
  )
  (func (export "catch_then_resume") (result i32)
    (call $resume_catching (ref.func $thrower))
    (call $run (ref.func $suspender))
    (i32.add)
  )
  ;; an exception thrown into a suspended chain is caught by the middle stack, unwinding its resume
  (func (export "resume_throw_into_chain") (result i32)
    (local $k (ref null $cs))
    (block $h (result i32 (ref null $cs))
      (return (resume $c (on $t $h) (cont.new $c (ref.func $catching_middle))))
    )
    (local.set $k)
    (drop)
    (resume_throw $cs $ex (i32.const 5) (local.get $k))
  )
  ;; the child traps; the next runs start from fresh stacks
  (func (export "trap") (result i32) (call $run (ref.func $trapper)))
  (func (export "after_trap") (result i32) (call $run (ref.func $suspender)))
)

(assert_return (invoke "catch_then_resume") (i32.const 49))
(assert_return (invoke "resume_throw_into_chain") (i32.const 2005))
(assert_trap (invoke "trap") "unreachable")
(assert_return (invoke "after_trap") (i32.const 46))
(assert_return (invoke "catch_then_resume") (i32.const 49))
(assert_return (invoke "resume_throw_into_chain") (i32.const 2005))
