;; Tag identity is per instance.
(module definition $M
  (type $f (func))
  (type $c (cont $f))
  (tag $t (export "t"))
  (func $child (export "child") (suspend $t))
  (elem declare func $child)
  (func (export "main") (result i32)
    (block $h (result (ref null $c))
      (resume $c (on $t $h) (cont.new $c (ref.func $child)))
      (return (i32.const 0))
    )
    (drop)
    (i32.const 1)
  )
)
(module instance $I1 $M)
(module instance $I2 $M)
(register "I1" $I1)
(register "I2" $I2)

(assert_return (invoke $I1 "main") (i32.const 1))
(assert_return (invoke $I2 "main") (i32.const 1))

(module definition $N
  (type $f (func))
  (type $c (cont $f))
  (tag $t2 (import "I2" "t"))
  (tag $t1 (import "I1" "t"))
  (func $child1 (import "I1" "child"))
  (func $child2 (import "I2" "child"))
  (elem declare func $child1 $child2)
  (func (export "main") (param $which i32) (result i32)
    (block $h1 (result (ref null $c))
      (block $h2 (result (ref null $c))
        (resume $c (on $t2 $h2) (on $t1 $h1)
          (cont.new $c
            (if (result (ref $f)) (local.get $which)
              (then (ref.func $child1))
              (else (ref.func $child2)))))
        (return (i32.const 0))
      )
      (drop)
      (return (i32.const 2))
    )
    (drop)
    (i32.const 1)
  )
)
(module instance $J $N)

(assert_return (invoke $J "main" (i32.const 1)) (i32.const 1))
(assert_return (invoke $J "main" (i32.const 0)) (i32.const 2))
(assert_return (invoke $J "main" (i32.const 1)) (i32.const 1))
(assert_return (invoke $J "main" (i32.const 0)) (i32.const 2))
