;; A resume site with both a switch clause and a suspend clause, in either order.
(module
  (type $f1 (func (result i32)))
  (type $c1 (cont $f1))
  (type $f2 (func (param (ref null $c1)) (result i32)))
  (type $c2 (cont $f2))
  (type $f3 (func (param i32) (result i32)))
  (type $c3 (cont $f3))
  (tag $a (result i32))
  (tag $b (param i32) (result i32))

  (func $switchee (param (ref null $c1)) (result i32)
    (drop (local.get 0))
    (i32.const 13)
  )
  (func $switcher (result i32)
    (switch $c2 $a (cont.new $c2 (ref.func $switchee)))
    (i32.const 99)
  )
  (func $suspender (result i32)
    (i32.add (i32.const 100) (suspend $b (i32.const 7)))
  )
  (elem declare func $switchee $switcher $suspender)

  (func (export "switch_first") (param $which i32) (result i32)
    (local $k (ref null $c3))
    (block $h (result i32 (ref null $c3))
      (return (resume $c1 (on $a switch) (on $b $h)
        (cont.new $c1
          (if (result (ref $f1)) (local.get $which)
            (then (ref.func $switcher))
            (else (ref.func $suspender))))))
    )
    (local.set $k)
    (drop)
    (resume $c3 (i32.const 8) (local.get $k))
  )
  (func (export "suspend_first") (param $which i32) (result i32)
    (local $k (ref null $c3))
    (block $h (result i32 (ref null $c3))
      (return (resume $c1 (on $b $h) (on $a switch)
        (cont.new $c1
          (if (result (ref $f1)) (local.get $which)
            (then (ref.func $switcher))
            (else (ref.func $suspender))))))
    )
    (local.set $k)
    (drop)
    (resume $c3 (i32.const 8) (local.get $k))
  )
)

(assert_return (invoke "switch_first" (i32.const 1)) (i32.const 13))
(assert_return (invoke "switch_first" (i32.const 0)) (i32.const 108))
(assert_return (invoke "suspend_first" (i32.const 1)) (i32.const 13))
(assert_return (invoke "suspend_first" (i32.const 0)) (i32.const 108))
