;; Run every combination of interpreted and compiled resumer and suspender.
(module
  (type $f (func (result i32)))
  (type $c (cont $f))
  (type $fs (func (param i32) (result i32)))
  (type $cs (cont $fs))
  (tag $t (param i32) (result i32))

  (func $childA (result i32) (i32.add (i32.const 10) (suspend $t (i32.const 1))))
  (func $childB (result i32) (i32.add (i32.const 20) (suspend $t (i32.const 2))))
  (elem declare func $childA $childB)

  (func (export "main") (param $which i32) (result i32)
    (local $k (ref null $cs))
    (block $h (result i32 (ref null $cs))
      (return (resume $c (on $t $h)
        (cont.new $c
          (if (result (ref $f)) (local.get $which)
            (then (ref.func $childB))
            (else (ref.func $childA))))))
    )
    (local.set $k)
    (i32.const 100)
    (i32.add)
    (local.get $k)
    (resume $cs)
  )
  (func (export "main2") (result i32)
    (local $k (ref null $cs))
    (block $h (result i32 (ref null $cs))
      (return (resume $c (on $t $h) (cont.new $c (ref.func $childA))))
    )
    (local.set $k)
    (i32.const 100)
    (i32.add)
    (local.get $k)
    (resume $cs)
  )
)

;; main and childA get compiled along the way
(assert_return (invoke "main" (i32.const 0)) (i32.const 111))
(assert_return (invoke "main" (i32.const 0)) (i32.const 111))
(assert_return (invoke "main" (i32.const 0)) (i32.const 111))
(assert_return (invoke "main" (i32.const 0)) (i32.const 111))
(assert_return (invoke "main" (i32.const 0)) (i32.const 111))
(assert_return (invoke "main" (i32.const 0)) (i32.const 111))
(assert_return (invoke "main" (i32.const 0)) (i32.const 111))
(assert_return (invoke "main" (i32.const 0)) (i32.const 111))
(assert_return (invoke "main" (i32.const 0)) (i32.const 111))
(assert_return (invoke "main" (i32.const 0)) (i32.const 111))
(assert_return (invoke "main" (i32.const 0)) (i32.const 111))
(assert_return (invoke "main" (i32.const 0)) (i32.const 111))
;; compiled resumer, interpreted suspender
(assert_return (invoke "main" (i32.const 1)) (i32.const 122))
(assert_return (invoke "main" (i32.const 1)) (i32.const 122))
(assert_return (invoke "main" (i32.const 1)) (i32.const 122))
;; interpreted resumer, compiled suspender
(assert_return (invoke "main2") (i32.const 111))
(assert_return (invoke "main2") (i32.const 111))
(assert_return (invoke "main2") (i32.const 111))
;; childB and main2 get compiled too
(assert_return (invoke "main" (i32.const 1)) (i32.const 122))
(assert_return (invoke "main" (i32.const 1)) (i32.const 122))
(assert_return (invoke "main" (i32.const 1)) (i32.const 122))
(assert_return (invoke "main" (i32.const 1)) (i32.const 122))
(assert_return (invoke "main" (i32.const 1)) (i32.const 122))
(assert_return (invoke "main" (i32.const 1)) (i32.const 122))
(assert_return (invoke "main" (i32.const 1)) (i32.const 122))
(assert_return (invoke "main" (i32.const 1)) (i32.const 122))
(assert_return (invoke "main2") (i32.const 111))
(assert_return (invoke "main2") (i32.const 111))
(assert_return (invoke "main2") (i32.const 111))
(assert_return (invoke "main2") (i32.const 111))
(assert_return (invoke "main2") (i32.const 111))
(assert_return (invoke "main2") (i32.const 111))
(assert_return (invoke "main2") (i32.const 111))
(assert_return (invoke "main2") (i32.const 111))
