(module
  (type $f1 (func (result i32)))
  (type $c1 (cont $f1))
  (tag $e)
  (tag $f (param i32))
  (func $t (result exnref)
    (try_table (catch_ref $e 0) (throw $e))
    unreachable
  )
  (func $g (param (ref null $c1)) (result exnref (ref null $c1))
     (call $t)
     (local.get 0)
  )
  (func $s (result i32)
    (block $h
      (try_table (catch $e $h) (suspend $f (i32.const 78)))
    )
    (i32.const 12)
  )
  (elem declare func $s)
  (func (export "main") (result i32)
    (block (result i32 (ref null $c1))
      (resume $c1 (on $f 0) (cont.new $c1 (ref.func $s)))
      (ref.null $c1)
    )
    (resume_throw_ref $c1 (call $g))
    (return)
  )
)

(assert_return (invoke "main") (i32.const 12))
