(module
  (type $ft (func (result i32)))
  (type $ct (cont $ft))
  (tag $cancel (param i32 i32))
  (tag $yield (param i32 i32))
  (table $t 1 (ref null $ct))

  (func $worker (type $ft) (result i32)
    (suspend $yield (i32.const 7) (i32.const 8))
    (i32.const 99))
  (elem declare func $worker)

  (func (export "main") (result i32)
    (local $a i32) (local $k (ref null $ct))
    (block $done (result i32)
      (block $on_yield (result i32 i32 (ref $ct))
        (resume $ct (on $yield $on_yield)
          (cont.new $ct (ref.func $worker)))
        (br $done))
      (local.set $k) (drop) (drop)
      (block $on_cancel (result i32 i32)
        (try_table (result i32 i32) (catch $cancel $on_cancel)
          (i32.add (local.get $a) (i32.const 1))
          (i32.add (local.get $a) (i32.const 2))
          (i32.const 7) (i32.const 8)
          (local.get $k)
          (resume_throw $ct $cancel)
          (unreachable)))
      (drop) (drop)
      (table.get $t (i32.const 0))
      (ref.is_null) (drop)
      (i32.const 42)))
)
(assert_return (invoke "main") (i32.const 42))
