;; resume_throw with both a non-zero tag index and a handler, followed by a branch.
(module
  (type $f1 (func (result i32)))
  (type $c1 (cont $f1))
  (tag $f)
  (tag $g)
  (tag $e)
  (func $s (result i32)
    (block $h
      (try_table (catch $e $h) (suspend $f))
      (return (i32.const -1))
    )
    (suspend $g)
    (i32.const 12)
  )
  (elem declare func $s)
  (func (export "main") (result i32)
    (local $k (ref null $c1))
    (block $h1 (result (ref null $c1))
      (resume $c1 (on $f $h1) (cont.new $c1 (ref.func $s)))
      (return)
    )
    (local.set $k)
    (block $h2 (result (ref null $c1))
      (resume_throw $c1 $e (on $g $h2) (local.get $k))
      (return)
    )
    (drop)
    ;; the branch below reads a sidetable entry placed after the resume_throw entries
    (block $done (result i32)
      (i32.const 42)
      (br $done)
    )
  )
)

(assert_return (invoke "main") (i32.const 42))
