;; resume_throw carrying a suspension handler, which is encoded after the tag index.
(module
  (type $f1 (func (result i32)))
  (type $c1 (cont $f1))
  (tag $e)
  (tag $f)
  (tag $g)
  (func $s (result i32)
    (block $h
      (try_table (catch $e $h) (suspend $f))
      (return (i32.const -1))
    )
    (suspend $g)
    (i32.const 12)
  )
  (elem declare func $s)
  (func (export "main") (result i32)
    (local $k (ref null $c1))
    (block $h1 (result (ref null $c1))
      (resume $c1 (on $f $h1) (cont.new $c1 (ref.func $s)))
      (return)
    )
    (local.set $k)
    (block $h2 (result (ref null $c1))
      (resume_throw $c1 $e (on $g $h2) (local.get $k))
      (return)
    )
    (drop)
    (i32.const 42)
  )
)

(assert_return (invoke "main") (i32.const 42))
