(module
  (type $f (func))
  (type $c (cont $f))
  (tag $t)
  
  (func $foo (suspend $t))
  (elem declare func $foo)

  (func (export "main") (result i32)
    (local $x (ref null $c))
    (i32.const 1)
    (cont.new $c (ref.func $foo))
    (loop (param (ref null $c))
      (local.set $x)
      (i32.const 2)
      (i32.const 3)
      (i32.const 4)
      (i32.const 5)
      (local.get $x)
      (resume $c (on $t 0))
      (drop)
      (drop)
      (drop)
      (drop)
    )
    (return)
  )
)

(assert_return (invoke "main") (i32.const 1))
