;; this is the test template for data type passing
;; control flow: main -> $from -> $to -> $from -> main
(module
  (type $f0 (func (result i64 i64 i64)))
  (type $c0 (cont $f0))

  ;; type of $from
  (type $f1 (func (param i64) (result i64 i64 i64)))
  (type $c1 (cont $f1))

  ;; type of continuation generated by switching from $to
  (type $f4 (func (param (ref null $c0)) (result i64 i64 i64)))
  (type $c4 (cont $f4))

  ;; type of continuation generated by switching from $from
  (type $f2 (func (param i64 i64 i64 (ref null $c4)) (result i64 i64 i64)))
  (type $c2 (cont $f2))

  ;; type of $to
  (type $f3 (func (param i64 i64 i64 (ref null $c2)) (result i64 i64 i64)))
  (type $c3 (cont $f3))

  (tag $e (result i64 i64 i64))

  (func $from (param $i i64) (result i64 i64 i64)
    (i64.add (local.get $i) (i64.const 100))
    (i64.add (local.get $i) (i64.const 200))
    (i64.add (local.get $i) (i64.const 300))
    (switch $c3 $e (cont.new $c3 (ref.func $to)))
    (drop)
    (return)
  )
  (elem declare func $from)

  (func $to (param $a i64) (param $b i64) (param $c i64) (param $cont (ref null $c2)) (result i64 i64 i64)
    (i64.add (local.get $a) (i64.const 10))
    (i64.add (local.get $b) (i64.const 20))
    (i64.add (local.get $c) (i64.const 30))
    (switch $c2 $e (local.get $cont))
    (unreachable)
  )
  (elem declare func $to)

  (func (export "main") (param $i i64) (result i64 i64 i64)
    (local.get $i)
    (resume $c1 (on $e switch) (cont.new $c1 (ref.func $from)))
  )
)

(assert_return (invoke "main" (i64.const 0)) (i64.const 110) (i64.const 220) (i64.const 330))
(assert_return (invoke "main" (i64.const 1)) (i64.const 111) (i64.const 221) (i64.const 331))
(assert_return (invoke "main" (i64.const 2)) (i64.const 112) (i64.const 222) (i64.const 332))
(assert_return (invoke "main" (i64.const 3)) (i64.const 113) (i64.const 223) (i64.const 333))
(assert_return (invoke "main" (i64.const 4)) (i64.const 114) (i64.const 224) (i64.const 334))
(assert_return (invoke "main" (i64.const 64)) (i64.const 174) (i64.const 284) (i64.const 394))
