(module
  (type $f1 (func))
  (type $c1 (cont $f1))
  (type $f2 (func (param (ref null $c1))))
  (type $c2 (cont $f2))
  (tag $e)
  (func $p (param (ref null $c1)))
  (elem declare func $p)
  (func $s (switch $c2 $e (cont.new $c2 (ref.func $p))))
  (elem declare func $s)
  (func (export "main")
    (block (result (ref null $c1))
      (resume $c1 (on $e 0) (cont.new $c1 (ref.func $s)))
      (ref.null $c1)
    )
    (drop)
  )
)

(assert_suspension (invoke "main") "unhandled tag")
