;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:sect_empty_s[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\01\00"
)

;; unittest bin:sect_empty_s[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\02\01\00"
)

;; unittest bin:sect_empty_s[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\03\01\00"
)

;; unittest bin:sect_empty_s[4]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\04\01\00"
)

;; unittest bin:sect_empty_s[5]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\01\00"
)

;; unittest bin:sect_empty_s[6]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\06\01\00"
)

;; unittest bin:sect_empty_s[7]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\07\01\00"
)

;; unittest bin:sect_empty_s[8]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\09\01\00"
)

;; unittest bin:sect_empty_s[9]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\0a\01\00"
)

;; unittest bin:sect_empty_s[10]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\0b\01\00"
)

