;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:memory_limits[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\85\80\80\80\00\01\00"
  "\ff\ff\03"
)

;; unittest bin:memory_limits[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\86\80\80\80\00\01\01"
  "\00\ff\ff\03"
)

;; unittest bin:memory_limits[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\85\80\80\80\00\01\00"
  "\80\80\04"
)

;; unittest bin:memory_limits[4]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\86\80\80\80\00\01\01"
  "\00\80\80\04"
)

;; skipped: EXCEEDED_LIMIT is an engine-specific limit
;; skipped: EXCEEDED_LIMIT is an engine-specific limit
