;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:data_count[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\0c\81\80\80\80\00\00"
)

;; unittest bin:data_count[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\0c\81\80\80\80\00\00\0b"
  "\81\80\80\80\00\00"
)

;; unittest bin:data_count[3]: MALFORMED DATA_COUNT_MISMATCH [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\0c\81\80\80\80\00\01"
  )
  "data count and data section have inconsistent lengths"
)

;; unittest bin:data_count[4]: MALFORMED DATA_COUNT_MISMATCH [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\0c\81\80\80\80\00\01\0b"
    "\81\80\80\80\00\00"
  )
  "data count and data section have inconsistent lengths"
)

;; unittest bin:data_count[5]: MALFORMED DATA_COUNT_MISMATCH [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\0c\81\80\80\80\00\01\0b"
    "\91\80\80\80\00\02\00\41\00\0b\03\61\62\63\00\41"
    "\00\0b\03\61\62\63"
  )
  "data count and data section have inconsistent lengths"
)

