;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:repeat_types1[1]: MALFORMED DUPLICATE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\01\04"
    "\01\60\00\00"
  )
  "unexpected content after last section"
)

;; unittest bin:repeat_types1[2]: MALFORMED DUPLICATE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\01\04"
    "\01\60\00\00\01\04\01\60\00\00"
  )
  "unexpected content after last section"
)

;; unittest bin:repeat_types1[3]: MALFORMED DUPLICATE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\01\04"
    "\01\60\00\00\01\04\01\60\00\00\01\04\01\60\00\00"
  )
  "unexpected content after last section"
)

;; skipped: needs the non-standard extension(s) repeat-sections
;; skipped: needs the non-standard extension(s) repeat-sections
;; skipped: needs the non-standard extension(s) repeat-sections
