;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:tablesN[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\04\01\00"
)

;; unittest bin:tablesN[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\04\04\01\70\00\00"
)

;; unittest bin:tablesN[3]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\04\04"
  )
  "length out of bounds"
)

;; unittest bin:tablesN[4]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\04\04\01"
  )
  "length out of bounds"
)

;; unittest bin:tablesN[5]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\04\04\01\70"
  )
  "length out of bounds"
)

;; unittest bin:tablesN[6]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\04\04\01\70\00"
  )
  "unexpected end of section or function"
)

;; unittest bin:tablesN[7]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\04\02\00\63"
  )
  "section size mismatch"
)

;; unittest bin:tablesN[8]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\04\05\01\70\00\00\63"
  )
  "section size mismatch"
)

