;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:sect_underflow[1]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\02\00"
  )
  "section size mismatch"
)

;; unittest bin:sect_underflow[2]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\02\00"
  )
  "section size mismatch"
)

;; unittest bin:sect_underflow[3]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\03\02\00"
  )
  "section size mismatch"
)

;; unittest bin:sect_underflow[4]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\04\02\00"
  )
  "section size mismatch"
)

;; unittest bin:sect_underflow[5]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\02\00"
  )
  "section size mismatch"
)

;; unittest bin:sect_underflow[6]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\02\00"
  )
  "section size mismatch"
)

;; unittest bin:sect_underflow[7]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\07\02\00"
  )
  "section size mismatch"
)

;; unittest bin:sect_underflow[8]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\09\02\00"
  )
  "section size mismatch"
)

;; unittest bin:sect_underflow[9]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\0a\02\00"
  )
  "section size mismatch"
)

;; unittest bin:sect_underflow[10]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\0b\02\00"
  )
  "section size mismatch"
)

