;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:sect_custom1[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\00\0b\0a\6d\79\5f\73\65"
  "\63\74\69\6f\6e"
)

;; unittest bin:sect_custom1[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\00\0c\0a\6d\79\5f\73\65"
  "\63\74\69\6f\6e\4d"
)

;; unittest bin:sect_custom1[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\00\0d\0a\6d\79\5f\73\65"
  "\63\74\69\6f\6e\4d\4d"
)

;; unittest bin:sect_custom1[4]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\00\0e\0a\6d\79\5f\73\65"
  "\63\74\69\6f\6e\4d\4d\4d"
)

;; unittest bin:sect_custom1[5]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\00\0f\0a\6d\79\5f\73\65"
  "\63\74\69\6f\6e\4d\4d\4d\4d"
)

