;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:count_limits[1]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\83\80\80\80\00\bf\84"
    "\3d"
  )
  "length out of bounds"
)

;; unittest bin:count_limits[2]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\83\80\80\80\00\c0\84"
    "\3d"
  )
  "length out of bounds"
)

;; skipped: EXCEEDED_LIMIT is an engine-specific limit
;; unittest bin:count_limits[3]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\03\83\80\80\80\00\bf\84"
    "\3d"
  )
  "length out of bounds"
)

;; unittest bin:count_limits[4]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\03\83\80\80\80\00\c0\84"
    "\3d"
  )
  "length out of bounds"
)

;; skipped: EXCEEDED_LIMIT is an engine-specific limit
;; unittest bin:count_limits[5]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\83\80\80\80\00\9f\8d"
    "\06"
  )
  "length out of bounds"
)

;; unittest bin:count_limits[6]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\83\80\80\80\00\a0\8d"
    "\06"
  )
  "length out of bounds"
)

;; skipped: EXCEEDED_LIMIT is an engine-specific limit
;; unittest bin:count_limits[7]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\07\83\80\80\80\00\9f\8d"
    "\06"
  )
  "length out of bounds"
)

;; unittest bin:count_limits[8]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\07\83\80\80\80\00\a0\8d"
    "\06"
  )
  "length out of bounds"
)

;; skipped: EXCEEDED_LIMIT is an engine-specific limit
;; unittest bin:count_limits[9]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\83\80\80\80\00\bf\84"
    "\3d"
  )
  "length out of bounds"
)

;; unittest bin:count_limits[10]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\83\80\80\80\00\c0\84"
    "\3d"
  )
  "length out of bounds"
)

;; skipped: EXCEEDED_LIMIT is an engine-specific limit
;; unittest bin:count_limits[11]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\0b\83\80\80\80\00\9f\8d"
    "\06"
  )
  "length out of bounds"
)

;; unittest bin:count_limits[12]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\0b\83\80\80\80\00\a0\8d"
    "\06"
  )
  "length out of bounds"
)

;; skipped: EXCEEDED_LIMIT is an engine-specific limit
;; unittest bin:count_limits[13]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\04\83\80\80\80\00\9f\8d"
    "\06"
  )
  "length out of bounds"
)

;; unittest bin:count_limits[14]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\04\83\80\80\80\00\a0\8d"
    "\06"
  )
  "length out of bounds"
)

;; skipped: EXCEEDED_LIMIT is an engine-specific limit
;; unittest bin:count_limits[15]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\81\80\80\80\00\00"
)

;; unittest bin:count_limits[16]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\81\80\80\80\00\01"
  )
  "unexpected end of section or function"
)

;; skipped: EXCEEDED_LIMIT is an engine-specific limit
