;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:sect_custom_ovf[1]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\00\09\09\78\5f\73\65\63"
    "\74\69\6f\6e"
  )
  "unexpected end of section or function"
)

;; unittest bin:sect_custom_ovf[2]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\00\08\09\78\5f\73\65\63"
    "\74\69\6f\6e"
  )
  "unexpected end of section or function"
)

;; unittest bin:sect_custom_ovf[3]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\00\07\09\78\5f\73\65\63"
    "\74\69\6f\6e"
  )
  "unexpected end of section or function"
)

;; unittest bin:sect_custom_ovf[4]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\00\06\09\78\5f\73\65\63"
    "\74\69\6f\6e"
  )
  "unexpected end of section or function"
)

;; unittest bin:sect_custom_ovf[5]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\00\05\09\78\5f\73\65\63"
    "\74\69\6f\6e"
  )
  "unexpected end of section or function"
)

;; unittest bin:sect_custom_ovf[6]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\00\04\09\78\5f\73\65\63"
    "\74\69\6f\6e"
  )
  "unexpected end of section or function"
)

;; unittest bin:sect_custom_ovf[7]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\00\03\09\78\5f\73\65\63"
    "\74\69\6f\6e"
  )
  "unexpected end of section or function"
)

;; unittest bin:sect_custom_ovf[8]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\00\02\09\78\5f\73\65\63"
    "\74\69\6f\6e"
  )
  "unexpected end of section or function"
)

;; unittest bin:sect_custom_ovf[9]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\00\01\09\78\5f\73\65\63"
    "\74\69\6f\6e"
  )
  "unexpected end of section or function"
)

;; unittest bin:sect_custom_ovf[10]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\00\00\09\78\5f\73\65\63"
    "\74\69\6f\6e"
  )
  "unexpected end of section or function"
)

