;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:max_num_tables[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\02\89\80\80\80\00\01\01"
  "\4d\01\6d\01\70\00\00"
)

;; unittest bin:max_num_tables[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\04\84\80\80\80\00\01\70"
  "\00\00"
)

;; unittest bin:max_num_tables[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\02\81\80\80\80\00\00\04"
  "\84\80\80\80\00\01\70\00\00"
)

;; skipped: EXCEEDED_LIMIT is an engine-specific limit
;; skipped: EXCEEDED_LIMIT is an engine-specific limit
;; skipped: EXCEEDED_LIMIT is an engine-specific limit
;; unittest bin:max_num_tables[4]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\02\a1\80\80\80\00\04\01"
  "\4d\01\6d\01\70\00\00\01\4d\01\6d\01\70\00\00\01"
  "\4d\01\6d\01\70\00\00\01\4d\01\6d\01\70\00\00"
)

;; unittest bin:max_num_tables[5]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\04\8d\80\80\80\00\04\70"
  "\00\00\70\00\00\70\00\00\70\00\00"
)

;; unittest bin:max_num_tables[6]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\02\99\80\80\80\00\03\01"
  "\4d\01\6d\01\70\00\00\01\4d\01\6d\01\70\00\00\01"
  "\4d\01\6d\01\70\00\00\04\84\80\80\80\00\01\70\00"
  "\00"
)

;; unittest bin:max_num_tables[7]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\02\a9\80\80\80\00\05\01"
  "\4d\01\6d\01\70\00\00\01\4d\01\6d\01\70\00\00\01"
  "\4d\01\6d\01\70\00\00\01\4d\01\6d\01\70\00\00\01"
  "\4d\01\6d\01\70\00\00"
)

;; unittest bin:max_num_tables[8]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\04\90\80\80\80\00\05\70"
  "\00\00\70\00\00\70\00\00\70\00\00\70\00\00"
)

;; unittest bin:max_num_tables[9]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\02\a1\80\80\80\00\04\01"
  "\4d\01\6d\01\70\00\00\01\4d\01\6d\01\70\00\00\01"
  "\4d\01\6d\01\70\00\00\01\4d\01\6d\01\70\00\00\04"
  "\84\80\80\80\00\01\70\00\00"
)

;; skipped: EXCEEDED_LIMIT is an engine-specific limit
;; skipped: EXCEEDED_LIMIT is an engine-specific limit
;; skipped: EXCEEDED_LIMIT is an engine-specific limit
