;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:empty[1]: MALFORMED INVALID_HEADER [none]
(assert_malformed
  (module binary
  )
  "unexpected end of section or function"
)

;; unittest bin:empty[2]: MALFORMED INVALID_HEADER [none]
(assert_malformed
  (module binary
    "\00"
  )
  "unexpected end of section or function"
)

;; unittest bin:empty[3]: MALFORMED INVALID_HEADER [none]
(assert_malformed
  (module binary
    "\00\61"
  )
  "unexpected end of section or function"
)

;; unittest bin:empty[4]: MALFORMED INVALID_HEADER [none]
(assert_malformed
  (module binary
    "\00\61\73"
  )
  "unexpected end of section or function"
)

;; unittest bin:empty[5]: MALFORMED INVALID_HEADER [none]
(assert_malformed
  (module binary
    "\00\61\73\6d"
  )
  "unexpected end of section or function"
)

;; unittest bin:empty[6]: MALFORMED INVALID_HEADER [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01"
  )
  "unexpected end of section or function"
)

;; unittest bin:empty[7]: MALFORMED INVALID_HEADER [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00"
  )
  "unexpected end of section or function"
)

;; unittest bin:empty[8]: MALFORMED INVALID_HEADER [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00"
  )
  "unexpected end of section or function"
)

