;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:exportsN[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
  "\07\01\00"
)

;; unittest bin:exportsN[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
  "\07\05\01\01\67\03\00"
)

;; unittest bin:exportsN[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
  "\07\09\02\01\67\03\00\01\68\03\00"
)

;; unittest bin:exportsN[4]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
  "\07\0d\03\01\67\03\00\01\68\03\00\01\69\03\00"
)

;; unittest bin:exportsN[5]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
    "\07\0d"
  )
  "length out of bounds"
)

;; unittest bin:exportsN[6]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
    "\07\0d\03"
  )
  "length out of bounds"
)

;; unittest bin:exportsN[7]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
    "\07\0d\03\01"
  )
  "length out of bounds"
)

;; unittest bin:exportsN[8]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
    "\07\0d\03\01\67"
  )
  "length out of bounds"
)

;; unittest bin:exportsN[9]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
    "\07\0d\03\01\67\03"
  )
  "length out of bounds"
)

;; unittest bin:exportsN[10]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
    "\07\0d\03\01\67\03\00"
  )
  "length out of bounds"
)

;; unittest bin:exportsN[11]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
    "\07\0d\03\01\67\03\00\01"
  )
  "length out of bounds"
)

;; unittest bin:exportsN[12]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
    "\07\0d\03\01\67\03\00\01\68"
  )
  "length out of bounds"
)

;; unittest bin:exportsN[13]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
    "\07\0d\03\01\67\03\00\01\68\03"
  )
  "length out of bounds"
)

;; unittest bin:exportsN[14]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
    "\07\0d\03\01\67\03\00\01\68\03\00"
  )
  "length out of bounds"
)

;; unittest bin:exportsN[15]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
    "\07\0d\03\01\67\03\00\01\68\03\00\01"
  )
  "length out of bounds"
)

;; unittest bin:exportsN[16]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
    "\07\0d\03\01\67\03\00\01\68\03\00\01\69"
  )
  "length out of bounds"
)

;; unittest bin:exportsN[17]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
    "\07\0d\03\01\67\03\00\01\68\03\00\01\69\03"
  )
  "unexpected end of section or function"
)

;; unittest bin:exportsN[18]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
    "\07\02\00\63"
  )
  "section size mismatch"
)

;; unittest bin:exportsN[19]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
    "\07\06\01\01\67\03\00\63"
  )
  "section size mismatch"
)

;; unittest bin:exportsN[20]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
    "\07\0a\02\01\67\03\00\01\68\03\00\63"
  )
  "section size mismatch"
)

;; unittest bin:exportsN[21]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
    "\07\0e\03\01\67\03\00\01\68\03\00\01\69\03\00\63"
  )
  "section size mismatch"
)

