;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:typesN[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\01\00"
)

;; unittest bin:typesN[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\06\01\60\01\7f\01\7f"
)

;; unittest bin:typesN[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\0b\02\60\01\7f\01\7f"
  "\60\01\7f\01\7f"
)

;; unittest bin:typesN[4]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\10\03\60\01\7f\01\7f"
  "\60\01\7f\01\7f\60\01\7f\01\7f"
)

;; unittest bin:typesN[5]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\10"
  )
  "length out of bounds"
)

;; unittest bin:typesN[6]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\10\03"
  )
  "length out of bounds"
)

;; unittest bin:typesN[7]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\10\03\60"
  )
  "length out of bounds"
)

;; unittest bin:typesN[8]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\10\03\60\01"
  )
  "length out of bounds"
)

;; unittest bin:typesN[9]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\10\03\60\01\7f"
  )
  "length out of bounds"
)

;; unittest bin:typesN[10]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\10\03\60\01\7f\01"
  )
  "length out of bounds"
)

;; unittest bin:typesN[11]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\10\03\60\01\7f\01\7f"
  )
  "length out of bounds"
)

;; unittest bin:typesN[12]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\10\03\60\01\7f\01\7f"
    "\60"
  )
  "length out of bounds"
)

;; unittest bin:typesN[13]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\10\03\60\01\7f\01\7f"
    "\60\01"
  )
  "length out of bounds"
)

;; unittest bin:typesN[14]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\10\03\60\01\7f\01\7f"
    "\60\01\7f"
  )
  "length out of bounds"
)

;; unittest bin:typesN[15]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\10\03\60\01\7f\01\7f"
    "\60\01\7f\01"
  )
  "length out of bounds"
)

;; unittest bin:typesN[16]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\10\03\60\01\7f\01\7f"
    "\60\01\7f\01\7f"
  )
  "length out of bounds"
)

;; unittest bin:typesN[17]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\10\03\60\01\7f\01\7f"
    "\60\01\7f\01\7f\60"
  )
  "length out of bounds"
)

;; unittest bin:typesN[18]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\10\03\60\01\7f\01\7f"
    "\60\01\7f\01\7f\60\01"
  )
  "length out of bounds"
)

;; unittest bin:typesN[19]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\10\03\60\01\7f\01\7f"
    "\60\01\7f\01\7f\60\01\7f"
  )
  "length out of bounds"
)

;; unittest bin:typesN[20]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\10\03\60\01\7f\01\7f"
    "\60\01\7f\01\7f\60\01\7f\01"
  )
  "unexpected end of section or function"
)

;; unittest bin:typesN[21]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\02\00\63"
  )
  "section size mismatch"
)

;; unittest bin:typesN[22]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\07\01\60\01\7f\01\7f"
    "\63"
  )
  "section size mismatch"
)

;; unittest bin:typesN[23]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\0c\02\60\01\7f\01\7f"
    "\60\01\7f\01\7f\63"
  )
  "section size mismatch"
)

;; unittest bin:typesN[24]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\11\03\60\01\7f\01\7f"
    "\60\01\7f\01\7f\60\01\7f\01\7f\63"
  )
  "section size mismatch"
)

