;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:elements4[1]: VALID [function-references]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\08\02\60\00\00\60\01"
  "\7f\00\02\0d\02\01\4d\01\66\00\00\01\4d\01\66\00"
  "\01\04\05\01\63\00\00\00\09\87\80\80\80\00\01\00"
  "\41\00\0b\01\00"
)

;; unittest bin:elements4[2]: INVALID TYPE_MISMATCH [function-references]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\08\02\60\00\00\60\01"
    "\7f\00\02\0d\02\01\4d\01\66\00\00\01\4d\01\66\00"
    "\01\04\05\01\63\00\00\00\09\87\80\80\80\00\01\00"
    "\41\00\0b\01\01"
  )
  "type mismatch: element segment's type (ref func) does not match table's element type (ref null 0)"
)

