;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:imports2[1]: MALFORMED INVALID_IMPORT_KIND [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\86\80\80\80\00\01\01"
    "\50\01\6a\05"
  )
  "malformed import kind"
)

