;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:importsN[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\02\01\00"
)

;; unittest bin:importsN[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\02\08\01\01\4d\01\67\03"
  "\7f\00"
)

;; unittest bin:importsN[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\02\0f\02\01\4d\01\67\03"
  "\7f\00\01\4d\01\67\03\7f\00"
)

;; unittest bin:importsN[4]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\02\16\03\01\4d\01\67\03"
  "\7f\00\01\4d\01\67\03\7f\00\01\4d\01\67\03\7f\00"
)

;; unittest bin:importsN[5]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\16"
  )
  "length out of bounds"
)

;; unittest bin:importsN[6]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\16\03"
  )
  "length out of bounds"
)

;; unittest bin:importsN[7]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\16\03\01"
  )
  "length out of bounds"
)

;; unittest bin:importsN[8]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\16\03\01\4d"
  )
  "length out of bounds"
)

;; unittest bin:importsN[9]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\16\03\01\4d\01"
  )
  "length out of bounds"
)

;; unittest bin:importsN[10]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\16\03\01\4d\01\67"
  )
  "length out of bounds"
)

;; unittest bin:importsN[11]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\16\03\01\4d\01\67\03"
  )
  "length out of bounds"
)

;; unittest bin:importsN[12]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\16\03\01\4d\01\67\03"
    "\7f"
  )
  "length out of bounds"
)

;; unittest bin:importsN[13]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\16\03\01\4d\01\67\03"
    "\7f\00"
  )
  "length out of bounds"
)

;; unittest bin:importsN[14]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\16\03\01\4d\01\67\03"
    "\7f\00\01"
  )
  "length out of bounds"
)

;; unittest bin:importsN[15]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\16\03\01\4d\01\67\03"
    "\7f\00\01\4d"
  )
  "length out of bounds"
)

;; unittest bin:importsN[16]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\16\03\01\4d\01\67\03"
    "\7f\00\01\4d\01"
  )
  "length out of bounds"
)

;; unittest bin:importsN[17]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\16\03\01\4d\01\67\03"
    "\7f\00\01\4d\01\67"
  )
  "length out of bounds"
)

;; unittest bin:importsN[18]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\16\03\01\4d\01\67\03"
    "\7f\00\01\4d\01\67\03"
  )
  "length out of bounds"
)

;; unittest bin:importsN[19]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\16\03\01\4d\01\67\03"
    "\7f\00\01\4d\01\67\03\7f"
  )
  "length out of bounds"
)

;; unittest bin:importsN[20]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\16\03\01\4d\01\67\03"
    "\7f\00\01\4d\01\67\03\7f\00"
  )
  "length out of bounds"
)

;; unittest bin:importsN[21]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\16\03\01\4d\01\67\03"
    "\7f\00\01\4d\01\67\03\7f\00\01"
  )
  "length out of bounds"
)

;; unittest bin:importsN[22]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\16\03\01\4d\01\67\03"
    "\7f\00\01\4d\01\67\03\7f\00\01\4d"
  )
  "length out of bounds"
)

;; unittest bin:importsN[23]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\16\03\01\4d\01\67\03"
    "\7f\00\01\4d\01\67\03\7f\00\01\4d\01"
  )
  "length out of bounds"
)

;; unittest bin:importsN[24]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\16\03\01\4d\01\67\03"
    "\7f\00\01\4d\01\67\03\7f\00\01\4d\01\67"
  )
  "length out of bounds"
)

;; unittest bin:importsN[25]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\16\03\01\4d\01\67\03"
    "\7f\00\01\4d\01\67\03\7f\00\01\4d\01\67\03"
  )
  "length out of bounds"
)

;; unittest bin:importsN[26]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\16\03\01\4d\01\67\03"
    "\7f\00\01\4d\01\67\03\7f\00\01\4d\01\67\03\7f"
  )
  "unexpected end of section or function"
)

;; unittest bin:importsN[27]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\02\00\63"
  )
  "section size mismatch"
)

;; unittest bin:importsN[28]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\09\01\01\4d\01\67\03"
    "\7f\00\63"
  )
  "section size mismatch"
)

;; unittest bin:importsN[29]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\10\02\01\4d\01\67\03"
    "\7f\00\01\4d\01\67\03\7f\00\63"
  )
  "section size mismatch"
)

;; unittest bin:importsN[30]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\17\03\01\4d\01\67\03"
    "\7f\00\01\4d\01\67\03\7f\00\01\4d\01\67\03\7f\00"
    "\63"
  )
  "section size mismatch"
)

