;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:memory0[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\83\80\80\80\00\01\00"
  "\00"
)

;; unittest bin:memory0[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\83\80\80\80\00\01\00"
  "\01"
)

;; unittest bin:memory0[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\83\80\80\80\00\01\00"
  "\05"
)

;; unittest bin:memory0[4]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\84\80\80\80\00\01\01"
  "\02\05"
)

;; unittest bin:memory0[5]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\83\80\80\80\00\01\01"
    "\00"
  )
  "unexpected end of section or function"
)

