;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:dataN[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\01\00"
)

;; unittest bin:dataN[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\09\01"
  "\00\41\00\0b\03\61\62\63"
)

;; unittest bin:dataN[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\11\02"
  "\00\41\00\0b\03\61\62\63\00\41\00\0b\03\61\62\63"
)

;; unittest bin:dataN[4]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
  "\00\41\00\0b\03\61\62\63\00\41\00\0b\03\61\62\63"
  "\00\41\00\0b\03\61\62\63"
)

;; unittest bin:dataN[5]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19"
  )
  "length out of bounds"
)

;; unittest bin:dataN[6]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
  )
  "length out of bounds"
)

;; unittest bin:dataN[7]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00"
  )
  "length out of bounds"
)

;; unittest bin:dataN[8]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00\41"
  )
  "length out of bounds"
)

;; unittest bin:dataN[9]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00\41\00"
  )
  "length out of bounds"
)

;; unittest bin:dataN[10]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00\41\00\0b"
  )
  "length out of bounds"
)

;; unittest bin:dataN[11]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00\41\00\0b\03"
  )
  "length out of bounds"
)

;; unittest bin:dataN[12]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00\41\00\0b\03\61"
  )
  "length out of bounds"
)

;; unittest bin:dataN[13]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00\41\00\0b\03\61\62"
  )
  "length out of bounds"
)

;; unittest bin:dataN[14]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00\41\00\0b\03\61\62\63"
  )
  "length out of bounds"
)

;; unittest bin:dataN[15]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00\41\00\0b\03\61\62\63\00"
  )
  "length out of bounds"
)

;; unittest bin:dataN[16]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00\41\00\0b\03\61\62\63\00\41"
  )
  "length out of bounds"
)

;; unittest bin:dataN[17]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00\41\00\0b\03\61\62\63\00\41\00"
  )
  "length out of bounds"
)

;; unittest bin:dataN[18]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00\41\00\0b\03\61\62\63\00\41\00\0b"
  )
  "length out of bounds"
)

;; unittest bin:dataN[19]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00\41\00\0b\03\61\62\63\00\41\00\0b\03"
  )
  "length out of bounds"
)

;; unittest bin:dataN[20]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00\41\00\0b\03\61\62\63\00\41\00\0b\03\61"
  )
  "length out of bounds"
)

;; unittest bin:dataN[21]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00\41\00\0b\03\61\62\63\00\41\00\0b\03\61\62"
  )
  "length out of bounds"
)

;; unittest bin:dataN[22]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00\41\00\0b\03\61\62\63\00\41\00\0b\03\61\62\63"
  )
  "length out of bounds"
)

;; unittest bin:dataN[23]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00\41\00\0b\03\61\62\63\00\41\00\0b\03\61\62\63"
    "\00"
  )
  "length out of bounds"
)

;; unittest bin:dataN[24]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00\41\00\0b\03\61\62\63\00\41\00\0b\03\61\62\63"
    "\00\41"
  )
  "length out of bounds"
)

;; unittest bin:dataN[25]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00\41\00\0b\03\61\62\63\00\41\00\0b\03\61\62\63"
    "\00\41\00"
  )
  "length out of bounds"
)

;; unittest bin:dataN[26]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00\41\00\0b\03\61\62\63\00\41\00\0b\03\61\62\63"
    "\00\41\00\0b"
  )
  "length out of bounds"
)

;; unittest bin:dataN[27]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00\41\00\0b\03\61\62\63\00\41\00\0b\03\61\62\63"
    "\00\41\00\0b\03"
  )
  "length out of bounds"
)

;; unittest bin:dataN[28]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00\41\00\0b\03\61\62\63\00\41\00\0b\03\61\62\63"
    "\00\41\00\0b\03\61"
  )
  "length out of bounds"
)

;; unittest bin:dataN[29]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\19\03"
    "\00\41\00\0b\03\61\62\63\00\41\00\0b\03\61\62\63"
    "\00\41\00\0b\03\61\62"
  )
  "unexpected end of section or function"
)

;; unittest bin:dataN[30]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\02\00"
    "\63"
  )
  "section size mismatch"
)

;; unittest bin:dataN[31]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\0a\01"
    "\00\41\00\0b\03\61\62\63\63"
  )
  "section size mismatch"
)

;; unittest bin:dataN[32]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\12\02"
    "\00\41\00\0b\03\61\62\63\00\41\00\0b\03\61\62\63"
    "\63"
  )
  "section size mismatch"
)

;; unittest bin:dataN[33]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\1a\03"
    "\00\41\00\0b\03\61\62\63\00\41\00\0b\03\61\62\63"
    "\00\41\00\0b\03\61\62\63\63"
  )
  "section size mismatch"
)

