;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:sect_custom2[1]: MALFORMED INVALID_UTF8_STRING [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\00\02\01\99"
  )
  "malformed UTF-8 encoding"
)

