;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:funcsN[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\01"
  "\00\0a\01\00"
)

;; unittest bin:funcsN[2]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\02"
    "\00\63\0a\01\00"
  )
  "section size mismatch"
)

;; unittest bin:funcsN[3]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\00"
    "\0a\01\00"
  )
  "length out of bounds"
)

;; unittest bin:funcsN[4]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\02"
  "\01\00\0a\04\01\02\00\0b"
)

;; unittest bin:funcsN[5]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\03"
    "\01\00\63\0a\04\01\02\00\0b"
  )
  "section size mismatch"
)

;; unittest bin:funcsN[6]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\01"
    "\01\0a\04\01\02\00\0b"
  )
  "section size mismatch"
)

;; unittest bin:funcsN[7]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\03"
  "\02\00\00\0a\07\02\02\00\0b\02\00\0b"
)

;; unittest bin:funcsN[8]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\04"
    "\02\00\00\63\0a\07\02\02\00\0b\02\00\0b"
  )
  "section size mismatch"
)

;; unittest bin:funcsN[9]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\02"
    "\02\00\0a\07\02\02\00\0b\02\00\0b"
  )
  "section size mismatch"
)

;; unittest bin:funcsN[10]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\04"
  "\03\00\00\00\0a\0a\03\02\00\0b\02\00\0b\02\00\0b"
)

;; unittest bin:funcsN[11]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\05"
    "\03\00\00\00\63\0a\0a\03\02\00\0b\02\00\0b\02\00"
    "\0b"
  )
  "section size mismatch"
)

;; unittest bin:funcsN[12]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\03"
    "\03\00\00\0a\0a\03\02\00\0b\02\00\0b\02\00\0b"
  )
  "section size mismatch"
)

