;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:recgrp0[1]: MALFORMED INVALID_TYPE [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\87\80\80\80\00\01\4e"
    "\01\60\00\01\7f"
  )
  ""
)

