;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:invalid[1]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\0e"
  )
  "malformed section id"
)

;; unittest bin:invalid[2]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\0f"
  )
  "malformed section id"
)

;; unittest bin:invalid[3]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\10"
  )
  "malformed section id"
)

;; unittest bin:invalid[4]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\11"
  )
  "malformed section id"
)

;; unittest bin:invalid[5]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\12"
  )
  "malformed section id"
)

;; unittest bin:invalid[6]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\13"
  )
  "malformed section id"
)

;; unittest bin:invalid[7]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\14"
  )
  "malformed section id"
)

;; unittest bin:invalid[8]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\15"
  )
  "malformed section id"
)

;; unittest bin:invalid[9]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\16"
  )
  "malformed section id"
)

;; unittest bin:invalid[10]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\17"
  )
  "malformed section id"
)

;; unittest bin:invalid[11]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\18"
  )
  "malformed section id"
)

;; unittest bin:invalid[12]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\19"
  )
  "malformed section id"
)

;; unittest bin:invalid[13]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\1a"
  )
  "malformed section id"
)

;; unittest bin:invalid[14]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\1b"
  )
  "malformed section id"
)

;; unittest bin:invalid[15]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\1c"
  )
  "malformed section id"
)

;; unittest bin:invalid[16]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\1d"
  )
  "malformed section id"
)

;; unittest bin:invalid[17]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\1e"
  )
  "malformed section id"
)

;; unittest bin:invalid[18]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\1f"
  )
  "malformed section id"
)

;; unittest bin:invalid[19]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\20"
  )
  "malformed section id"
)

;; unittest bin:invalid[20]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\21"
  )
  "malformed section id"
)

;; unittest bin:invalid[21]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\22"
  )
  "malformed section id"
)

;; unittest bin:invalid[22]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\23"
  )
  "malformed section id"
)

;; unittest bin:invalid[23]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\24"
  )
  "malformed section id"
)

;; unittest bin:invalid[24]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\25"
  )
  "malformed section id"
)

;; unittest bin:invalid[25]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\26"
  )
  "malformed section id"
)

;; unittest bin:invalid[26]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\27"
  )
  "malformed section id"
)

;; unittest bin:invalid[27]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\28"
  )
  "malformed section id"
)

;; unittest bin:invalid[28]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\29"
  )
  "malformed section id"
)

;; unittest bin:invalid[29]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\2a"
  )
  "malformed section id"
)

;; unittest bin:invalid[30]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\2b"
  )
  "malformed section id"
)

;; unittest bin:invalid[31]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\2c"
  )
  "malformed section id"
)

;; unittest bin:invalid[32]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\2d"
  )
  "malformed section id"
)

;; unittest bin:invalid[33]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\2e"
  )
  "malformed section id"
)

;; unittest bin:invalid[34]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\2f"
  )
  "malformed section id"
)

;; unittest bin:invalid[35]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\30"
  )
  "malformed section id"
)

;; unittest bin:invalid[36]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\31"
  )
  "malformed section id"
)

;; unittest bin:invalid[37]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\32"
  )
  "malformed section id"
)

;; unittest bin:invalid[38]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\33"
  )
  "malformed section id"
)

;; unittest bin:invalid[39]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\34"
  )
  "malformed section id"
)

;; unittest bin:invalid[40]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\35"
  )
  "malformed section id"
)

;; unittest bin:invalid[41]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\36"
  )
  "malformed section id"
)

;; unittest bin:invalid[42]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\37"
  )
  "malformed section id"
)

;; unittest bin:invalid[43]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\38"
  )
  "malformed section id"
)

;; unittest bin:invalid[44]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\39"
  )
  "malformed section id"
)

;; unittest bin:invalid[45]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\3a"
  )
  "malformed section id"
)

;; unittest bin:invalid[46]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\3b"
  )
  "malformed section id"
)

;; unittest bin:invalid[47]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\3c"
  )
  "malformed section id"
)

;; unittest bin:invalid[48]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\3d"
  )
  "malformed section id"
)

;; unittest bin:invalid[49]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\3e"
  )
  "malformed section id"
)

;; unittest bin:invalid[50]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\3f"
  )
  "malformed section id"
)

;; unittest bin:invalid[51]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\40"
  )
  "malformed section id"
)

;; unittest bin:invalid[52]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\41"
  )
  "malformed section id"
)

;; unittest bin:invalid[53]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\42"
  )
  "malformed section id"
)

;; unittest bin:invalid[54]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\43"
  )
  "malformed section id"
)

;; unittest bin:invalid[55]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\44"
  )
  "malformed section id"
)

;; unittest bin:invalid[56]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\45"
  )
  "malformed section id"
)

;; unittest bin:invalid[57]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\46"
  )
  "malformed section id"
)

;; unittest bin:invalid[58]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\47"
  )
  "malformed section id"
)

;; unittest bin:invalid[59]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\48"
  )
  "malformed section id"
)

;; unittest bin:invalid[60]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\49"
  )
  "malformed section id"
)

;; unittest bin:invalid[61]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\4a"
  )
  "malformed section id"
)

;; unittest bin:invalid[62]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\4b"
  )
  "malformed section id"
)

;; unittest bin:invalid[63]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\4c"
  )
  "malformed section id"
)

;; unittest bin:invalid[64]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\4d"
  )
  "malformed section id"
)

;; unittest bin:invalid[65]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\4e"
  )
  "malformed section id"
)

;; unittest bin:invalid[66]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\4f"
  )
  "malformed section id"
)

;; unittest bin:invalid[67]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\50"
  )
  "malformed section id"
)

;; unittest bin:invalid[68]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\51"
  )
  "malformed section id"
)

;; unittest bin:invalid[69]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\52"
  )
  "malformed section id"
)

;; unittest bin:invalid[70]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\53"
  )
  "malformed section id"
)

;; unittest bin:invalid[71]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\54"
  )
  "malformed section id"
)

;; unittest bin:invalid[72]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\55"
  )
  "malformed section id"
)

;; unittest bin:invalid[73]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\56"
  )
  "malformed section id"
)

;; unittest bin:invalid[74]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\57"
  )
  "malformed section id"
)

;; unittest bin:invalid[75]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\58"
  )
  "malformed section id"
)

;; unittest bin:invalid[76]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\59"
  )
  "malformed section id"
)

;; unittest bin:invalid[77]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\5a"
  )
  "malformed section id"
)

;; unittest bin:invalid[78]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\5b"
  )
  "malformed section id"
)

;; unittest bin:invalid[79]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\5c"
  )
  "malformed section id"
)

;; unittest bin:invalid[80]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\5d"
  )
  "malformed section id"
)

;; unittest bin:invalid[81]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\5e"
  )
  "malformed section id"
)

;; unittest bin:invalid[82]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\5f"
  )
  "malformed section id"
)

;; unittest bin:invalid[83]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\60"
  )
  "malformed section id"
)

;; unittest bin:invalid[84]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\61"
  )
  "malformed section id"
)

;; unittest bin:invalid[85]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\62"
  )
  "malformed section id"
)

;; unittest bin:invalid[86]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\63"
  )
  "malformed section id"
)

;; unittest bin:invalid[87]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\64"
  )
  "malformed section id"
)

;; unittest bin:invalid[88]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\65"
  )
  "malformed section id"
)

;; unittest bin:invalid[89]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\66"
  )
  "malformed section id"
)

;; unittest bin:invalid[90]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\67"
  )
  "malformed section id"
)

;; unittest bin:invalid[91]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\68"
  )
  "malformed section id"
)

;; unittest bin:invalid[92]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\69"
  )
  "malformed section id"
)

;; unittest bin:invalid[93]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\6a"
  )
  "malformed section id"
)

;; unittest bin:invalid[94]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\6b"
  )
  "malformed section id"
)

;; unittest bin:invalid[95]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\6c"
  )
  "malformed section id"
)

;; unittest bin:invalid[96]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\6d"
  )
  "malformed section id"
)

;; unittest bin:invalid[97]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\6e"
  )
  "malformed section id"
)

;; unittest bin:invalid[98]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\6f"
  )
  "malformed section id"
)

;; unittest bin:invalid[99]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\70"
  )
  "malformed section id"
)

;; unittest bin:invalid[100]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\71"
  )
  "malformed section id"
)

;; unittest bin:invalid[101]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\72"
  )
  "malformed section id"
)

;; unittest bin:invalid[102]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\73"
  )
  "malformed section id"
)

;; unittest bin:invalid[103]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\74"
  )
  "malformed section id"
)

;; unittest bin:invalid[104]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\75"
  )
  "malformed section id"
)

;; unittest bin:invalid[105]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\76"
  )
  "malformed section id"
)

;; unittest bin:invalid[106]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\77"
  )
  "malformed section id"
)

;; unittest bin:invalid[107]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\78"
  )
  "malformed section id"
)

;; unittest bin:invalid[108]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\79"
  )
  "malformed section id"
)

;; unittest bin:invalid[109]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\7a"
  )
  "malformed section id"
)

;; unittest bin:invalid[110]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\7b"
  )
  "malformed section id"
)

;; unittest bin:invalid[111]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\7c"
  )
  "malformed section id"
)

;; unittest bin:invalid[112]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\7d"
  )
  "malformed section id"
)

;; unittest bin:invalid[113]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\7e"
  )
  "malformed section id"
)

;; unittest bin:invalid[114]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\7f"
  )
  "malformed section id"
)

;; unittest bin:invalid[115]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\80"
  )
  "malformed section id"
)

;; unittest bin:invalid[116]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\81"
  )
  "malformed section id"
)

;; unittest bin:invalid[117]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\82"
  )
  "malformed section id"
)

;; unittest bin:invalid[118]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\83"
  )
  "malformed section id"
)

;; unittest bin:invalid[119]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\84"
  )
  "malformed section id"
)

;; unittest bin:invalid[120]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\85"
  )
  "malformed section id"
)

;; unittest bin:invalid[121]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\86"
  )
  "malformed section id"
)

;; unittest bin:invalid[122]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\87"
  )
  "malformed section id"
)

;; unittest bin:invalid[123]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\88"
  )
  "malformed section id"
)

;; unittest bin:invalid[124]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\89"
  )
  "malformed section id"
)

;; unittest bin:invalid[125]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\8a"
  )
  "malformed section id"
)

;; unittest bin:invalid[126]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\8b"
  )
  "malformed section id"
)

;; unittest bin:invalid[127]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\8c"
  )
  "malformed section id"
)

;; unittest bin:invalid[128]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\8d"
  )
  "malformed section id"
)

;; unittest bin:invalid[129]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\8e"
  )
  "malformed section id"
)

;; unittest bin:invalid[130]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\8f"
  )
  "malformed section id"
)

;; unittest bin:invalid[131]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\90"
  )
  "malformed section id"
)

;; unittest bin:invalid[132]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\91"
  )
  "malformed section id"
)

;; unittest bin:invalid[133]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\92"
  )
  "malformed section id"
)

;; unittest bin:invalid[134]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\93"
  )
  "malformed section id"
)

;; unittest bin:invalid[135]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\94"
  )
  "malformed section id"
)

;; unittest bin:invalid[136]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\95"
  )
  "malformed section id"
)

;; unittest bin:invalid[137]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\96"
  )
  "malformed section id"
)

;; unittest bin:invalid[138]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\97"
  )
  "malformed section id"
)

;; unittest bin:invalid[139]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\98"
  )
  "malformed section id"
)

;; unittest bin:invalid[140]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\99"
  )
  "malformed section id"
)

;; unittest bin:invalid[141]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\9a"
  )
  "malformed section id"
)

;; unittest bin:invalid[142]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\9b"
  )
  "malformed section id"
)

;; unittest bin:invalid[143]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\9c"
  )
  "malformed section id"
)

;; unittest bin:invalid[144]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\9d"
  )
  "malformed section id"
)

;; unittest bin:invalid[145]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\9e"
  )
  "malformed section id"
)

;; unittest bin:invalid[146]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\9f"
  )
  "malformed section id"
)

;; unittest bin:invalid[147]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\a0"
  )
  "malformed section id"
)

;; unittest bin:invalid[148]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\a1"
  )
  "malformed section id"
)

;; unittest bin:invalid[149]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\a2"
  )
  "malformed section id"
)

;; unittest bin:invalid[150]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\a3"
  )
  "malformed section id"
)

;; unittest bin:invalid[151]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\a4"
  )
  "malformed section id"
)

;; unittest bin:invalid[152]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\a5"
  )
  "malformed section id"
)

;; unittest bin:invalid[153]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\a6"
  )
  "malformed section id"
)

;; unittest bin:invalid[154]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\a7"
  )
  "malformed section id"
)

;; unittest bin:invalid[155]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\a8"
  )
  "malformed section id"
)

;; unittest bin:invalid[156]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\a9"
  )
  "malformed section id"
)

;; unittest bin:invalid[157]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\aa"
  )
  "malformed section id"
)

;; unittest bin:invalid[158]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\ab"
  )
  "malformed section id"
)

;; unittest bin:invalid[159]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\ac"
  )
  "malformed section id"
)

;; unittest bin:invalid[160]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\ad"
  )
  "malformed section id"
)

;; unittest bin:invalid[161]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\ae"
  )
  "malformed section id"
)

;; unittest bin:invalid[162]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\af"
  )
  "malformed section id"
)

;; unittest bin:invalid[163]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\b0"
  )
  "malformed section id"
)

;; unittest bin:invalid[164]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\b1"
  )
  "malformed section id"
)

;; unittest bin:invalid[165]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\b2"
  )
  "malformed section id"
)

;; unittest bin:invalid[166]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\b3"
  )
  "malformed section id"
)

;; unittest bin:invalid[167]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\b4"
  )
  "malformed section id"
)

;; unittest bin:invalid[168]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\b5"
  )
  "malformed section id"
)

;; unittest bin:invalid[169]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\b6"
  )
  "malformed section id"
)

;; unittest bin:invalid[170]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\b7"
  )
  "malformed section id"
)

;; unittest bin:invalid[171]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\b8"
  )
  "malformed section id"
)

;; unittest bin:invalid[172]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\b9"
  )
  "malformed section id"
)

;; unittest bin:invalid[173]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\ba"
  )
  "malformed section id"
)

;; unittest bin:invalid[174]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\bb"
  )
  "malformed section id"
)

;; unittest bin:invalid[175]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\bc"
  )
  "malformed section id"
)

;; unittest bin:invalid[176]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\bd"
  )
  "malformed section id"
)

;; unittest bin:invalid[177]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\be"
  )
  "malformed section id"
)

;; unittest bin:invalid[178]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\bf"
  )
  "malformed section id"
)

;; unittest bin:invalid[179]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\c0"
  )
  "malformed section id"
)

;; unittest bin:invalid[180]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\c1"
  )
  "malformed section id"
)

;; unittest bin:invalid[181]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\c2"
  )
  "malformed section id"
)

;; unittest bin:invalid[182]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\c3"
  )
  "malformed section id"
)

;; unittest bin:invalid[183]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\c4"
  )
  "malformed section id"
)

;; unittest bin:invalid[184]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\c5"
  )
  "malformed section id"
)

;; unittest bin:invalid[185]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\c6"
  )
  "malformed section id"
)

;; unittest bin:invalid[186]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\c7"
  )
  "malformed section id"
)

;; unittest bin:invalid[187]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\c8"
  )
  "malformed section id"
)

;; unittest bin:invalid[188]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\c9"
  )
  "malformed section id"
)

;; unittest bin:invalid[189]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\ca"
  )
  "malformed section id"
)

;; unittest bin:invalid[190]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\cb"
  )
  "malformed section id"
)

;; unittest bin:invalid[191]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\cc"
  )
  "malformed section id"
)

;; unittest bin:invalid[192]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\cd"
  )
  "malformed section id"
)

;; unittest bin:invalid[193]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\ce"
  )
  "malformed section id"
)

;; unittest bin:invalid[194]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\cf"
  )
  "malformed section id"
)

;; unittest bin:invalid[195]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\d0"
  )
  "malformed section id"
)

;; unittest bin:invalid[196]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\d1"
  )
  "malformed section id"
)

;; unittest bin:invalid[197]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\d2"
  )
  "malformed section id"
)

;; unittest bin:invalid[198]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\d3"
  )
  "malformed section id"
)

;; unittest bin:invalid[199]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\d4"
  )
  "malformed section id"
)

;; unittest bin:invalid[200]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\d5"
  )
  "malformed section id"
)

;; unittest bin:invalid[201]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\d6"
  )
  "malformed section id"
)

;; unittest bin:invalid[202]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\d7"
  )
  "malformed section id"
)

;; unittest bin:invalid[203]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\d8"
  )
  "malformed section id"
)

;; unittest bin:invalid[204]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\d9"
  )
  "malformed section id"
)

;; unittest bin:invalid[205]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\da"
  )
  "malformed section id"
)

;; unittest bin:invalid[206]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\db"
  )
  "malformed section id"
)

;; unittest bin:invalid[207]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\dc"
  )
  "malformed section id"
)

;; unittest bin:invalid[208]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\dd"
  )
  "malformed section id"
)

;; unittest bin:invalid[209]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\de"
  )
  "malformed section id"
)

;; unittest bin:invalid[210]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\df"
  )
  "malformed section id"
)

;; unittest bin:invalid[211]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\e0"
  )
  "malformed section id"
)

;; unittest bin:invalid[212]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\e1"
  )
  "malformed section id"
)

;; unittest bin:invalid[213]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\e2"
  )
  "malformed section id"
)

;; unittest bin:invalid[214]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\e3"
  )
  "malformed section id"
)

;; unittest bin:invalid[215]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\e4"
  )
  "malformed section id"
)

;; unittest bin:invalid[216]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\e5"
  )
  "malformed section id"
)

;; unittest bin:invalid[217]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\e6"
  )
  "malformed section id"
)

;; unittest bin:invalid[218]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\e7"
  )
  "malformed section id"
)

;; unittest bin:invalid[219]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\e8"
  )
  "malformed section id"
)

;; unittest bin:invalid[220]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\e9"
  )
  "malformed section id"
)

;; unittest bin:invalid[221]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\ea"
  )
  "malformed section id"
)

;; unittest bin:invalid[222]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\eb"
  )
  "malformed section id"
)

;; unittest bin:invalid[223]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\ec"
  )
  "malformed section id"
)

;; unittest bin:invalid[224]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\ed"
  )
  "malformed section id"
)

;; unittest bin:invalid[225]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\ee"
  )
  "malformed section id"
)

;; unittest bin:invalid[226]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\ef"
  )
  "malformed section id"
)

;; unittest bin:invalid[227]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\f0"
  )
  "malformed section id"
)

;; unittest bin:invalid[228]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\f1"
  )
  "malformed section id"
)

;; unittest bin:invalid[229]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\f2"
  )
  "malformed section id"
)

;; unittest bin:invalid[230]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\f3"
  )
  "malformed section id"
)

;; unittest bin:invalid[231]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\f4"
  )
  "malformed section id"
)

;; unittest bin:invalid[232]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\f5"
  )
  "malformed section id"
)

;; unittest bin:invalid[233]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\f6"
  )
  "malformed section id"
)

;; unittest bin:invalid[234]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\f7"
  )
  "malformed section id"
)

;; unittest bin:invalid[235]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\f8"
  )
  "malformed section id"
)

;; unittest bin:invalid[236]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\f9"
  )
  "malformed section id"
)

;; unittest bin:invalid[237]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\fa"
  )
  "malformed section id"
)

;; unittest bin:invalid[238]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\fb"
  )
  "malformed section id"
)

;; unittest bin:invalid[239]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\fc"
  )
  "malformed section id"
)

;; unittest bin:invalid[240]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\fd"
  )
  "malformed section id"
)

;; unittest bin:invalid[241]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\fe"
  )
  "malformed section id"
)

;; unittest bin:invalid[242]: MALFORMED INVALID_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\ff"
  )
  "malformed section id"
)

