;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:funcs0[1]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\03\82\80\80\80\00\01\00"
  )
  ""
)

;; unittest bin:funcs0[2]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\03\82\80\80\80\00\01\01"
  )
  ""
)

;; unittest bin:funcs0[3]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\03\82\80\80\80\00\01\04"
  )
  ""
)

;; unittest bin:funcs0[4]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\82"
  "\80\80\80\00\01\00\0a\04\01\02\00\0b"
)

;; unittest bin:funcs0[5]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\82"
    "\80\80\80\00\01\01\0a\04\01\02\00\0b"
  )
  "unknown type 1"
)

;; unittest bin:funcs0[6]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\82"
    "\80\80\80\00\01\04\0a\04\01\02\00\0b"
  )
  "unknown type 4"
)

;; unittest bin:funcs0[7]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\81"
    "\80\80\80\00\01\0a\04\01\02\00\0b"
  )
  "section size mismatch"
)

