;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:table_limits[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\04\87\80\80\80\00\01\70"
  "\00\ff\ac\e2\04"
)

;; unittest bin:table_limits[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\04\88\80\80\80\00\01\70"
  "\01\00\ff\ac\e2\04"
)

;; unittest bin:table_limits[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\04\87\80\80\80\00\01\70"
  "\00\80\ad\e2\04"
)

;; unittest bin:table_limits[4]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\04\88\80\80\80\00\01\70"
  "\01\00\80\ad\e2\04"
)

;; skipped: EXCEEDED_LIMIT is an engine-specific limit
;; skipped: EXCEEDED_LIMIT is an engine-specific limit
