;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:start0[1]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\08\81\80\80\80\00\00"
  )
  "unknown function 0"
)

;; unittest bin:start0[2]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\08\81\80\80\80\00\01"
  )
  "unknown function 1"
)

;; unittest bin:start0[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\02"
  "\01\00\08\81\80\80\80\00\00\0a\04\01\02\00\0b"
)

;; unittest bin:start0[4]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\02"
    "\01\00\08\81\80\80\80\00\01\0a\04\01\02\00\0b"
  )
  "unknown function 1"
)

;; unittest bin:start0[5]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\02"
    "\01\00\08\82\80\80\80\00\00\00\0a\04\01\02\00\0b"
  )
  "section size mismatch"
)

