;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:data0[1]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\0b\86\80\80\80\00\01\00"
    "\41\00\0b\00"
  )
  "unknown memory 0"
)

;; unittest bin:data0[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\86\80"
  "\80\80\00\01\00\41\00\0b\00"
)

;; unittest bin:data0[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\88\80"
  "\80\80\00\01\00\41\00\0b\02\63\58"
)

;; unittest bin:data0[4]: INVALID TYPE_MISMATCH [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\86\80"
    "\80\80\00\01\00\42\00\0b\00"
  )
  "type mismatch: instruction requires [i32] but stack has [i64]"
)

;; unittest bin:data0[5]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\87\80"
    "\80\80\00\01\00\41\00\0b\ec\3c"
  )
  "length out of bounds"
)

;; unittest bin:data0[6]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\8a\80"
    "\80\80\00\01\00\41\00\0b\ff\ff\ff\ff\03"
  )
  "length out of bounds"
)

;; unittest bin:data0[7]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\0b\8a\80"
    "\80\80\00\01\00\41\00\0b\80\80\80\80\04"
  )
  "length out of bounds"
)

;; skipped: EXCEEDED_LIMIT is an engine-specific limit
