;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:version[1]: MALFORMED INVALID_HEADER [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\ff\00\00\00"
  )
  "unknown binary version"
)

;; unittest bin:version[2]: MALFORMED INVALID_HEADER [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\ff\00\00"
  )
  "unknown binary version"
)

;; unittest bin:version[3]: MALFORMED INVALID_HEADER [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\ff\00"
  )
  "unknown binary version"
)

;; unittest bin:version[4]: MALFORMED INVALID_HEADER [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\ff"
  )
  "unknown binary version"
)

