;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:func_ref_types1[1]: MALFORMED INVALID_TYPE [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\8a\80\80\80\00\02\60"
    "\00\01\64\01\60\00\01\7f"
  )
  ""
)

