;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:imports1[1]: MALFORMED INVALID_IMPORT_KIND [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\86\80\80\80\00\01\01"
    "\50\01\6a\05"
  )
  "malformed import kind"
)

;; unittest bin:imports1[2]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\02\87\80\80\80\00\01\01"
    "\4d\01\67\00\00"
  )
  "unknown type 0"
)

;; skipped: EXCEEDED_LIMIT is an engine-specific limit
;; unittest bin:imports1[3]: MALFORMED INVALID_TYPE [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\88\80\80\80\00\01\01"
    "\50\01\6a\03\2c\00"
  )
  "malformed reference type"
)

;; unittest bin:imports1[4]: MALFORMED INVALID_GLOBAL_FLAGS [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\88\80\80\80\00\01\01"
    "\50\01\6a\03\7f\13"
  )
  "malformed mutability"
)

