;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:globals0[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\06\86\80\80\80\00\01\7f"
  "\00\41\01\0b"
)

;; unittest bin:globals0[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\06\86\80\80\80\00\01\7f"
  "\01\41\01\0b"
)

;; unittest bin:globals0[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\06\86\80\80\80\00\01\7e"
  "\00\42\02\0b"
)

;; unittest bin:globals0[4]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\06\89\80\80\80\00\01\7d"
  "\00\43\00\00\00\00\0b"
)

;; unittest bin:globals0[5]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\06\8d\80\80\80\00\01\7c"
  "\00\44\00\00\00\00\00\00\00\00\0b"
)

;; unittest bin:globals0[6]: MALFORMED INVALID_TYPE [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\84\80\80\80\00\01\2c"
    "\00\0b"
  )
  "malformed reference type"
)

;; unittest bin:globals0[7]: MALFORMED INVALID_GLOBAL_FLAGS [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\86\80\80\80\00\01\7f"
    "\02\41\01\0b"
  )
  "malformed mutability"
)

;; unittest bin:globals0[8]: INVALID TYPE_MISMATCH [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\06\86\80\80\80\00\01\7d"
    "\00\41\01\0b"
  )
  "type mismatch: instruction requires [f32] but stack has [i32]"
)

;; unittest bin:globals0[9]: INVALID TYPE_MISMATCH [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\06\86\80\80\80\00\01\7c"
    "\00\42\02\0b"
  )
  "type mismatch: instruction requires [f64] but stack has [i64]"
)

;; unittest bin:globals0[10]: INVALID TYPE_MISMATCH [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\06\89\80\80\80\00\01\7f"
    "\00\43\00\00\00\00\0b"
  )
  "type mismatch: instruction requires [i32] but stack has [f32]"
)

;; unittest bin:globals0[11]: INVALID TYPE_MISMATCH [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\06\8d\80\80\80\00\01\7e"
    "\00\44\00\00\00\00\00\00\00\00\0b"
  )
  "type mismatch: instruction requires [i64] but stack has [f64]"
)

