;; generated by test/regress/binary/record.sh; do not edit

;; skipped: needs the non-standard extension(s) repeat-sections
;; skipped: needs the non-standard extension(s) repeat-sections
;; skipped: needs the non-standard extension(s) repeat-sections
