;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:code1[1]: MALFORMED FUNC_COUNT_MISMATCH [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\84"
    "\80\80\80\00\03\00\00\00\0a\81\80\80\80\00\00"
  )
  "function and code section have inconsistent lengths"
)

;; unittest bin:code1[2]: MALFORMED FUNC_COUNT_MISMATCH [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\84"
    "\80\80\80\00\03\00\00\00\0a\82\80\80\80\00\01\00"
  )
  "unexpected end of section or function"
)

;; unittest bin:code1[3]: MALFORMED FUNC_COUNT_MISMATCH [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\84"
    "\80\80\80\00\03\00\00\00\0a\83\80\80\80\00\02\00"
    "\00"
  )
  "unexpected end of section or function"
)

;; unittest bin:code1[4]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\84"
  "\80\80\80\00\03\00\00\00\0a\8a\80\80\80\00\03\02"
  "\00\0b\02\00\0b\02\00\0b"
)

;; unittest bin:code1[5]: MALFORMED FUNC_COUNT_MISMATCH [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\84"
    "\80\80\80\00\03\00\00\00\0a\85\80\80\80\00\04\00"
    "\00\00\00"
  )
  "unexpected end of section or function"
)

