;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:code_missing[1]: MALFORMED FUNC_COUNT_MISMATCH [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\82"
    "\80\80\80\00\01\00"
  )
  "function and code section have inconsistent lengths"
)

