;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:types1[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\01\00"
)

;; unittest bin:types1[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00"
)

;; unittest bin:types1[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\05\01\60\00\01\7d"
)

;; unittest bin:types1[4]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\05\01\60\01\7f\00"
)

;; unittest bin:types1[5]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\06\01\60\01\7f\01\7d"
)

;; unittest bin:types1[6]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\06\01\60\02\7f\7f\00"
)

;; unittest bin:types1[7]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\07\01\60\02\7f\7f\01"
  "\7d"
)

;; unittest bin:types1[8]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\07\02\60\00\00\60\00"
  "\00"
)

;; unittest bin:types1[9]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\09\02\60\00\01\7d\60"
  "\00\01\7d"
)

;; unittest bin:types1[10]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\09\02\60\01\7f\00\60"
  "\01\7f\00"
)

;; unittest bin:types1[11]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\0b\02\60\01\7f\01\7d"
  "\60\01\7f\01\7d"
)

;; unittest bin:types1[12]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\0b\02\60\02\7f\7f\00"
  "\60\02\7f\7f\00"
)

;; unittest bin:types1[13]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\0d\02\60\02\7f\7f\01"
  "\7d\60\02\7f\7f\01\7d"
)

