;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:sub2[1]: MALFORMED INVALID_TYPE [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\8e\80\80\80\00\02\50"
    "\00\60\00\01\7f\50\01\00\60\00\01\7f"
  )
  ""
)

