;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:globalsN[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\06\01\00"
)

;; unittest bin:globalsN[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
)

;; unittest bin:globalsN[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\06\0b\02\7f\00\41\00\0b"
  "\7f\00\41\00\0b"
)

;; unittest bin:globalsN[4]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\06\10\03\7f\00\41\00\0b"
  "\7f\00\41\00\0b\7f\00\41\00\0b"
)

;; unittest bin:globalsN[5]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\10"
  )
  "length out of bounds"
)

;; unittest bin:globalsN[6]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\10\03"
  )
  "length out of bounds"
)

;; unittest bin:globalsN[7]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\10\03\7f"
  )
  "length out of bounds"
)

;; unittest bin:globalsN[8]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\10\03\7f\00"
  )
  "length out of bounds"
)

;; unittest bin:globalsN[9]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\10\03\7f\00\41"
  )
  "length out of bounds"
)

;; unittest bin:globalsN[10]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\10\03\7f\00\41\00"
  )
  "length out of bounds"
)

;; unittest bin:globalsN[11]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\10\03\7f\00\41\00\0b"
  )
  "length out of bounds"
)

;; unittest bin:globalsN[12]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\10\03\7f\00\41\00\0b"
    "\7f"
  )
  "length out of bounds"
)

;; unittest bin:globalsN[13]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\10\03\7f\00\41\00\0b"
    "\7f\00"
  )
  "length out of bounds"
)

;; unittest bin:globalsN[14]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\10\03\7f\00\41\00\0b"
    "\7f\00\41"
  )
  "length out of bounds"
)

;; unittest bin:globalsN[15]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\10\03\7f\00\41\00\0b"
    "\7f\00\41\00"
  )
  "length out of bounds"
)

;; unittest bin:globalsN[16]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\10\03\7f\00\41\00\0b"
    "\7f\00\41\00\0b"
  )
  "length out of bounds"
)

;; unittest bin:globalsN[17]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\10\03\7f\00\41\00\0b"
    "\7f\00\41\00\0b\7f"
  )
  "length out of bounds"
)

;; unittest bin:globalsN[18]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\10\03\7f\00\41\00\0b"
    "\7f\00\41\00\0b\7f\00"
  )
  "length out of bounds"
)

;; unittest bin:globalsN[19]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\10\03\7f\00\41\00\0b"
    "\7f\00\41\00\0b\7f\00\41"
  )
  "length out of bounds"
)

;; unittest bin:globalsN[20]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\10\03\7f\00\41\00\0b"
    "\7f\00\41\00\0b\7f\00\41\00"
  )
  "unexpected end of section or function"
)

;; unittest bin:globalsN[21]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\02\00\63"
  )
  "section size mismatch"
)

;; unittest bin:globalsN[22]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\07\01\7f\00\41\00\0b"
    "\63"
  )
  "section size mismatch"
)

;; unittest bin:globalsN[23]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\0c\02\7f\00\41\00\0b"
    "\7f\00\41\00\0b\63"
  )
  "section size mismatch"
)

;; unittest bin:globalsN[24]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\11\03\7f\00\41\00\0b"
    "\7f\00\41\00\0b\7f\00\41\00\0b\63"
  )
  "section size mismatch"
)

