;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:elementsN[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
  "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\01\00"
)

;; unittest bin:elementsN[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
  "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\09\01"
  "\00\41\00\0b\03\00\00\00"
)

;; unittest bin:elementsN[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
  "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\11\02"
  "\00\41\00\0b\03\00\00\00\00\41\00\0b\03\00\00\00"
)

;; unittest bin:elementsN[4]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
  "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
  "\00\41\00\0b\03\00\00\00\00\41\00\0b\03\00\00\00"
  "\00\41\00\0b\03\00\00\00"
)

;; unittest bin:elementsN[5]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[6]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[7]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[8]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00\41"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[9]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00\41\00"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[10]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00\41\00\0b"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[11]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00\41\00\0b\03"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[12]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00\41\00\0b\03\00"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[13]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00\41\00\0b\03\00\00"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[14]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00\41\00\0b\03\00\00\00"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[15]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00\41\00\0b\03\00\00\00\00"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[16]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00\41\00\0b\03\00\00\00\00\41"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[17]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00\41\00\0b\03\00\00\00\00\41\00"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[18]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00\41\00\0b\03\00\00\00\00\41\00\0b"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[19]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00\41\00\0b\03\00\00\00\00\41\00\0b\03"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[20]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00\41\00\0b\03\00\00\00\00\41\00\0b\03\00"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[21]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00\41\00\0b\03\00\00\00\00\41\00\0b\03\00\00"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[22]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00\41\00\0b\03\00\00\00\00\41\00\0b\03\00\00\00"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[23]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00\41\00\0b\03\00\00\00\00\41\00\0b\03\00\00\00"
    "\00"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[24]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00\41\00\0b\03\00\00\00\00\41\00\0b\03\00\00\00"
    "\00\41"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[25]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00\41\00\0b\03\00\00\00\00\41\00\0b\03\00\00\00"
    "\00\41\00"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[26]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00\41\00\0b\03\00\00\00\00\41\00\0b\03\00\00\00"
    "\00\41\00\0b"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[27]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00\41\00\0b\03\00\00\00\00\41\00\0b\03\00\00\00"
    "\00\41\00\0b\03"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[28]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00\41\00\0b\03\00\00\00\00\41\00\0b\03\00\00\00"
    "\00\41\00\0b\03\00"
  )
  "length out of bounds"
)

;; unittest bin:elementsN[29]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\19\03"
    "\00\41\00\0b\03\00\00\00\00\41\00\0b\03\00\00\00"
    "\00\41\00\0b\03\00\00"
  )
  "unexpected end of section or function"
)

;; unittest bin:elementsN[30]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\02\00"
    "\63"
  )
  "section size mismatch"
)

;; unittest bin:elementsN[31]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\0a\01"
    "\00\41\00\0b\03\00\00\00\63"
  )
  "section size mismatch"
)

;; unittest bin:elementsN[32]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\12\02"
    "\00\41\00\0b\03\00\00\00\00\41\00\0b\03\00\00\00"
    "\63"
  )
  "section size mismatch"
)

;; unittest bin:elementsN[33]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\05\09\1a\03"
    "\00\41\00\0b\03\00\00\00\00\41\00\0b\03\00\00\00"
    "\00\41\00\0b\03\00\00\00\63"
  )
  "section size mismatch"
)

