;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:magic[1]: MALFORMED INVALID_HEADER [none]
(assert_malformed
  (module binary
    "\ff\61\73\6d\01\00\00\00"
  )
  "magic header not detected"
)

;; unittest bin:magic[2]: MALFORMED INVALID_HEADER [none]
(assert_malformed
  (module binary
    "\00\ff\73\6d\01\00\00\00"
  )
  "magic header not detected"
)

;; unittest bin:magic[3]: MALFORMED INVALID_HEADER [none]
(assert_malformed
  (module binary
    "\00\61\ff\6d\01\00\00\00"
  )
  "magic header not detected"
)

;; unittest bin:magic[4]: MALFORMED INVALID_HEADER [none]
(assert_malformed
  (module binary
    "\00\61\73\ff\01\00\00\00"
  )
  "magic header not detected"
)

