;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:start2[1]: INVALID ILLEGAL_TYPE [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\05\01\60\01\7f\00\03"
    "\02\01\00\08\01\00"
  )
  ""
)

;; unittest bin:start2[2]: INVALID ILLEGAL_TYPE [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\05\01\60\00\01\7f\03"
    "\02\01\00\08\01\00"
  )
  ""
)

