;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:sect_size0[1]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\00\00"
  )
  "section size mismatch"
)

;; unittest bin:sect_size0[2]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\00\00"
  )
  "section size mismatch"
)

;; unittest bin:sect_size0[3]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\03\00\00"
  )
  "section size mismatch"
)

;; unittest bin:sect_size0[4]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\04\00\00"
  )
  "section size mismatch"
)

;; unittest bin:sect_size0[5]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\00\00"
  )
  "section size mismatch"
)

;; unittest bin:sect_size0[6]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\00\00"
  )
  "section size mismatch"
)

;; unittest bin:sect_size0[7]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\07\00\00"
  )
  "section size mismatch"
)

;; unittest bin:sect_size0[8]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\09\00\00"
  )
  "section size mismatch"
)

;; unittest bin:sect_size0[9]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\0a\00\00"
  )
  "section size mismatch"
)

;; unittest bin:sect_size0[10]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\0b\00\00"
  )
  "section size mismatch"
)

