;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:sect_dup[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\01\00"
)

;; unittest bin:sect_dup[2]: MALFORMED DUPLICATE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\01\00\01\01\00"
  )
  "unexpected content after last section"
)

;; unittest bin:sect_dup[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\02\01\00"
)

;; unittest bin:sect_dup[4]: MALFORMED DUPLICATE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\01\00\02\01\00"
  )
  "unexpected content after last section"
)

;; unittest bin:sect_dup[5]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\03\01\00"
)

;; unittest bin:sect_dup[6]: MALFORMED DUPLICATE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\03\01\00\03\01\00"
  )
  "unexpected content after last section"
)

;; unittest bin:sect_dup[7]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\04\01\00"
)

;; unittest bin:sect_dup[8]: MALFORMED DUPLICATE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\04\01\00\04\01\00"
  )
  "unexpected content after last section"
)

;; unittest bin:sect_dup[9]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\01\00"
)

;; unittest bin:sect_dup[10]: MALFORMED DUPLICATE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\01\00\05\01\00"
  )
  "unexpected content after last section"
)

;; unittest bin:sect_dup[11]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\06\01\00"
)

;; unittest bin:sect_dup[12]: MALFORMED DUPLICATE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\01\00\06\01\00"
  )
  "unexpected content after last section"
)

;; unittest bin:sect_dup[13]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\07\01\00"
)

;; unittest bin:sect_dup[14]: MALFORMED DUPLICATE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\07\01\00\07\01\00"
  )
  "unexpected content after last section"
)

;; unittest bin:sect_dup[15]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\09\01\00"
)

;; unittest bin:sect_dup[16]: MALFORMED DUPLICATE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\09\01\00\09\01\00"
  )
  "unexpected content after last section"
)

;; unittest bin:sect_dup[17]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\0a\01\00"
)

;; unittest bin:sect_dup[18]: MALFORMED DUPLICATE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\0a\01\00\0a\01\00"
  )
  "unexpected content after last section"
)

;; unittest bin:sect_dup[19]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\0b\01\00"
)

;; unittest bin:sect_dup[20]: MALFORMED DUPLICATE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\0b\01\00\0b\01\00"
  )
  "unexpected content after last section"
)

