;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:memoriesN[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\01\00"
)

;; unittest bin:memoriesN[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\03\01\00\00"
)

;; unittest bin:memoriesN[3]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03"
  )
  "length out of bounds"
)

;; unittest bin:memoriesN[4]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01"
  )
  "length out of bounds"
)

;; unittest bin:memoriesN[5]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00"
  )
  "unexpected end of section or function"
)

;; unittest bin:memoriesN[6]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\02\00\63"
  )
  "section size mismatch"
)

;; unittest bin:memoriesN[7]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\04\01\00\00\63"
  )
  "section size mismatch"
)

