;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:bad_sub3[1]: INVALID ILLEGAL_SUPERTYPE [gc]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\88\80\80\80\00\02\5f"
    "\00\50\01\00\5f\00"
  )
  "sub type 1 has final super type 0"
)

;; unittest bin:bad_sub3[2]: INVALID ILLEGAL_SUPERTYPE [gc]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\8a\80\80\80\00\02\5e"
    "\78\00\50\01\00\5e\78\00"
  )
  "sub type 1 has final super type 0"
)

;; unittest bin:bad_sub3[3]: INVALID ILLEGAL_SUPERTYPE [gc]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\8c\80\80\80\00\02\60"
    "\00\01\7f\50\01\00\60\00\01\7f"
  )
  "sub type 1 has final super type 0"
)

