;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:start1[1]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\08\81\80\80\80\00\00"
  )
  "unknown function 0"
)

;; unittest bin:start1[2]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\08\81\80\80\80\00\01"
  )
  "unknown function 1"
)

;; unittest bin:start1[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
  "\01\01\4d\01\66\00\00\08\81\80\80\80\00\00"
)

;; unittest bin:start1[4]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\08\81\80\80\80\00\01"
  )
  "unknown function 1"
)

;; unittest bin:start1[5]: MALFORMED INCOMPLETE_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\08\82\80\80\80\00\00\00"
  )
  "section size mismatch"
)

