;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:code0[1]: MALFORMED FUNC_COUNT_MISMATCH [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\02"
    "\01\00\0a\81\80\80\80\00\00"
  )
  "function and code section have inconsistent lengths"
)

;; unittest bin:code0[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\02"
  "\01\00\0a\84\80\80\80\00\01\02\00\0b"
)

;; unittest bin:code0[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\02"
  "\01\00\0a\85\80\80\80\00\01\03\00\01\0b"
)

;; unittest bin:code0[4]: MALFORMED FUNC_COUNT_MISMATCH [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\02"
    "\01\00\0a\83\80\80\80\00\02\00\00"
  )
  "unexpected end of section or function"
)

