;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:sect_eof[1]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\01\01"
  )
  "unexpected end of section or function"
)

;; unittest bin:sect_eof[2]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\02\01\01"
  )
  "unexpected end of section or function"
)

;; unittest bin:sect_eof[3]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\03\01\01"
  )
  "unexpected end of section or function"
)

;; unittest bin:sect_eof[4]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\04\01\01"
  )
  "unexpected end of section or function"
)

;; unittest bin:sect_eof[5]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\05\01\01"
  )
  "unexpected end of section or function"
)

;; unittest bin:sect_eof[6]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\06\01\01"
  )
  "unexpected end of section or function"
)

;; unittest bin:sect_eof[7]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\07\01\01"
  )
  "unexpected end of section or function"
)

;; unittest bin:sect_eof[8]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\09\01\01"
  )
  "unexpected end of section or function"
)

;; unittest bin:sect_eof[9]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\0b\01\01"
  )
  "unexpected end of section or function"
)

