;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:funcs1[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\8a\80\80\80\00\03\60"
  "\00\00\60\00\00\60\00\00\03\82\80\80\80\00\01\00"
  "\0a\04\01\02\00\0b"
)

;; unittest bin:funcs1[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\8a\80\80\80\00\03\60"
  "\00\00\60\00\00\60\00\00\03\83\80\80\80\00\01\81"
  "\00\0a\04\01\02\00\0b"
)

;; unittest bin:funcs1[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\8a\80\80\80\00\03\60"
  "\00\00\60\00\00\60\00\00\03\83\80\80\80\00\01\82"
  "\00\0a\04\01\02\00\0b"
)

;; unittest bin:funcs1[4]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\8a\80\80\80\00\03\60"
    "\00\00\60\00\00\60\00\00\03\82\80\80\80\00\01\04"
    "\0a\04\01\02\00\0b"
  )
  "unknown type 4"
)

;; unittest bin:funcs1[5]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\8a\80\80\80\00\03\60"
    "\00\00\60\00\00\60\00\00\03\82\80\80\80\00\01\05"
    "\0a\04\01\02\00\0b"
  )
  "unknown type 5"
)

