;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:exports0[1]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\07\85\80\80\80\00\01\01"
    "\66\00\00"
  )
  "unknown function 0"
)

;; unittest bin:exports0[2]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\07\85\80\80\80\00\01\01"
    "\74\01\00"
  )
  "unknown table 0"
)

;; unittest bin:exports0[3]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\07\85\80\80\80\00\01\01"
    "\6d\02\00"
  )
  "unknown memory 0"
)

;; unittest bin:exports0[4]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\07\85\80\80\80\00\01\01"
    "\67\03\00"
  )
  "unknown global 0"
)

;; unittest bin:exports0[5]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\02"
  "\01\00\07\86\80\80\80\00\01\02\63\64\00\00\0a\04"
  "\01\02\00\0b"
)

;; unittest bin:exports0[6]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\02"
  "\01\00\07\8b\80\80\80\00\02\02\63\64\00\00\02\63"
  "\66\00\00\0a\04\01\02\00\0b"
)

;; unittest bin:exports0[7]: INVALID DUPLICATE_EXPORT [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\02"
    "\01\00\07\8b\80\80\80\00\02\02\46\65\00\00\02\46"
    "\65\00\00\0a\04\01\02\00\0b"
  )
  ""
)

;; unittest bin:exports0[8]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\02"
    "\01\00\07\86\80\80\80\00\01\02\63\64\00\01\0a\04"
    "\01\02\00\0b"
  )
  "unknown function 1"
)

;; unittest bin:exports0[9]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\04\04\01\70\00\00\07\86"
  "\80\80\80\00\01\02\66\67\01\00"
)

;; unittest bin:exports0[10]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\04\04\01\70\00\00\07\86"
    "\80\80\80\00\01\02\66\67\01\01"
  )
  "unknown table 1"
)

;; unittest bin:exports0[11]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\03\01\00\01\07\87\80"
  "\80\80\00\01\03\78\79\7a\02\00"
)

;; unittest bin:exports0[12]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\05\03\01\00\01\07\87\80"
    "\80\80\00\01\03\78\79\7a\02\01"
  )
  "unknown memory 1"
)

;; unittest bin:exports0[13]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
  "\07\84\80\80\80\00\01\00\03\00"
)

;; unittest bin:exports0[14]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\06\06\01\7f\00\41\00\0b"
    "\07\84\80\80\80\00\01\00\03\01"
  )
  "unknown global 1"
)

