;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:globals2[1]: INVALID INVALID_INIT_EXPR [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\06\89\80\80\80\00\01\7d"
    "\00\01\00\00\00\00\0b"
  )
  "constant expression required"
)

;; unittest bin:globals2[2]: INVALID INVALID_INIT_EXPR [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\06\8b\80\80\80\00\02\7f"
    "\00\41\02\0b\7f\00\23\00\0b"
  )
  ""
)

;; unittest bin:globals2[3]: INVALID INVALID_INIT_EXPR [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\06\8b\80\80\80\00\02\7f"
    "\01\41\02\0b\7f\00\23\00\0b"
  )
  "constant expression required"
)

