;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:globals1[1]: INVALID INVALID_INIT_EXPR [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\06\8b\80\80\80\00\02\7f"
    "\00\41\01\0b\7f\00\23\00\0b"
  )
  ""
)

;; unittest bin:globals1[2]: INVALID INVALID_INIT_EXPR [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\06\8b\80\80\80\00\02\7e"
    "\00\42\01\0b\7f\00\23\00\0b"
  )
  "type mismatch: instruction requires [i32] but stack has [i64]"
)

;; unittest bin:globals1[3]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\06\86\80\80\80\00\01\7f"
    "\00\23\00\0b"
  )
  "unknown global 0"
)

;; unittest bin:globals1[4]: VALID [gc]
(module definition binary
  "\00\61\73\6d\01\00\00\00\06\8b\80\80\80\00\02\7f"
  "\00\41\01\0b\7f\00\23\00\0b"
)

;; unittest bin:globals1[5]: INVALID TYPE_MISMATCH [gc]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\06\8b\80\80\80\00\02\7e"
    "\00\42\01\0b\7f\00\23\00\0b"
  )
  "type mismatch: instruction requires [i32] but stack has [i64]"
)

