;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:bad_sub0[1]: INVALID ILLEGAL_SUPERTYPE [gc]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\8e\80\80\80\00\02\50"
    "\00\60\00\01\7f\50\01\00\60\00\01\7e"
  )
  "sub type 1 does not match super type 0"
)

;; unittest bin:bad_sub0[2]: INVALID ILLEGAL_SUPERTYPE [gc]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\8c\80\80\80\00\02\50"
    "\00\5f\00\50\01\00\60\00\01\7c"
  )
  "sub type 1 does not match super type 0"
)

;; unittest bin:bad_sub0[3]: INVALID ILLEGAL_SUPERTYPE [gc]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\8d\80\80\80\00\02\50"
    "\00\5e\78\00\50\01\00\60\00\01\7d"
  )
  "sub type 1 does not match super type 0"
)

