;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:max_num_memories[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\02\88\80\80\80\00\01\01"
  "\4d\01\6d\02\00\00"
)

;; unittest bin:max_num_memories[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\84\80\80\80\00\01\01"
  "\03\04"
)

;; unittest bin:max_num_memories[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\02\81\80\80\80\00\00\05"
  "\84\80\80\80\00\01\01\03\04"
)

;; skipped: EXCEEDED_LIMIT is an engine-specific limit
;; skipped: EXCEEDED_LIMIT is an engine-specific limit
;; skipped: EXCEEDED_LIMIT is an engine-specific limit
;; unittest bin:max_num_memories[4]: VALID [multi-memory]
(module definition binary
  "\00\61\73\6d\01\00\00\00\02\9d\80\80\80\00\04\01"
  "\4d\01\6d\02\00\00\01\4d\01\6d\02\00\00\01\4d\01"
  "\6d\02\00\00\01\4d\01\6d\02\00\00"
)

;; unittest bin:max_num_memories[5]: VALID [multi-memory]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\8d\80\80\80\00\04\01"
  "\03\04\01\03\04\01\03\04\01\03\04"
)

;; unittest bin:max_num_memories[6]: VALID [multi-memory]
(module definition binary
  "\00\61\73\6d\01\00\00\00\02\96\80\80\80\00\03\01"
  "\4d\01\6d\02\00\00\01\4d\01\6d\02\00\00\01\4d\01"
  "\6d\02\00\00\05\84\80\80\80\00\01\01\03\04"
)

;; unittest bin:max_num_memories[7]: VALID [multi-memory]
(module definition binary
  "\00\61\73\6d\01\00\00\00\02\a4\80\80\80\00\05\01"
  "\4d\01\6d\02\00\00\01\4d\01\6d\02\00\00\01\4d\01"
  "\6d\02\00\00\01\4d\01\6d\02\00\00\01\4d\01\6d\02"
  "\00\00"
)

;; unittest bin:max_num_memories[8]: VALID [multi-memory]
(module definition binary
  "\00\61\73\6d\01\00\00\00\05\90\80\80\80\00\05\01"
  "\03\04\01\03\04\01\03\04\01\03\04\01\03\04"
)

;; unittest bin:max_num_memories[9]: VALID [multi-memory]
(module definition binary
  "\00\61\73\6d\01\00\00\00\02\9d\80\80\80\00\04\01"
  "\4d\01\6d\02\00\00\01\4d\01\6d\02\00\00\01\4d\01"
  "\6d\02\00\00\01\4d\01\6d\02\00\00\05\84\80\80\80"
  "\00\01\01\03\04"
)

;; skipped: EXCEEDED_LIMIT is an engine-specific limit
;; skipped: EXCEEDED_LIMIT is an engine-specific limit
;; skipped: EXCEEDED_LIMIT is an engine-specific limit
