;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:types0[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\01\00"
)

;; unittest bin:types0[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00"
)

;; unittest bin:types0[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\07\02\60\00\00\60\00"
  "\00"
)

;; unittest bin:types0[4]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\0a\03\60\00\00\60\00"
  "\00\60\00\00"
)

;; unittest bin:types0[5]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\0d\04\60\00\00\60\00"
  "\00\60\00\00\60\00\00"
)

