;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:funcs2[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
  "\01\01\4d\01\66\00\00\03\82\80\80\80\00\01\00\0a"
  "\04\01\02\00\0b"
)

;; unittest bin:funcs2[2]: MALFORMED FUNC_COUNT_MISMATCH [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\03\81\80\80\80\00\00\0a\04"
    "\01\02\00\0b"
  )
  "function and code section have inconsistent lengths"
)

;; unittest bin:funcs2[3]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\03\82\80\80\80\00\01\01\0a"
    "\04\01\02\00\0b"
  )
  "unknown type 1"
)

;; unittest bin:funcs2[4]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\03\82\80\80\80\00\01\04\0a"
    "\04\01\02\00\0b"
  )
  "unknown type 4"
)

;; unittest bin:funcs2[5]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\03\81\80\80\80\00\01\0a\04"
    "\01\02\00\0b"
  )
  "section size mismatch"
)

