;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:bad_sub1[1]: INVALID ILLEGAL_SUPERTYPE [gc]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\8c\80\80\80\00\02\50"
    "\00\5f\01\78\00\50\01\00\5f\00"
  )
  "sub type 1 does not match super type 0"
)

;; unittest bin:bad_sub1[2]: INVALID ILLEGAL_SUPERTYPE [gc]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\8c\80\80\80\00\02\50"
    "\00\60\00\01\7c\50\01\00\5f\00"
  )
  "sub type 1 does not match super type 0"
)

;; unittest bin:bad_sub1[3]: INVALID ILLEGAL_SUPERTYPE [gc]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\8c\80\80\80\00\02\50"
    "\00\60\00\01\7d\50\01\00\5f\00"
  )
  "sub type 1 does not match super type 0"
)

