;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:imports0[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\87"
  "\80\80\80\00\01\01\4d\01\67\00\00"
)

;; unittest bin:imports0[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\89"
  "\80\80\80\00\01\01\4e\01\68\01\70\00\00"
)

;; unittest bin:imports0[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\88"
  "\80\80\80\00\01\01\4f\01\69\02\00\00"
)

;; unittest bin:imports0[4]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\88"
  "\80\80\80\00\01\01\50\01\6a\03\7f\00"
)

;; unittest bin:imports0[5]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\87"
    "\80\80\80\00\01\01\50\01\6a\03\7f"
  )
  "unexpected end of section or function"
)

