;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:imports3[1]: MALFORMED INVALID_UTF8_STRING [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\87"
    "\80\80\80\00\01\01\87\01\67\00\00"
  )
  "malformed UTF-8 encoding"
)

;; unittest bin:imports3[2]: MALFORMED INVALID_UTF8_STRING [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\87"
    "\80\80\80\00\01\01\57\01\86\00\00"
  )
  "malformed UTF-8 encoding"
)

