;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:func_ref_types0[1]: MALFORMED INVALID_TYPE [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\89\80\80\80\00\02\60"
    "\00\00\60\00\01\64\00"
  )
  ""
)

;; unittest bin:func_ref_types0[2]: VALID [function-references]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\89\80\80\80\00\02\60"
  "\00\00\60\01\63\00\00"
)

;; unittest bin:func_ref_types0[3]: INVALID OOB_INDEX [function-references]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\89\80\80\80\00\02\60"
    "\00\00\60\01\63\02\00"
  )
  "unknown type 2"
)

