;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:elements2[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\04\04\01\70\00\00\09\86"
  "\80\80\80\00\01\00\41\00\0b\00"
)

;; unittest bin:elements2[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\04\04\01\70\00\00\09\86"
  "\80\80\80\00\01\04\41\00\0b\00"
)

;; unittest bin:elements2[3]: INVALID TYPE_MISMATCH [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\04\04\01\70\00\00\09\89"
    "\80\80\80\00\01\04\41\00\0b\01\41\00\0b"
  )
  "type mismatch: instruction requires [(ref null func)] but stack has [i32]"
)

