;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:elements0[1]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\09\86\80\80\80\00\01\00"
    "\41\00\0b\00"
  )
  "unknown table 0"
)

;; unittest bin:elements0[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\04\04\01\70\00\00\09\86"
  "\80\80\80\00\01\00\41\00\0b\00"
)

;; unittest bin:elements0[3]: INVALID TYPE_MISMATCH [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\04\04\01\70\00\00\09\86"
    "\80\80\80\00\01\00\42\00\0b\00"
  )
  "type mismatch: instruction requires [i32] but stack has [i64]"
)

;; unittest bin:elements0[4]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\04\04\01\70\00\00\09\87"
    "\80\80\80\00\01\00\41\00\0b\01\00"
  )
  "unknown function 0"
)

;; unittest bin:elements0[5]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
  "\01\01\4d\01\66\00\00\04\04\01\70\00\00\09\87\80"
  "\80\80\00\01\00\41\00\0b\01\00"
)

;; unittest bin:elements0[6]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
  "\01\01\4d\01\66\00\00\04\04\01\70\00\00\09\89\80"
  "\80\80\00\01\00\41\00\0b\03\00\00\00"
)

;; unittest bin:elements0[7]: INVALID OOB_INDEX [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\02\07"
    "\01\01\4d\01\66\00\00\04\04\01\70\00\00\09\87\80"
    "\80\80\00\01\00\41\00\0b\01\01"
  )
  "unknown function 1"
)

