;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:tables0[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\04\84\80\80\80\00\01\70"
  "\00\00"
)

;; unittest bin:tables0[2]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\04\84\80\80\80\00\01\70"
  "\00\02"
)

;; unittest bin:tables0[3]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\04\85\80\80\80\00\01\70"
  "\01\02\03"
)

;; unittest bin:tables0[4]: INVALID ILLEGAL_TYPE [none]
(assert_invalid
  (module binary
    "\00\61\73\6d\01\00\00\00\04\84\80\80\80\00\01\7f"
    "\00\00"
  )
  ""
)

;; unittest bin:tables0[5]: MALFORMED OVERFLOW_SECTION [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\04\84\80\80\80\00\01\70"
    "\01\02"
  )
  "unexpected end of section or function"
)

