;; generated by test/regress/binary/record.sh; do not edit

;; unittest bin:code2[1]: VALID [none]
(module definition binary
  "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\82"
  "\80\80\80\00\01\00\0a\84\80\80\80\00\01\02\00\0b"
)

;; unittest bin:code2[2]: MALFORMED INCOMPLETE_FUNCTION_BODY [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\82"
    "\80\80\80\00\01\00\0a\81\80\80\80\00\01"
  )
  "unexpected end of section or function"
)

;; unittest bin:code2[3]: MALFORMED INCOMPLETE_FUNCTION_BODY [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\82"
    "\80\80\80\00\01\00\0a\83\80\80\80\00\01\02\00"
  )
  "unexpected end of section or function"
)

;; unittest bin:code2[4]: MALFORMED INCOMPLETE_FUNCTION_BODY [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\82"
    "\80\80\80\00\01\00\0a\82\80\80\80\00\01\42"
  )
  "length out of bounds"
)

;; unittest bin:code2[5]: MALFORMED INCOMPLETE_FUNCTION_BODY [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\82"
    "\80\80\80\00\01\00\0a\85\80\80\80\00\01\b0\97\d3"
    "\03"
  )
  "length out of bounds"
)

;; unittest bin:code2[6]: MALFORMED INCOMPLETE_FUNCTION_BODY [none]
(assert_malformed
  (module binary
    "\00\61\73\6d\01\00\00\00\01\04\01\60\00\00\03\82"
    "\80\80\80\00\01\00\0a\85\80\80\80\00\01\b1\97\d3"
    "\03"
  )
  "length out of bounds"
)

;; skipped: EXCEEDED_LIMIT is an engine-specific limit
